import { Przepis } from '../przepis.model';

/** Kashotto, kung pao, lasagne, miso, müsli, zupa grzybowa, owsianka,
 *  okonomiyaki, omlety, osso buco, pad thai, paella. */
export const PACZKA_3: Przepis[] = [
  // ---------- kashotto-details ----------
  {
    slug: 'mushroom-kashotto-details',
    parent: 'kashotto-details',
    nazwa: 'Mushroom kashotto',
    opis: 'Risotto z kaszy pęczak z pieczarkami — polska odpowiedź na włoski oryginał.',
    porcje: 4,
    czasMinut: 50,
    skladniki: ['300 g kaszy pęczak', '400 g pieczarek', '1 l bulionu warzywnego', '1 cebula', '100 ml białego wina', '50 g parmezanu', '40 g masła', 'tymianek'],
    kroki: [
      'Pieczarki podsmaż na dużym ogniu i odłóż — muszą się zarumienić, nie udusić.',
      'Zeszklij cebulę, wsyp kaszę i praż 2 minuty.',
      'Wlej wino, odparuj, potem dolewaj gorący bulion chochlą, mieszając.',
      'Po 30 minutach wróć grzyby.',
      'Zdejmij z ognia, wmieszaj masło i parmezan.',
    ],
  },
  {
    slug: 'pumpkin-and-sage-kashotto-details',
    parent: 'kashotto-details',
    nazwa: 'Pumpkin and sage kashotto',
    opis: 'Kremowe kashotto z pieczoną dynią i smażoną szałwią.',
    porcje: 4,
    czasMinut: 60,
    skladniki: ['300 g kaszy pęczak', '500 g dyni hokkaido', '1 l bulionu', 'pęczek szałwii', '1 cebula', '50 g parmezanu', 'masło', 'gałka muszkatołowa'],
    kroki: [
      'Dynię pokrój w kostkę i piecz 25 minut w 200°C.',
      'Kaszę przygotuj jak risotto, dolewając bulion partiami.',
      'Połowę dyni zblenduj i wmieszaj, resztę dodaj w kawałkach.',
      'Szałwię usmaż na maśle do chrupkości i połóż na wierzchu.',
    ],
  },
  {
    slug: 'spinach-and-feta-kashotto-details',
    parent: 'kashotto-details',
    nazwa: 'Spinach and feta kashotto',
    opis: 'Kasza ze szpinakiem i fetą, doprawiona skórką z cytryny.',
    porcje: 4,
    czasMinut: 45,
    skladniki: ['300 g kaszy pęczak', '300 g szpinaku', '150 g fety', '1 l bulionu', '1 cebula', 'skórka z cytryny', 'oliwa', 'pieprz'],
    kroki: [
      'Kaszę praż z cebulą, potem dolewaj bulion partiami przez 30 minut.',
      'Wmieszaj szpinak — zwiędnie w minutę od gorąca kaszy.',
      'Dodaj pokruszoną fetę i skórkę z cytryny.',
      'Dopraw pieprzem; soli raczej nie trzeba przez fetę.',
    ],
  },
  {
    slug: 'butternut-squash-and-walnut-kashotto-details',
    parent: 'kashotto-details',
    nazwa: 'Butternut squash and walnut kashotto',
    opis: 'Z dynią piżmową i prażonymi orzechami włoskimi dla chrupkości.',
    porcje: 4,
    czasMinut: 60,
    skladniki: ['300 g kaszy pęczak', '500 g dyni piżmowej', '80 g orzechów włoskich', '1 l bulionu', 'ser pleśniowy 80 g', 'tymianek', 'masło'],
    kroki: [
      'Dynię upiecz z tymiankiem przez 25 minut.',
      'Kaszę ugotuj metodą risotto.',
      'Orzechy upraż na suchej patelni i grubo posiekaj.',
      'Połącz wszystko, na wierzch pokrusz ser pleśniowy.',
    ],
  },
  {
    slug: 'asparagus-and-lemon-kashotto-details',
    parent: 'kashotto-details',
    nazwa: 'Asparagus and lemon kashotto',
    opis: 'Wiosenna wersja ze szparagami i dużą ilością cytryny.',
    porcje: 4,
    czasMinut: 45,
    skladniki: ['300 g kaszy pęczak', '500 g zielonych szparagów', '1 l bulionu', '1 cytryna', '50 g parmezanu', 'masło', 'natka pietruszki'],
    kroki: [
      'Szparagi pokrój na kawałki, końcówki zostaw w całości.',
      'Blanszuj 2 minuty i przełóż do lodowatej wody, żeby zachowały kolor.',
      'Ugotuj kaszę metodą risotto.',
      'Wmieszaj szparagi, sok i skórkę z cytryny, masło i parmezan.',
    ],
  },

  // ---------- kung-pao-details ----------
  {
    slug: 'chicken-kung-pao-details',
    parent: 'kung-pao-details',
    nazwa: 'Chicken kung pao',
    opis: 'Syczuańskie danie z kurczakiem, orzeszkami ziemnymi i pieprzem syczuańskim.',
    porcje: 4,
    czasMinut: 35,
    skladniki: ['500 g piersi z kurczaka', '100 g orzeszków ziemnych', '8 suszonych papryczek chili', '1 łyżeczka pieprzu syczuańskiego', '3 łyżki sosu sojowego', '2 łyżki octu ryżowego', '1 łyżka cukru', 'dymka', 'skrobia'],
    kroki: [
      'Kurczaka pokrój w kostkę i zamarynuj w sosie sojowym ze skrobią na 15 minut.',
      'Rozgrzej wok do dymu, wrzuć chili i pieprz syczuański na 20 sekund.',
      'Dodaj mięso i smaż 3 minuty na dużym ogniu.',
      'Wlej sos z octu, cukru i sojowego, zagęść skrobią.',
      'Na koniec wsyp orzeszki i dymkę — orzeszki mają zostać chrupiące.',
    ],
  },
  {
    slug: 'shrimp-kung-pao-details',
    parent: 'kung-pao-details',
    nazwa: 'Shrimp kung pao',
    opis: 'Wersja z krewetkami, smażona jeszcze krócej niż oryginał.',
    porcje: 4,
    czasMinut: 25,
    skladniki: ['500 g krewetek', '100 g orzeszków nerkowca', '6 suszonych chili', 'pieprz syczuański', 'sos sojowy', 'ocet ryżowy', 'czosnek', 'imbir', 'dymka'],
    kroki: [
      'Krewetki osusz — mokre będą się dusić zamiast smażyć.',
      'Podsmaż chili i przyprawy, dodaj czosnek z imbirem.',
      'Wrzuć krewetki i smaż 2 minuty.',
      'Zalej sosem, zagęść i dodaj orzechy oraz dymkę.',
    ],
  },
  {
    slug: 'tofu-kung-pao-details',
    parent: 'kung-pao-details',
    nazwa: 'Tofu kung pao',
    opis: 'Wegetariańska wersja z podsmażonym tofu w chrupiącej skorupce.',
    porcje: 4,
    czasMinut: 40,
    skladniki: ['400 g tofu twardego', 'skrobia kukurydziana', '100 g orzeszków ziemnych', 'suszone chili', 'sos sojowy', 'ocet ryżowy', 'cukier', 'papryka', 'dymka'],
    kroki: [
      'Tofu odciśnij przez 20 minut pod obciążeniem, pokrój w kostkę.',
      'Obtocz w skrobi i smaż na złoto ze wszystkich stron.',
      'Odłóż, na tym samym oleju podsmaż chili i paprykę.',
      'Wróć tofu, zalej sosem i wsyp orzeszki.',
    ],
  },
  {
    slug: 'beef-kung-pao-details',
    parent: 'kung-pao-details',
    nazwa: 'Beef kung pao',
    opis: 'Z cienko krojoną wołowiną marynowaną w sosie sojowym ze skrobią.',
    porcje: 4,
    czasMinut: 35,
    skladniki: ['500 g polędwicy wołowej', 'skrobia', '100 g orzeszków ziemnych', 'suszone chili', 'pieprz syczuański', 'sos sojowy', 'ocet', 'cukier', 'czosnek'],
    kroki: [
      'Wołowinę pokrój w poprzek włókien i zamarynuj ze skrobią.',
      'Smaż partiami na bardzo gorącym woku po 90 sekund.',
      'Podsmaż przyprawy, wróć mięso.',
      'Zalej sosem i zagęść, dodaj orzeszki.',
    ],
  },
  {
    slug: 'pork-kung-pao-details',
    parent: 'kung-pao-details',
    nazwa: 'Pork kung pao',
    opis: 'Wieprzowa wersja z dodatkiem papryki i selera naciowego.',
    porcje: 4,
    czasMinut: 35,
    skladniki: ['500 g schabu', '2 łodygi selera naciowego', '1 papryka', '100 g orzeszków', 'suszone chili', 'sos sojowy', 'ocet ryżowy', 'skrobia'],
    kroki: [
      'Schab pokrój w kostkę i zamarynuj ze skrobią i sosem sojowym.',
      'Smaż na woku 4 minuty, odłóż.',
      'Podsmaż seler i paprykę przez 2 minuty — mają zostać chrupiące.',
      'Połącz z mięsem, zalej sosem, dodaj orzeszki.',
    ],
  },

  // ---------- lasagne-details ----------
  {
    slug: 'beef-lasagne-details',
    parent: 'lasagne-details',
    nazwa: 'Beef lasagne',
    opis: 'Klasyczna lasagne bolognese z sosem mięsnym i beszamelem.',
    porcje: 6,
    czasMinut: 180,
    skladniki: ['12 płatów lasagne', '600 g mielonej wołowiny', '800 g pomidorów', '1 l mleka', '80 g masła', '80 g mąki', '150 g parmezanu', 'włoszczyzna', 'czerwone wino'],
    kroki: [
      'Zrób sofrito z cebuli, marchwi i selera, smażąc 10 minut.',
      'Dodaj mięso, obsmaż, wlej wino i odparuj.',
      'Dodaj pomidory i duś ragù minimum 90 minut na małym ogniu.',
      'Ugotuj beszamel z masła, mąki i mleka.',
      'Układaj warstwami: ragù, płat, beszamel, parmezan. Piecz 40 minut w 180°C.',
    ],
  },
  {
    slug: 'vegetarian-lasagne-details',
    parent: 'lasagne-details',
    nazwa: 'Vegetarian lasagne',
    opis: 'Z warstwami grillowanej cukinii, bakłażana i papryki.',
    porcje: 6,
    czasMinut: 120,
    skladniki: ['12 płatów lasagne', '2 cukinie', '1 bakłażan', '2 papryki', '800 g passaty', 'beszamel', '200 g mozzarelli', 'bazylia'],
    kroki: [
      'Warzywa pokrój w plastry i grilluj, aż stracą wodę.',
      'Przygotuj sos pomidorowy z passaty, czosnku i bazylii.',
      'Układaj warstwami warzywa, sos, beszamel i płaty.',
      'Piecz 40 minut w 180°C, ostatnie 10 minut bez folii.',
    ],
  },
  {
    slug: 'seafood-lasagne-details',
    parent: 'lasagne-details',
    nazwa: 'Seafood lasagne',
    opis: 'Lasagne z owocami morza w białym sosie, bez pomidorów.',
    porcje: 6,
    czasMinut: 100,
    skladniki: ['12 płatów lasagne', '300 g krewetek', '300 g małży', '200 g kalmarów', '1 l beszamelu', '150 ml białego wina', 'czosnek', 'natka pietruszki'],
    kroki: [
      'Owoce morza podduś z winem i czosnkiem przez 4 minuty.',
      'Odcedź, a płyn wmieszaj w beszamel — to on niesie smak.',
      'Układaj warstwy: beszamel, płat, owoce morza.',
      'Piecz 35 minut w 180°C i posyp natką.',
    ],
  },
  {
    slug: 'chicken-and-spinach-lasagne-details',
    parent: 'lasagne-details',
    nazwa: 'Chicken and spinach lasagne',
    opis: 'Delikatna wersja z kurczakiem, szpinakiem i ricottą.',
    porcje: 6,
    czasMinut: 110,
    skladniki: ['12 płatów lasagne', '600 g piersi z kurczaka', '400 g szpinaku', '400 g ricotty', 'beszamel', '150 g mozzarelli', 'gałka muszkatołowa'],
    kroki: [
      'Kurczaka pokrój w kostkę i podsmaż z czosnkiem.',
      'Szpinak zblanszuj i odciśnij, wymieszaj z ricottą i gałką muszkatołową.',
      'Układaj warstwami kurczaka, masę szpinakową i beszamel.',
      'Piecz 40 minut w 180°C.',
    ],
  },
  {
    slug: 'four-cheese-lasagne-details',
    parent: 'lasagne-details',
    nazwa: 'Four cheese lasagne',
    opis: 'Bez mięsa i bez pomidorów — cztery sery w beszamelu.',
    porcje: 6,
    czasMinut: 80,
    skladniki: ['12 płatów lasagne', '150 g gorgonzoli', '150 g mozzarelli', '100 g parmezanu', '150 g fontiny', '1 l beszamelu', 'gałka muszkatołowa', 'pieprz'],
    kroki: [
      'Sery zetrzyj lub pokrusz i wymieszaj, zostawiając część parmezanu na wierzch.',
      'Beszamel dopraw gałką muszkatołową i pieprzem.',
      'Układaj warstwami: beszamel, płat, mieszanka serów.',
      'Piecz 35 minut w 180°C do zarumienienia.',
    ],
  },

  // ---------- miso-details ----------
  {
    slug: 'with-tofu-and-wakame-details',
    parent: 'miso-details',
    nazwa: 'Miso soup with tofu and wakame',
    opis: 'Podstawowa japońska zupa miso z kostkami tofu i wodorostami wakame.',
    porcje: 4,
    czasMinut: 20,
    skladniki: ['800 ml dashi', '3 łyżki pasty miso', '200 g tofu jedwabistego', '10 g suszonych wakame', 'dymka'],
    kroki: [
      'Wakame namocz w zimnej wodzie na 10 minut.',
      'Podgrzej dashi, ale nie doprowadzaj do wrzenia.',
      'Rozprowadź miso w chochli bulionu i wmieszaj do garnka.',
      'Dodaj tofu i wakame, podgrzej minutę — gotowanie zabija aromat miso.',
      'Posyp dymką.',
    ],
  },
  {
    slug: 'with-mushroom-details',
    parent: 'miso-details',
    nazwa: 'Miso soup with mushroom',
    opis: 'Z grzybami shiitake, które wnoszą dodatkowe umami.',
    porcje: 4,
    czasMinut: 25,
    skladniki: ['800 ml dashi', '3 łyżki pasty miso', '150 g shiitake', '150 g tofu', 'dymka', 'sos sojowy'],
    kroki: [
      'Shiitake pokrój w plastry i podduś w dashi przez 5 minut.',
      'Zdejmij z ognia i rozprowadź pastę miso.',
      'Dodaj tofu i łyżkę sosu sojowego.',
      'Podawaj od razu, posypane dymką.',
    ],
  },
  {
    slug: 'with-vegetables-details',
    parent: 'miso-details',
    nazwa: 'Miso soup with vegetables',
    opis: 'Sycąca wersja z marchewką, rzodkwią daikon i kapustą.',
    porcje: 4,
    czasMinut: 30,
    skladniki: ['800 ml dashi', '3 łyżki miso', '1 marchewka', '150 g daikonu', '150 g kapusty pekińskiej', 'tofu', 'dymka'],
    kroki: [
      'Warzywa pokrój w cienkie plastry i gotuj w dashi 10 minut.',
      'Zdejmij z ognia, rozprowadź miso.',
      'Dodaj tofu i podgrzej bez gotowania.',
      'Posyp dymką.',
    ],
  },
  {
    slug: 'with-clams-details',
    parent: 'miso-details',
    nazwa: 'Miso soup with clams',
    opis: 'Z małżami asari — bulion powstaje w dużej mierze z ich soku.',
    porcje: 4,
    czasMinut: 30,
    skladniki: ['600 g małży', '800 ml wody', '3 łyżki miso', 'kawałek kombu', 'sake', 'dymka'],
    kroki: [
      'Małże wypłucz i odstaw w słonej wodzie na 30 minut, żeby pozbyły się piasku.',
      'Zagotuj wodę z kombu, wyjmij kombu przed wrzeniem.',
      'Wrzuć małże z odrobiną sake i gotuj, aż się otworzą.',
      'Zdejmij z ognia i rozprowadź miso.',
    ],
  },
  {
    slug: 'spicy-details',
    parent: 'miso-details',
    nazwa: 'Spicy miso soup',
    opis: 'Ostra wersja z pastą gochujang i olejem chili.',
    porcje: 4,
    czasMinut: 25,
    skladniki: ['800 ml dashi', '2 łyżki miso', '1 łyżka gochujang', 'olej chili', '200 g tofu', 'kiełki fasoli', 'dymka', 'czosnek'],
    kroki: [
      'Podgrzej dashi z czosnkiem.',
      'Rozprowadź miso razem z gochujang w chochli bulionu.',
      'Dodaj tofu i kiełki, podgrzej minutę.',
      'Skrop olejem chili i posyp dymką.',
    ],
  },

  // ---------- muesli-details ----------
  {
    slug: 'classic-details',
    parent: 'muesli-details',
    nazwa: 'Classic muesli',
    opis: 'Płatki owsiane z orzechami i suszonymi owocami, zalane mlekiem lub jogurtem.',
    porcje: 2,
    czasMinut: 5,
    skladniki: ['100 g płatków owsianych', '30 g rodzynek', '30 g orzechów laskowych', '20 g pestek słonecznika', '300 ml mleka', 'miód', 'świeże owoce'],
    kroki: [
      'Wymieszaj płatki z orzechami, pestkami i suszonymi owocami.',
      'Zalej mlekiem lub jogurtem.',
      'Odstaw na 5 minut, żeby płatki zmiękły.',
      'Dodaj świeże owoce i miód.',
    ],
  },
  {
    slug: 'bircher-details',
    parent: 'muesli-details',
    nazwa: 'Bircher muesli',
    opis: 'Szwajcarskie müsli namaczane przez noc, ze startym jabłkiem i śmietanką.',
    porcje: 2,
    czasMinut: 480,
    skladniki: ['100 g płatków owsianych', '200 ml mleka', '100 g jogurtu', '2 jabłka', 'sok z cytryny', '30 g orzechów', 'miód'],
    kroki: [
      'Płatki zalej mlekiem i wstaw do lodówki na noc.',
      'Rano zetrzyj jabłka i skrop sokiem z cytryny.',
      'Wymieszaj z namoczonymi płatkami i jogurtem.',
      'Dodaj orzechy i miód tuż przed podaniem.',
    ],
  },
  {
    slug: 'nutty-details',
    parent: 'muesli-details',
    nazwa: 'Nutty muesli',
    opis: 'Z podwójną porcją prażonych orzechów i masłem orzechowym.',
    porcje: 2,
    czasMinut: 15,
    skladniki: ['100 g płatków owsianych', '40 g migdałów', '40 g orzechów włoskich', '30 g nerkowców', '2 łyżki masła orzechowego', '300 ml mleka', 'miód'],
    kroki: [
      'Orzechy upraż na suchej patelni 5 minut — to wyciąga z nich olejki.',
      'Wymieszaj z płatkami.',
      'Masło orzechowe rozprowadź w ciepłym mleku.',
      'Zalej müsli i odstaw na 5 minut.',
    ],
  },
  {
    slug: 'berry-details',
    parent: 'muesli-details',
    nazwa: 'Berry muesli',
    opis: 'Z owocami leśnymi i jogurtem greckim.',
    porcje: 2,
    czasMinut: 10,
    skladniki: ['100 g płatków owsianych', '200 g owoców leśnych', '250 g jogurtu greckiego', '30 g nasion chia', 'miód', 'mięta'],
    kroki: [
      'Wymieszaj płatki z nasionami chia i jogurtem.',
      'Odstaw na 10 minut, żeby chia napęczniała.',
      'Dodaj owoce i miód.',
      'Udekoruj listkami mięty.',
    ],
  },
  {
    slug: 'chocolate-details',
    parent: 'muesli-details',
    nazwa: 'Chocolate muesli',
    opis: 'Z kakao, wiórkami czekolady i bananem.',
    porcje: 2,
    czasMinut: 10,
    skladniki: ['100 g płatków owsianych', '2 łyżki kakao', '40 g gorzkiej czekolady', '2 banany', '300 ml mleka', 'miód', 'orzechy'],
    kroki: [
      'Kakao rozprowadź w odrobinie ciepłego mleka, żeby nie zrobiło grudek.',
      'Wymieszaj z resztą mleka i zalej płatki.',
      'Dodaj plastry banana i posiekaną czekoladę.',
      'Posyp orzechami.',
    ],
  },

  // ---------- mushroom-soup-details ----------
  {
    slug: 'cream-of-mushroom-soup-details',
    parent: 'mushroom-soup-details',
    nazwa: 'Cream of mushroom soup',
    opis: 'Gładka zupa krem z pieczarek ze śmietaną i tymiankiem.',
    porcje: 4,
    czasMinut: 45,
    skladniki: ['600 g pieczarek', '1 cebula', '1 l bulionu', '200 ml śmietany 30%', '40 g masła', 'tymianek', 'sól, pieprz'],
    kroki: [
      'Zostaw kilka pieczarek na dekorację, resztę pokrój.',
      'Smaż na maśle na dużym ogniu, aż mocno się zarumienią.',
      'Dodaj cebulę, wlej bulion i gotuj 20 minut.',
      'Zblenduj na gładko, wlej śmietanę i podgrzej bez gotowania.',
    ],
  },
  {
    slug: 'wild-mushroom-soup-details',
    parent: 'mushroom-soup-details',
    nazwa: 'Wild mushroom soup',
    opis: 'Zupa z grzybów leśnych — borowików i podgrzybków, świeżych lub suszonych.',
    porcje: 4,
    czasMinut: 60,
    skladniki: ['400 g grzybów leśnych', '30 g suszonych borowików', '1 l bulionu', '1 cebula', '200 ml śmietany', 'natka pietruszki', 'masło'],
    kroki: [
      'Suszone grzyby namocz w gorącej wodzie na 30 minut, wodę zachowaj.',
      'Świeże grzyby podsmaż na maśle z cebulą.',
      'Wlej bulion i wodę z namaczania, gotuj 25 minut.',
      'Zblenduj częściowo — kawałki grzybów powinny zostać.',
      'Wmieszaj śmietanę i natkę.',
    ],
  },
  {
    slug: 'barley-mushroom-soup-details',
    parent: 'mushroom-soup-details',
    nazwa: 'Barley mushroom soup',
    opis: 'Krupnik z kaszą jęczmienną i grzybami — sycący, jednogarnkowy.',
    porcje: 6,
    czasMinut: 70,
    skladniki: ['150 g kaszy jęczmiennej', '400 g pieczarek', '30 g suszonych grzybów', '1,5 l bulionu', '2 marchewki', '1 pietruszka', 'ziemniaki', 'koperek'],
    kroki: [
      'Suszone grzyby namocz i ugotuj razem z kaszą.',
      'Warzywa pokrój w kostkę i dodaj do garnka.',
      'Pieczarki podsmaż osobno i dorzuć po 20 minutach.',
      'Gotuj łącznie 45 minut, dopraw i posyp koperkiem.',
    ],
  },
  {
    slug: 'miso-mushroom-soup-details',
    parent: 'mushroom-soup-details',
    nazwa: 'Miso mushroom soup',
    opis: 'Japońskie połączenie: grzyby shiitake i enoki w bulionie z pastą miso.',
    porcje: 4,
    czasMinut: 30,
    skladniki: ['800 ml dashi', '150 g shiitake', '100 g enoki', '3 łyżki miso', '150 g tofu', 'dymka', 'olej sezamowy'],
    kroki: [
      'Shiitake podduś w dashi przez 6 minut.',
      'Dodaj enoki i tofu.',
      'Zdejmij z ognia i rozprowadź miso.',
      'Skrop olejem sezamowym i posyp dymką.',
    ],
  },
  {
    slug: 'creamy-with-potato-mushroom-soup-details',
    parent: 'mushroom-soup-details',
    nazwa: 'Creamy mushroom soup with potato',
    opis: 'Zagęszczana ziemniakiem zamiast mąki — naturalnie kremowa.',
    porcje: 4,
    czasMinut: 50,
    skladniki: ['500 g pieczarek', '400 g ziemniaków', '1 l bulionu', '1 cebula', '150 ml śmietany', 'czosnek', 'tymianek', 'masło'],
    kroki: [
      'Pieczarki podsmaż na maśle do zarumienienia.',
      'Dodaj cebulę, czosnek i pokrojone ziemniaki.',
      'Wlej bulion i gotuj 25 minut, aż ziemniaki się rozpadną.',
      'Zblenduj — ziemniak zagęści zupę bez mąki.',
      'Wmieszaj śmietanę i tymianek.',
    ],
  },

  // ---------- oatmeal-details ----------
  {
    slug: 'classic-details',
    parent: 'oatmeal-details',
    nazwa: 'Classic oatmeal',
    opis: 'Owsianka gotowana na mleku, gładka i kremowa.',
    porcje: 2,
    czasMinut: 15,
    skladniki: ['100 g płatków owsianych górskich', '400 ml mleka', 'szczypta soli', '1 łyżka masła', 'miód', 'cynamon'],
    kroki: [
      'Zalej płatki mlekiem i dodaj szczyptę soli — bez niej owsianka jest mdła.',
      'Gotuj na małym ogniu 10 minut, mieszając.',
      'Zdejmij z ognia i wmieszaj masło.',
      'Podawaj z miodem i cynamonem.',
    ],
  },
  {
    slug: 'apple-cinnamon-details',
    parent: 'oatmeal-details',
    nazwa: 'Apple cinnamon oatmeal',
    opis: 'Owsianka z duszonym jabłkiem i cynamonem.',
    porcje: 2,
    czasMinut: 20,
    skladniki: ['100 g płatków owsianych', '400 ml mleka', '2 jabłka', '1 łyżeczka cynamonu', '2 łyżki masła', 'brązowy cukier', 'orzechy włoskie'],
    kroki: [
      'Jabłka pokrój w kostkę i duś na maśle z cukrem i cynamonem 8 minut.',
      'Osobno ugotuj owsiankę na mleku.',
      'Połącz, zostawiając część jabłek na wierzch.',
      'Posyp orzechami.',
    ],
  },
  {
    slug: 'banana-nut-details',
    parent: 'oatmeal-details',
    nazwa: 'Banana nut oatmeal',
    opis: 'Z bananem wgniecionym w gotującą się owsiankę — słodzi bez cukru.',
    porcje: 2,
    czasMinut: 15,
    skladniki: ['100 g płatków owsianych', '400 ml mleka', '2 banany', '40 g orzechów włoskich', 'masło orzechowe', 'cynamon', 'szczypta soli'],
    kroki: [
      'Jednego banana rozgnieć i dodaj do mleka na początku gotowania.',
      'Gotuj płatki 10 minut.',
      'Wmieszaj łyżkę masła orzechowego.',
      'Na wierzch połóż plastry drugiego banana i orzechy.',
    ],
  },
  {
    slug: 'berry-blast-details',
    parent: 'oatmeal-details',
    nazwa: 'Berry blast oatmeal',
    opis: 'Owsianka z rozgotowanymi owocami leśnymi, na fioletowo.',
    porcje: 2,
    czasMinut: 18,
    skladniki: ['100 g płatków owsianych', '400 ml mleka', '200 g mrożonych owoców leśnych', 'miód', 'nasiona chia', 'jogurt'],
    kroki: [
      'Połowę owoców dodaj do mleka i gotuj razem z płatkami.',
      'Po 10 minutach zdejmij z ognia.',
      'Wmieszaj nasiona chia i odstaw na 3 minuty.',
      'Na wierzch dodaj resztę owoców, jogurt i miód.',
    ],
  },
  {
    slug: 'pumpkin-spice-details',
    parent: 'oatmeal-details',
    nazwa: 'Pumpkin spice oatmeal',
    opis: 'Jesienna owsianka z purée z dyni i mieszanką korzennych przypraw.',
    porcje: 2,
    czasMinut: 20,
    skladniki: ['100 g płatków owsianych', '400 ml mleka', '200 g purée z dyni', 'cynamon', 'imbir mielony', 'gałka muszkatołowa', 'syrop klonowy', 'pestki dyni'],
    kroki: [
      'Ugotuj płatki na mleku przez 8 minut.',
      'Wmieszaj purée z dyni i przyprawy.',
      'Gotuj jeszcze 3 minuty, aż zgęstnieje.',
      'Polej syropem klonowym i posyp prażonymi pestkami dyni.',
    ],
  },

  // ---------- okonomiyaki-details ----------
  {
    slug: 'classic-details',
    parent: 'okonomiyaki-details',
    nazwa: 'Classic okonomiyaki',
    opis: 'Japoński placek z kapusty w cieście, z sosem okonomiyaki i płatkami bonito.',
    porcje: 2,
    czasMinut: 40,
    skladniki: ['300 g kapusty białej', '150 g mąki', '120 ml dashi', '2 jajka', '100 g boczku w plastrach', 'sos okonomiyaki', 'majonez japoński', 'płatki bonito', 'aonori'],
    kroki: [
      'Kapustę posiekaj bardzo drobno — to podstawa struktury placka.',
      'Wymieszaj mąkę z dashi i jajkami, dodaj kapustę.',
      'Wylej na patelnię, na wierzch połóż plastry boczku.',
      'Smaż 6 minut, obróć i smaż kolejne 6 pod przykryciem.',
      'Posmaruj sosem i majonezem, posyp bonito i aonori.',
    ],
  },
  {
    slug: 'hiroshima-details',
    parent: 'okonomiyaki-details',
    nazwa: 'Hiroshima okonomiyaki',
    opis: 'Wersja warstwowa z makaronem yakisoba i jajkiem sadzonym na spodzie.',
    porcje: 2,
    czasMinut: 50,
    skladniki: ['200 g kapusty', '100 g mąki', '100 ml wody', '200 g makaronu yakisoba', '2 jajka', 'boczek', 'kiełki fasoli', 'sos okonomiyaki'],
    kroki: [
      'Usmaż cienki naleśnik z ciasta, na nim ułóż górę kapusty i kiełków.',
      'Dołóż boczek i przykryj na 5 minut, aż kapusta osiądzie.',
      'Osobno podsmaż makaron i ułóż go obok.',
      'Przełóż placek na makaron, na patelni usmaż jajko i przełóż na nie całość.',
      'Posmaruj sosem.',
    ],
  },
  {
    slug: 'seafood-details',
    parent: 'okonomiyaki-details',
    nazwa: 'Seafood okonomiyaki',
    opis: 'Z krewetkami i kalmarami zamiast boczku.',
    porcje: 2,
    czasMinut: 40,
    skladniki: ['300 g kapusty', '150 g mąki', '120 ml dashi', '2 jajka', '150 g krewetek', '100 g kalmarów', 'sos okonomiyaki', 'majonez', 'dymka'],
    kroki: [
      'Owoce morza pokrój na małe kawałki i wmieszaj w ciasto z kapustą.',
      'Smaż placek 6 minut z każdej strony.',
      'Nie dociskaj łopatką — placek ma zostać puszysty.',
      'Wykończ sosem, majonezem i dymką.',
    ],
  },
  {
    slug: 'vegetarian-details',
    parent: 'okonomiyaki-details',
    nazwa: 'Vegetarian okonomiyaki',
    opis: 'Bezmięsna wersja z marchewką, dymką i grzybami shiitake.',
    porcje: 2,
    czasMinut: 40,
    skladniki: ['300 g kapusty', '1 marchewka', '100 g shiitake', '150 g mąki', '120 ml bulionu warzywnego', '2 jajka', 'sos okonomiyaki', 'majonez'],
    kroki: [
      'Kapustę i marchewkę posiekaj drobno, grzyby pokrój w plastry.',
      'Wymieszaj z ciastem z mąki, bulionu i jajek.',
      'Smaż po 6 minut z każdej strony.',
      'Wykończ sosem i majonezem.',
    ],
  },
  {
    slug: 'modern-fusion-details',
    parent: 'okonomiyaki-details',
    nazwa: 'Modern fusion okonomiyaki',
    opis: 'Wersja z serem, kimchi i sosem sriracha — poza kanonem, ale działa.',
    porcje: 2,
    czasMinut: 40,
    skladniki: ['300 g kapusty', '150 g kimchi', '100 g sera cheddar', '150 g mąki', '120 ml dashi', '2 jajka', 'sriracha', 'majonez', 'dymka'],
    kroki: [
      'Kimchi odciśnij i posiekaj, wmieszaj w ciasto z kapustą.',
      'Wylej na patelnię, posyp serem i przykryj.',
      'Smaż 6 minut, obróć i dosmaż kolejne 5.',
      'Wykończ majonezem, sriracha i dymką.',
    ],
  },

  // ---------- omelette-details ----------
  {
    slug: 'frittata-details',
    parent: 'omelette-details',
    nazwa: 'Frittata',
    opis: 'Włoski omlet zapiekany w piekarniku, z warzywami i serem.',
    porcje: 4,
    czasMinut: 35,
    skladniki: ['8 jajek', '1 cukinia', '1 papryka', '1 cebula', '100 g parmezanu', '50 ml śmietanki', 'oliwa', 'bazylia'],
    kroki: [
      'Warzywa podsmaż na patelni żaroodpornej przez 8 minut.',
      'Jajka roztrzep ze śmietanką i parmezanem.',
      'Wlej na warzywa i smaż 3 minuty, aż brzegi się zetną.',
      'Wstaw patelnię do piekarnika i piecz 12 minut w 180°C.',
    ],
  },
  {
    slug: 'eggs-benedict-details',
    parent: 'omelette-details',
    nazwa: 'Eggs Benedict',
    opis: 'Jajka w koszulkach na bekonie i muffince, pod sosem holenderskim.',
    porcje: 2,
    czasMinut: 35,
    skladniki: ['4 jajka', '4 plastry bekonu', '2 muffinki angielskie', '3 żółtka', '150 g masła klarowanego', 'sok z cytryny', 'szczypiorek'],
    kroki: [
      'Ubij żółtka nad parą, powoli dodając masło klarowane — sos ma zgęstnieć, nie zwarzyć się.',
      'Bekon usmaż na chrupko.',
      'Jajka gotuj w koszulkach 3 minuty w wodzie z octem.',
      'Złóż: muffinka, bekon, jajko, sos; posyp szczypiorkiem.',
    ],
  },
  {
    slug: 'spanish-details',
    parent: 'omelette-details',
    nazwa: 'Spanish omelette',
    opis: 'Tortilla española — gruby omlet z ziemniakami i cebulą.',
    porcje: 4,
    czasMinut: 45,
    skladniki: ['6 jajek', '600 g ziemniaków', '1 cebula', '200 ml oliwy', 'sól'],
    kroki: [
      'Ziemniaki pokrój w cienkie plastry i gotuj w oliwie na małym ogniu 20 minut — mają zmięknąć, nie zbrązowieć.',
      'Odsącz z oliwy i wymieszaj z roztrzepanymi jajkami; odstaw na 10 minut.',
      'Wylej na patelnię i smaż 5 minut na średnim ogniu.',
      'Odwróć na talerzu i wsuń z powrotem, dosmaż 4 minuty. Środek ma zostać wilgotny.',
    ],
  },
  {
    slug: 'mushroom-details',
    parent: 'omelette-details',
    nazwa: 'Mushroom omelette',
    opis: 'Francuski omlet z pieczarkami — puszysty, złożony na trzy.',
    porcje: 1,
    czasMinut: 15,
    skladniki: ['3 jajka', '100 g pieczarek', '20 g masła', '30 g sera gruyère', 'szczypiorek', 'sól, pieprz'],
    kroki: [
      'Pieczarki podsmaż na maśle i odłóż.',
      'Jajka roztrzep widelcem, ale nie ubijaj na pianę.',
      'Wylej na patelnię i mieszaj widelcem przez 30 sekund, potem zostaw.',
      'Nałóż grzyby i ser, złóż omlet na trzy i zsuń na talerz.',
      'Wierzch powinien pozostać lekko wilgotny — to francuski standard.',
    ],
  },

  // ---------- osso-buco-details ----------
  {
    slug: 'osso-buco-with-vegetables-details',
    parent: 'osso-buco-details',
    nazwa: 'Osso buco with vegetables',
    opis: 'Cielęca gicz duszona z warzywami i białym winem, z gremolatą na wierzchu.',
    porcje: 4,
    czasMinut: 180,
    skladniki: ['4 plastry giczy cielęcej', '2 marchewki', '2 łodygi selera', '1 cebula', '250 ml białego wina', '400 g pomidorów', 'bulion', 'skórka z cytryny, czosnek, natka'],
    kroki: [
      'Plastry giczy natnij po obwodzie, żeby się nie zwinęły; oprósz mąką i obsmaż.',
      'Podsmaż warzywa, wlej wino i odparuj.',
      'Dodaj pomidory i bulion do wysokości mięsa.',
      'Duś pod przykryciem 2 godziny w 160°C.',
      'Gremolata: posiekana natka, czosnek i skórka z cytryny — posyp tuż przed podaniem.',
    ],
  },
  {
    slug: 'osso-buco-with-potatoes-details',
    parent: 'osso-buco-details',
    nazwa: 'Osso buco with potatoes',
    opis: 'Wersja jednogarnkowa — ziemniaki dochodzą razem z mięsem.',
    porcje: 4,
    czasMinut: 190,
    skladniki: ['4 plastry giczy cielęcej', '800 g ziemniaków', '1 cebula', '250 ml białego wina', 'bulion', 'rozmaryn', 'czosnek', 'mąka'],
    kroki: [
      'Mięso oprósz mąką i obsmaż na złoto.',
      'Podsmaż cebulę i czosnek, wlej wino.',
      'Duś mięso 90 minut.',
      'Dodaj ziemniaki w dużych kawałkach i duś kolejne 40 minut.',
    ],
  },
  {
    slug: 'osso-buco-with-rice-details',
    parent: 'osso-buco-details',
    nazwa: 'Osso buco with rice',
    opis: 'Podawane po mediolańsku, z risottem szafranowym.',
    porcje: 4,
    czasMinut: 180,
    skladniki: ['4 plastry giczy cielęcej', '300 g ryżu arborio', 'szafran', '1 l bulionu', '250 ml białego wina', 'parmezan', 'masło', 'cebula'],
    kroki: [
      'Duś osso buco przez 2 godziny w winie i bulionie.',
      'Osobno przygotuj risotto: praż ryż, dolewaj bulion partiami.',
      'Szafran namocz w łyżce bulionu i dodaj w połowie gotowania.',
      'Wykończ risotto masłem i parmezanem, podaj z mięsem i sosem.',
    ],
  },
  {
    slug: 'osso-buco-with-buckwheat-details',
    parent: 'osso-buco-details',
    nazwa: 'Osso buco with buckwheat',
    opis: 'Nietypowe połączenie z kaszą gryczaną zamiast risotta.',
    porcje: 4,
    czasMinut: 175,
    skladniki: ['4 plastry giczy cielęcej', '300 g kaszy gryczanej', '250 ml czerwonego wina', 'bulion', 'cebula', 'marchewka', 'majeranek', 'masło'],
    kroki: [
      'Mięso obsmaż i duś w winie z warzywami przez 2 godziny.',
      'Kaszę upraż na sucho, potem zalej wrzątkiem w proporcji 1:2.',
      'Gotuj 15 minut pod przykryciem i odstaw na 10.',
      'Podawaj mięso na kaszy, polane sosem z duszenia.',
    ],
  },
  {
    slug: 'osso-buco-with-mashed-potatoes-details',
    parent: 'osso-buco-details',
    nazwa: 'Osso buco with mashed potatoes',
    opis: 'Z gładkim purée ziemniaczanym, które chłonie sos.',
    porcje: 4,
    czasMinut: 185,
    skladniki: ['4 plastry giczy cielęcej', '1 kg ziemniaków', '150 ml mleka', '80 g masła', '250 ml białego wina', 'bulion', 'włoszczyzna'],
    kroki: [
      'Duś mięso z warzywami i winem przez 2 godziny.',
      'Ziemniaki ugotuj i przeciśnij przez praskę — blender zrobi z nich klej.',
      'Wmieszaj gorące mleko i masło.',
      'Podawaj mięso na purée, obficie polane sosem.',
    ],
  },

  // ---------- pad-thai-details ----------
  {
    slug: 'classic-pad-thai-details',
    parent: 'pad-thai-details',
    nazwa: 'Classic pad thai',
    opis: 'Tajski makaron ryżowy smażony w sosie z tamaryndowca, z krewetkami i jajkiem.',
    porcje: 4,
    czasMinut: 40,
    skladniki: ['300 g makaronu ryżowego', '250 g krewetek', '2 jajka', '3 łyżki pasty tamaryndowej', '3 łyżki sosu rybnego', '2 łyżki cukru palmowego', 'kiełki fasoli', 'orzeszki ziemne', 'limonka'],
    kroki: [
      'Makaron namocz w ciepłej wodzie 30 minut — nie gotuj.',
      'Sos: tamaryndowiec, sos rybny i cukier palmowy rozpuść razem.',
      'Na woku usmaż krewetki, odsuń na bok, wbij jajka i wymieszaj.',
      'Dodaj makaron i sos, smaż 3 minuty na dużym ogniu.',
      'Wrzuć kiełki, posyp orzeszkami, podaj z ćwiartką limonki.',
    ],
  },
  {
    slug: 'vegetarian-pad-thai-details',
    parent: 'pad-thai-details',
    nazwa: 'Vegetarian pad thai',
    opis: 'Bez sosu rybnego — z sosem sojowym i tofu.',
    porcje: 4,
    czasMinut: 40,
    skladniki: ['300 g makaronu ryżowego', '250 g tofu', '2 jajka', 'pasta tamaryndowa', '3 łyżki sosu sojowego', 'cukier palmowy', 'kiełki', 'orzeszki', 'dymka'],
    kroki: [
      'Tofu odciśnij, pokrój w kostkę i podsmaż do zarumienienia.',
      'Makaron namocz w ciepłej wodzie.',
      'Sos przygotuj na sosie sojowym zamiast rybnego.',
      'Smaż wszystko razem na woku 3 minuty i wykończ orzeszkami.',
    ],
  },
  {
    slug: 'seafood-pad-thai-details',
    parent: 'pad-thai-details',
    nazwa: 'Seafood pad thai',
    opis: 'Z krewetkami, kalmarami i małżami.',
    porcje: 4,
    czasMinut: 45,
    skladniki: ['300 g makaronu ryżowego', '200 g krewetek', '150 g kalmarów', '200 g małży', 'pasta tamaryndowa', 'sos rybny', 'cukier palmowy', 'kiełki', 'limonka'],
    kroki: [
      'Małże otwórz osobno na parze i wyjmij z muszli.',
      'Krewetki i kalmary usmaż na woku 2 minuty.',
      'Dodaj namoczony makaron i sos, smaż 3 minuty.',
      'Na koniec wrzuć małże i kiełki.',
    ],
  },
  {
    slug: 'chicken-pad-thai-details',
    parent: 'pad-thai-details',
    nazwa: 'Chicken pad thai',
    opis: 'Z kurczakiem — najczęściej zamawiana wersja poza Tajlandią.',
    porcje: 4,
    czasMinut: 40,
    skladniki: ['300 g makaronu ryżowego', '400 g piersi z kurczaka', '2 jajka', 'pasta tamaryndowa', 'sos rybny', 'cukier palmowy', 'kiełki', 'orzeszki', 'chili'],
    kroki: [
      'Kurczaka pokrój w paski i usmaż na woku do zarumienienia.',
      'Odsuń na bok, wbij jajka i rozmieszaj.',
      'Dodaj makaron i sos, smaż na dużym ogniu 3 minuty.',
      'Wykończ kiełkami, orzeszkami i chili.',
    ],
  },
  {
    slug: 'tofu-pad-thai-details',
    parent: 'pad-thai-details',
    nazwa: 'Tofu pad thai',
    opis: 'Z chrupiącym tofu i podwójną porcją kiełków.',
    porcje: 4,
    czasMinut: 45,
    skladniki: ['300 g makaronu ryżowego', '300 g tofu twardego', 'skrobia', 'pasta tamaryndowa', 'sos sojowy', 'cukier palmowy', '200 g kiełków', 'orzeszki', 'szczypiorek'],
    kroki: [
      'Tofu odciśnij, obtocz w skrobi i usmaż na chrupko.',
      'Makaron namocz i odcedź.',
      'Smaż makaron z sosem 3 minuty.',
      'Dodaj tofu i kiełki na ostatnie 30 sekund, żeby zostały chrupiące.',
    ],
  },

  // ---------- paella-details ----------
  {
    slug: 'valencian-paella-details',
    parent: 'paella-details',
    nazwa: 'Valencian paella',
    opis: 'Oryginalna paella z Walencji: królik, kurczak i fasola, bez owoców morza.',
    porcje: 6,
    czasMinut: 75,
    skladniki: ['400 g ryżu bomba', '500 g królika', '500 g kurczaka', '200 g fasoli szparagowej', '150 g białej fasoli', 'szafran', 'papryka słodka', '1,2 l bulionu', 'oliwa'],
    kroki: [
      'Mięso obsmaż na patelni do paelli na oliwie, po 10 minut z każdej strony.',
      'Dodaj fasolę i paprykę, potem starte pomidory.',
      'Wsyp ryż i wymieszaj, żeby oblepił się tłuszczem.',
      'Wlej gorący bulion z szafranem i NIE mieszaj już do końca.',
      'Gotuj 18 minut, ostatnie 2 na dużym ogniu — na dnie ma powstać socarrat.',
    ],
  },
  {
    slug: 'seafood-paella-details',
    parent: 'paella-details',
    nazwa: 'Seafood paella',
    opis: 'Paella de marisco z krewetkami, małżami i kalmarami.',
    porcje: 6,
    czasMinut: 60,
    skladniki: ['400 g ryżu bomba', '300 g krewetek', '400 g małży', '200 g kalmarów', 'szafran', '1,2 l bulionu rybnego', 'papryka', 'czosnek', 'oliwa'],
    kroki: [
      'Krewetki podsmaż 1 minutę i wyjmij — wrócą na koniec.',
      'Podsmaż kalmary z czosnkiem i papryką.',
      'Wsyp ryż, wlej gorący bulion z szafranem.',
      'Gotuj 15 minut bez mieszania, dokładając małże.',
      'Ułóż krewetki na wierzchu i odstaw pod ściereczką na 5 minut.',
    ],
  },
  {
    slug: 'mixed-paella-details',
    parent: 'paella-details',
    nazwa: 'Mixed paella',
    opis: 'Paella mixta łącząca mięso i owoce morza — turystyczna, ale popularna.',
    porcje: 6,
    czasMinut: 70,
    skladniki: ['400 g ryżu bomba', '300 g kurczaka', '200 g chorizo', '250 g krewetek', '300 g małży', 'papryka', 'groszek', 'szafran', 'bulion'],
    kroki: [
      'Obsmaż kurczaka i chorizo — tłuszcz z kiełbasy zabarwi ryż.',
      'Dodaj paprykę i starte pomidory.',
      'Wsyp ryż, wlej bulion z szafranem.',
      'Po 10 minutach dołóż owoce morza i groszek.',
      'Dogotuj 8 minut i odstaw na 5 minut.',
    ],
  },
  {
    slug: 'vegetarian-paella-details',
    parent: 'paella-details',
    nazwa: 'Vegetarian paella',
    opis: 'Warzywna wersja z karczochami, papryką i fasolą.',
    porcje: 6,
    czasMinut: 55,
    skladniki: ['400 g ryżu bomba', '4 karczochy', '2 papryki', '200 g fasoli szparagowej', '150 g groszku', 'szafran', '1,2 l bulionu warzywnego', 'papryka wędzona'],
    kroki: [
      'Warzywa podsmaż na oliwie przez 10 minut.',
      'Dodaj paprykę wędzoną i starte pomidory.',
      'Wsyp ryż, wlej bulion z szafranem.',
      'Gotuj 18 minut bez mieszania i odstaw pod ściereczką.',
    ],
  },
  {
    slug: 'black-paella-details',
    parent: 'paella-details',
    nazwa: 'Black paella',
    opis: 'Arròs negre — ryż barwiony atramentem z kalmarów, podawany z aioli.',
    porcje: 6,
    czasMinut: 60,
    skladniki: ['400 g ryżu bomba', '400 g kalmarów', '4 saszetki atramentu', '250 g krewetek', '1,2 l bulionu rybnego', 'czosnek', 'papryka', 'aioli'],
    kroki: [
      'Kalmary pokrój w pierścienie i podsmaż z czosnkiem.',
      'Rozpuść atrament w gorącym bulionie.',
      'Wsyp ryż, wymieszaj, wlej czarny bulion.',
      'Gotuj 18 minut bez mieszania.',
      'Podawaj z kleksem aioli — kontrast jest tu obowiązkowy.',
    ],
  },
];
