import { Przepis } from '../przepis.model';

/** Ryż z jajkiem, risotta, kanapki, sashimi, jajecznice, szakszuka,
 *  krewetki, kluski śląskie, żurki, spaghetti, sushi, słodkie naleśniki. */
export const PACZKA_5: Przepis[] = [
  // ---------- rice-with-egg-details ----------
  {
    slug: 'tamago-gohan-details',
    parent: 'rice-with-egg-details',
    nazwa: 'Tamago gohan',
    opis: 'Japońskie śniadanie: surowe jajko wbite w gorący ryż i wymieszane na krem.',
    porcje: 1,
    czasMinut: 10,
    skladniki: ['1 miska gorącego ryżu', '1 bardzo świeże jajko', '1 łyżeczka sosu sojowego', 'dymka', 'nori'],
    kroki: [
      'Ryż musi być świeżo ugotowany i parujący — to on ścina jajko.',
      'Wbij jajko na wierzch i wlej sos sojowy.',
      'Mieszaj energicznie pałeczkami, aż powstanie jednolity, kremowy ryż.',
      'Posyp dymką i nori.',
    ],
  },
  {
    slug: 'oyakodon-details',
    parent: 'rice-with-egg-details',
    nazwa: 'Oyakodon',
    opis: 'Kurczak duszony z cebulą i jajkiem, podany na ryżu.',
    porcje: 2,
    czasMinut: 25,
    skladniki: ['300 g udek z kurczaka', '3 jajka', '1 cebula', '200 ml dashi', '3 łyżki sosu sojowego', '2 łyżki mirin', 'ryż', 'dymka'],
    kroki: [
      'Zagotuj dashi z sosem sojowym i mirin.',
      'Dodaj cebulę i kurczaka, gotuj 7 minut.',
      'Wlej roztrzepane jajka po obwodzie patelni.',
      'Przykryj na minutę — jajko ma zostać ledwo ścięte.',
      'Zsuń na ryż i posyp dymką.',
    ],
  },
  {
    slug: 'omurice-details',
    parent: 'rice-with-egg-details',
    nazwa: 'Omurice',
    opis: 'Ryż smażony z ketchupem, zawinięty w cienki omlet.',
    porcje: 2,
    czasMinut: 30,
    skladniki: ['400 g ugotowanego ryżu', '200 g kurczaka', '1 cebula', '4 łyżki ketchupu', '4 jajka', 'masło', 'groszek', 'sól'],
    kroki: [
      'Podsmaż kurczaka z cebulą, dodaj ryż i ketchup, smaż 5 minut.',
      'Uformuj z ryżu owalny kopiec na talerzu.',
      'Usmaż cienki omlet z dwóch jajek, nie rumieniąc go.',
      'Przykryj nim ryż i podetknij brzegi pod spód.',
      'Ozdób ketchupem.',
    ],
  },
  {
    slug: 'fried-rice-details',
    parent: 'rice-with-egg-details',
    nazwa: 'Egg fried rice',
    opis: 'Smażony ryż z jajkiem — najlepszy z ryżu z poprzedniego dnia.',
    porcje: 2,
    czasMinut: 20,
    skladniki: ['400 g zimnego ryżu', '3 jajka', '2 dymki', '100 g groszku', '2 łyżki sosu sojowego', 'olej', 'biały pieprz'],
    kroki: [
      'Użyj ryżu z lodówki — świeży skleja się w papkę.',
      'Rozgrzej wok do dymu i wlej olej.',
      'Wbij jajka, rozmieszaj i od razu dodaj ryż.',
      'Smaż 3 minuty, rozbijając grudki, dopraw sosem sojowym.',
      'Na koniec wrzuć groszek i dymkę.',
    ],
  },

  // ---------- risotto-details ----------
  {
    slug: 'rissoto-alla-milanese-details',
    parent: 'risotto-details',
    nazwa: 'Risotto alla milanese',
    opis: 'Złote risotto z szafranem i szpikiem kostnym — klasyk z Mediolanu.',
    porcje: 4,
    czasMinut: 40,
    skladniki: ['320 g ryżu carnaroli', '1 g szafranu', '1,2 l bulionu wołowego', '1 cebula', '100 ml białego wina', '80 g parmezanu', '80 g masła', 'szpik kostny'],
    kroki: [
      'Zeszklij cebulę na maśle ze szpikiem.',
      'Wsyp ryż i praż 2 minuty, aż ziarna staną się przezroczyste na brzegach.',
      'Wlej wino i odparuj.',
      'Dolewaj gorący bulion chochlą, mieszając, przez 18 minut.',
      'Szafran namoczony w bulionie dodaj na 5 minut przed końcem; zdejmij z ognia i wmieszaj masło z parmezanem.',
    ],
  },
  {
    slug: 'rissoto-ai-funghi-details',
    parent: 'risotto-details',
    nazwa: 'Risotto ai funghi',
    opis: 'Risotto grzybowe z borowikami — świeżymi i suszonymi naraz.',
    porcje: 4,
    czasMinut: 45,
    skladniki: ['320 g ryżu carnaroli', '300 g borowików', '30 g suszonych grzybów', '1,2 l bulionu', '100 ml białego wina', 'parmezan', 'masło', 'natka'],
    kroki: [
      'Suszone grzyby namocz, wodę dodaj do bulionu.',
      'Świeże grzyby podsmaż osobno i odłóż.',
      'Przygotuj risotto, dolewając bulion partiami.',
      'Grzyby wróć na ostatnie 5 minut.',
      'Zdejmij z ognia i wykończ masłem oraz parmezanem.',
    ],
  },
  {
    slug: 'rissoto-al-frutti-di-mare-details',
    parent: 'risotto-details',
    nazwa: 'Risotto ai frutti di mare',
    opis: 'Risotto z owocami morza — bez sera, bo we Włoszech nie łączy się go z rybami.',
    porcje: 4,
    czasMinut: 45,
    skladniki: ['320 g ryżu', '300 g małży', '200 g krewetek', '150 g kalmarów', '1,2 l bulionu rybnego', '100 ml białego wina', 'czosnek', 'natka', 'oliwa'],
    kroki: [
      'Małże otwórz w winie, wyjmij z muszli, płyn przecedź do bulionu.',
      'Krewetki i kalmary podsmaż 2 minuty i odłóż.',
      'Ugotuj risotto na bulionie rybnym.',
      'Owoce morza wróć na ostatnią minutę.',
      'Wykończ oliwą i natką — parmezanu tu nie dodajemy.',
    ],
  },
  {
    slug: 'rissoto-ai-frutti-di-bosco-details',
    parent: 'risotto-details',
    nazwa: 'Risotto ai frutti di bosco',
    opis: 'Nietypowe risotto z owocami leśnymi i czerwonym winem, na słodko-wytrawnie.',
    porcje: 4,
    czasMinut: 40,
    skladniki: ['320 g ryżu', '250 g owoców leśnych', '150 ml czerwonego wina', '1,2 l bulionu warzywnego', 'ser taleggio', 'masło', 'cebula', 'tymianek'],
    kroki: [
      'Zeszklij cebulę i praż ryż.',
      'Wlej czerwone wino i odparuj — ono nada risottu kolor.',
      'Dolewaj bulion partiami przez 18 minut.',
      'Na 5 minut przed końcem dodaj owoce.',
      'Wykończ masłem i kawałkami taleggio.',
    ],
  },

  // ---------- sandwiches-details ----------
  {
    slug: 'club-details',
    parent: 'sandwiches-details',
    nazwa: 'Club sandwich',
    opis: 'Trzypiętrowa kanapka z kurczakiem, bekonem, sałatą i pomidorem.',
    porcje: 2,
    czasMinut: 25,
    skladniki: ['6 kromek chleba tostowego', '200 g grillowanego kurczaka', '4 plastry bekonu', 'sałata', '1 pomidor', 'majonez', 'masło'],
    kroki: [
      'Kromki opiecz w tosterze i posmaruj majonezem.',
      'Pierwsza warstwa: kurczak, sałata, pomidor.',
      'Druga warstwa: bekon i sałata.',
      'Przykryj trzecią kromką, spnij wykałaczkami i przekrój na trójkąty.',
    ],
  },
  {
    slug: 'blt-details',
    parent: 'sandwiches-details',
    nazwa: 'BLT',
    opis: 'Bacon, lettuce, tomato — trzy składniki i majonez.',
    porcje: 2,
    czasMinut: 15,
    skladniki: ['4 kromki chleba', '6 plastrów bekonu', 'sałata lodowa', '2 pomidory', 'majonez', 'pieprz'],
    kroki: [
      'Bekon wysmaż na bardzo chrupko.',
      'Kromki opiecz i posmaruj majonezem po obu stronach kanapki.',
      'Pomidory posól i odsącz przez chwilę na ręczniku.',
      'Złóż: bekon, pomidor, sałata; dopraw pieprzem.',
    ],
  },
  {
    slug: 'grilled-cheese-details',
    parent: 'sandwiches-details',
    nazwa: 'Grilled cheese',
    opis: 'Kanapka z serem smażona na maśle do złocistej skorupki.',
    porcje: 2,
    czasMinut: 15,
    skladniki: ['4 kromki chleba', '150 g cheddara', '150 g sera gruyère', '60 g masła', 'musztarda dijon'],
    kroki: [
      'Zetrzyj oba sery i wymieszaj — mieszanka topi się lepiej niż jeden rodzaj.',
      'Posmaruj zewnętrzne strony kromek masłem.',
      'Smaż na średnim ogniu 4 minuty z każdej strony pod przykryciem.',
      'Zbyt duży ogień przypali chleb, zanim ser się roztopi.',
    ],
  },
  {
    slug: 'reuben-details',
    parent: 'sandwiches-details',
    nazwa: 'Reuben',
    opis: 'Nowojorska kanapka z peklowaną wołowiną, kiszoną kapustą i sosem tysiąca wysp.',
    porcje: 2,
    czasMinut: 20,
    skladniki: ['4 kromki chleba żytniego', '200 g peklowanej wołowiny', '150 g kapusty kiszonej', '100 g sera szwajcarskiego', 'sos tysiąca wysp', 'masło'],
    kroki: [
      'Kapustę odciśnij dokładnie z zalewy.',
      'Posmaruj kromki sosem, ułóż ser, wołowinę i kapustę.',
      'Zewnętrzne strony posmaruj masłem.',
      'Smaż pod przykryciem po 4 minuty z każdej strony.',
    ],
  },
  {
    slug: 'philly-chesesteak-details',
    parent: 'sandwiches-details',
    nazwa: 'Philly cheesesteak',
    opis: 'Bułka z cienko krojoną wołowiną, cebulą i roztopionym serem.',
    porcje: 2,
    czasMinut: 30,
    skladniki: ['2 długie bułki', '400 g rostbefu', '2 cebule', '1 papryka', '150 g sera provolone', 'masło', 'sól, pieprz'],
    kroki: [
      'Mięso podmroź 30 minut — dzięki temu pokroisz je na papierowo cienkie plastry.',
      'Smaż cebulę i paprykę do zmiękczenia, odsuń na bok patelni.',
      'Wrzuć mięso i siekaj łopatką podczas smażenia przez 3 minuty.',
      'Wymieszaj z warzywami, połóż ser i przykryj na minutę.',
      'Przełóż do bułki jedną łopatką, zachowując warstwy.',
    ],
  },

  // ---------- sashimi-details ----------
  {
    slug: 'tuna-sashimi-details',
    parent: 'sashimi-details',
    nazwa: 'Tuna sashimi',
    opis: 'Plastry surowego tuńczyka w jakości sashimi, podawane z wasabi i sosem sojowym.',
    porcje: 2,
    czasMinut: 15,
    skladniki: ['300 g tuńczyka w jakości sashimi', 'wasabi', 'sos sojowy', 'daikon', 'shiso', 'marynowany imbir'],
    kroki: [
      'Nóż musi być bardzo ostry — tępy rozrywa włókna zamiast ciąć.',
      'Kroj w poprzek włókien, jednym pociągnięciem, na plastry 8 mm.',
      'Ułóż na startym daikonie i liściach shiso.',
      'Podawaj z wasabi i sosem sojowym osobno.',
    ],
  },
  {
    slug: 'salmon-sashimi-details',
    parent: 'sashimi-details',
    nazwa: 'Salmon sashimi',
    opis: 'Łosoś w jakości sashimi, tłustszy i łagodniejszy od tuńczyka.',
    porcje: 2,
    czasMinut: 15,
    skladniki: ['300 g łososia w jakości sashimi', 'wasabi', 'sos sojowy', 'dymka', 'cytryna', 'daikon'],
    kroki: [
      'Usuń wszystkie ości pęsetą.',
      'Kroj ukośnie, pod kątem 45 stopni, na szersze plastry.',
      'Ułóż wachlarzowo na startym daikonie.',
      'Podawaj z wasabi, dymką i ćwiartką cytryny.',
    ],
  },
  {
    slug: 'mackerel-sashimi-details',
    parent: 'sashimi-details',
    nazwa: 'Mackerel sashimi',
    opis: 'Makrela shime saba — wcześniej peklowana w soli i occie, bo psuje się bardzo szybko.',
    porcje: 2,
    czasMinut: 180,
    skladniki: ['2 filety z makreli', '100 g soli', '200 ml octu ryżowego', 'imbir', 'dymka', 'sos sojowy'],
    kroki: [
      'Filety obsyp grubo solą i odstaw na 2 godziny.',
      'Opłucz i zanurz w occie ryżowym na 30 minut.',
      'Zdejmij cienką błonkę ze skóry — schodzi wtedy sama.',
      'Pokrój w plastry i podawaj z imbirem i dymką.',
    ],
  },
  {
    slug: 'shrimp-sashimi-details',
    parent: 'sashimi-details',
    nazwa: 'Shrimp sashimi',
    opis: 'Ama ebi — surowe słodkie krewetki, podawane z głowami usmażonymi na chrupko.',
    porcje: 2,
    czasMinut: 20,
    skladniki: ['12 krewetek słodkowodnych w jakości sashimi', 'wasabi', 'sos sojowy', 'shiso', 'olej do smażenia'],
    kroki: [
      'Oddziel głowy i odłóż je.',
      'Obierz ogony, pozostawiając ostatni segment pancerza.',
      'Usuń jelito wzdłuż grzbietu.',
      'Głowy usmaż na chrupko i podaj obok surowych ogonów.',
    ],
  },
  {
    slug: 'duck-sashimi-details',
    parent: 'sashimi-details',
    nazwa: 'Duck sashimi',
    opis: 'Kaczka tataki — obsmażona z zewnątrz, surowa w środku, krojona w cienkie plastry.',
    porcje: 2,
    czasMinut: 30,
    skladniki: ['1 pierś z kaczki', 'sos sojowy', 'mirin', 'imbir', 'dymka', 'ponzu'],
    kroki: [
      'Skórę natnij w kratkę i smaż na zimnej patelni skórą do dołu 8 minut, aż wytopi się tłuszcz.',
      'Obróć i smaż 2 minuty — środek ma zostać różowy.',
      'Zanurz w lodowatej wodzie, żeby zatrzymać gotowanie.',
      'Schłodź, pokrój w cienkie plastry i podawaj z ponzu.',
    ],
  },

  // ---------- scrambled-eggs-details ----------
  {
    slug: 'classic-details',
    parent: 'scrambled-eggs-details',
    nazwa: 'Classic scrambled eggs',
    opis: 'Jajecznica na maśle, mieszana na małym ogniu do miękkich płatków.',
    porcje: 2,
    czasMinut: 10,
    skladniki: ['5 jajek', '30 g masła', 'sól', 'pieprz', 'szczypiorek'],
    kroki: [
      'Roztrzep jajka dopiero na patelni — nie wcześniej.',
      'Smaż na małym ogniu, mieszając łopatką bez przerwy.',
      'Zdejmij z ognia, gdy jajka są jeszcze wilgotne — dojdą z resztek ciepła.',
      'Posól na końcu; sól dodana wcześniej powoduje wyciek wody.',
    ],
  },
  {
    slug: 'creamy-details',
    parent: 'scrambled-eggs-details',
    nazwa: 'Creamy scrambled eggs',
    opis: 'Wersja francuska, gotowana bardzo powoli ze śmietanką — prawie jak krem.',
    porcje: 2,
    czasMinut: 20,
    skladniki: ['5 jajek', '40 g masła', '2 łyżki śmietanki 30%', 'sól', 'szczypiorek'],
    kroki: [
      'Jajka mieszaj na patelni na bardzo małym ogniu przez 15 minut.',
      'Zdejmuj patelnię z ognia co 30 sekund, żeby temperatura nie skoczyła.',
      'Na końcu wmieszaj zimną śmietankę — zatrzymuje gotowanie.',
      'Podawaj natychmiast, konsystencja psuje się w minutę.',
    ],
  },
  {
    slug: 'cheesy-details',
    parent: 'scrambled-eggs-details',
    nazwa: 'Cheesy scrambled eggs',
    opis: 'Z serem cheddar wmieszanym pod koniec smażenia.',
    porcje: 2,
    czasMinut: 12,
    skladniki: ['5 jajek', '80 g cheddara', '30 g masła', 'szczypiorek', 'sól, pieprz'],
    kroki: [
      'Smaż jajka na małym ogniu, mieszając.',
      'Gdy są w połowie ścięte, wsyp starty ser.',
      'Mieszaj jeszcze 30 sekund i zdejmij z ognia.',
      'Posyp szczypiorkiem.',
    ],
  },
  {
    slug: 'herbed-details',
    parent: 'scrambled-eggs-details',
    nazwa: 'Herbed scrambled eggs',
    opis: 'Z natką, szczypiorkiem, koperkiem i estragonem — francuskie fines herbes.',
    porcje: 2,
    czasMinut: 12,
    skladniki: ['5 jajek', '30 g masła', 'natka pietruszki', 'szczypiorek', 'koperek', 'estragon', 'sól'],
    kroki: [
      'Zioła posiekaj bardzo drobno.',
      'Smaż jajka na maśle na małym ogniu.',
      'Wmieszaj zioła dopiero po zdjęciu z ognia — gorąco zabija ich aromat.',
      'Podawaj na grzance.',
    ],
  },
  {
    slug: 'smoked-salmon-details',
    parent: 'scrambled-eggs-details',
    nazwa: 'Scrambled eggs with smoked salmon',
    opis: 'Jajecznica z wędzonym łososiem i koperkiem, klasyka brunchu.',
    porcje: 2,
    czasMinut: 12,
    skladniki: ['5 jajek', '120 g łososia wędzonego', '30 g masła', 'koperek', 'śmietanka', 'pieprz', 'kapary'],
    kroki: [
      'Łososia pokrój w paski.',
      'Smaż jajka na małym ogniu ze śmietanką.',
      'Gdy są prawie gotowe, wmieszaj łososia — ma się tylko podgrzać.',
      'Posyp koperkiem, kaparami i pieprzem; soli nie dodawaj.',
    ],
  },

  // ---------- shakshouka-details ----------
  {
    slug: 'spinach-and-feta-details',
    parent: 'shakshouka-details',
    nazwa: 'Green shakshouka with spinach and feta',
    opis: 'Zielona wersja szakszuki na szpinaku, z fetą zamiast pomidorów.',
    porcje: 4,
    czasMinut: 30,
    skladniki: ['500 g szpinaku', '200 g fety', '6 jajek', '1 cebula', '3 ząbki czosnku', 'kmin rzymski', 'oliwa', 'chili'],
    kroki: [
      'Zeszklij cebulę z czosnkiem i kminem rzymskim.',
      'Dodaj szpinak i duś, aż zwiędnie.',
      'Zrób wgłębienia i wbij w nie jajka.',
      'Przykryj i gotuj 8 minut, aż białka się zetną, a żółtka pozostaną płynne.',
      'Pokrusz fetę na wierzch.',
    ],
  },
  {
    slug: 'zucchini-and-eggplant-details',
    parent: 'shakshouka-details',
    nazwa: 'Shakshouka with zucchini and eggplant',
    opis: 'Z podsmażoną cukinią i bakłażanem w sosie pomidorowym.',
    porcje: 4,
    czasMinut: 45,
    skladniki: ['1 bakłażan', '2 cukinie', '800 g pomidorów', '6 jajek', '1 cebula', 'papryka wędzona', 'kmin rzymski', 'kolendra'],
    kroki: [
      'Bakłażan i cukinię pokrój w kostkę i podsmaż osobno na oliwie.',
      'Dodaj cebulę, przyprawy i pomidory, duś 20 minut.',
      'Zrób wgłębienia i wbij jajka.',
      'Przykryj i gotuj 8 minut.',
    ],
  },
  {
    slug: 'chorizo-details',
    parent: 'shakshouka-details',
    nazwa: 'Shakshouka with chorizo',
    opis: 'Z kiełbasą chorizo, która oddaje do sosu papryczany tłuszcz.',
    porcje: 4,
    czasMinut: 40,
    skladniki: ['200 g chorizo', '800 g pomidorów', '6 jajek', '2 papryki', '1 cebula', 'papryka wędzona', 'czosnek', 'natka'],
    kroki: [
      'Chorizo podsmaż na sucho, aż wytopi się czerwony tłuszcz.',
      'Na tym tłuszczu podsmaż cebulę i paprykę.',
      'Dodaj pomidory i duś 20 minut.',
      'Wbij jajka i gotuj pod przykryciem 8 minut.',
    ],
  },
  {
    slug: 'bell-pepper-and-chickpea-details',
    parent: 'shakshouka-details',
    nazwa: 'Shakshouka with bell pepper and chickpea',
    opis: 'Sycąca wersja z ciecierzycą, bez mięsa.',
    porcje: 4,
    czasMinut: 40,
    skladniki: ['3 papryki', '1 puszka ciecierzycy', '800 g pomidorów', '6 jajek', 'kmin rzymski', 'kolendra mielona', 'harissa', 'oliwa'],
    kroki: [
      'Paprykę podsmaż z cebulą przez 10 minut.',
      'Dodaj przyprawy, pomidory i ciecierzycę, duś 20 minut.',
      'Dopraw harissą do żądanej ostrości.',
      'Wbij jajka i duś pod przykryciem 8 minut.',
    ],
  },
  {
    slug: 'mushroom-and-olive-details',
    parent: 'shakshouka-details',
    nazwa: 'Shakshouka with mushroom and olive',
    opis: 'Z pieczarkami i oliwkami, o wyraźnie słonym profilu.',
    porcje: 4,
    czasMinut: 40,
    skladniki: ['400 g pieczarek', '100 g oliwek', '800 g pomidorów', '6 jajek', 'czosnek', 'tymianek', 'oliwa', 'chili'],
    kroki: [
      'Pieczarki podsmaż na dużym ogniu do zarumienienia.',
      'Dodaj czosnek, pomidory i oliwki, duś 20 minut.',
      'Wbij jajka we wgłębienia.',
      'Przykryj i gotuj 8 minut, posyp tymiankiem.',
    ],
  },

  // ---------- shrimps-details ----------
  {
    slug: 'scampi-details',
    parent: 'shrimps-details',
    nazwa: 'Shrimp scampi',
    opis: 'Krewetki w maśle czosnkowym z białym winem i cytryną.',
    porcje: 2,
    czasMinut: 20,
    skladniki: ['400 g krewetek', '80 g masła', '4 ząbki czosnku', '100 ml białego wina', '1 cytryna', 'natka pietruszki', 'chili'],
    kroki: [
      'Krewetki osusz i dopraw solą.',
      'Smaż na maśle po 90 sekund z każdej strony i wyjmij.',
      'Na tej samej patelni podsmaż czosnek, wlej wino i zredukuj.',
      'Wróć krewetki, dodaj sok z cytryny i natkę.',
    ],
  },
  {
    slug: 'coconut-details',
    parent: 'shrimps-details',
    nazwa: 'Coconut shrimp',
    opis: 'Krewetki w panierce z wiórków kokosowych, smażone w głębokim tłuszczu.',
    porcje: 4,
    czasMinut: 30,
    skladniki: ['500 g krewetek', '100 g mąki', '2 jajka', '150 g wiórków kokosowych', 'panko', 'olej do smażenia', 'sos słodko-kwaśny'],
    kroki: [
      'Wymieszaj wiórki kokosowe z panko — samo kokos przypala się za szybko.',
      'Krewetki obtocz w mące, jajku i panierce.',
      'Smaż w oleju 170°C przez 2 minuty.',
      'Odsącz i podawaj z sosem słodko-kwaśnym.',
    ],
  },
  {
    slug: 'pad-thai-details',
    parent: 'shrimps-details',
    nazwa: 'Shrimp pad thai',
    opis: 'Krewetki w tajskim makaronie ryżowym z sosem tamaryndowym.',
    porcje: 4,
    czasMinut: 40,
    skladniki: ['300 g makaronu ryżowego', '400 g krewetek', '2 jajka', 'pasta tamaryndowa', 'sos rybny', 'cukier palmowy', 'kiełki', 'orzeszki', 'limonka'],
    kroki: [
      'Makaron namocz w ciepłej wodzie przez 30 minut.',
      'Krewetki usmaż na woku 90 sekund i odłóż.',
      'Wbij jajka, rozmieszaj, dodaj makaron i sos.',
      'Wróć krewetki, dodaj kiełki i orzeszki.',
    ],
  },
  {
    slug: 'coctail-details',
    parent: 'shrimps-details',
    nazwa: 'Shrimp cocktail',
    opis: 'Schłodzone krewetki z sosem koktajlowym — przystawka z lat siedemdziesiątych.',
    porcje: 4,
    czasMinut: 30,
    skladniki: ['500 g krewetek', 'ketchup', 'chrzan', 'sos worcestershire', 'majonez', 'cytryna', 'sałata lodowa', 'tabasco'],
    kroki: [
      'Krewetki ugotuj 2 minuty w osolonej wodzie z cytryną.',
      'Od razu przełóż do lodowatej wody, żeby przerwać gotowanie.',
      'Sos: ketchup, majonez, chrzan, worcestershire i kilka kropli tabasco.',
      'Podawaj w kieliszkach na posiekanej sałacie.',
    ],
  },
  {
    slug: 'garlic-butter-details',
    parent: 'shrimps-details',
    nazwa: 'Garlic butter shrimp',
    opis: 'Krewetki smażone w dużej ilości masła z czosnkiem i papryką.',
    porcje: 2,
    czasMinut: 15,
    skladniki: ['400 g krewetek', '100 g masła', '5 ząbków czosnku', 'papryka wędzona', 'natka', 'sok z cytryny', 'pieczywo'],
    kroki: [
      'Rozgrzej masło i wrzuć rozgnieciony czosnek na 30 sekund.',
      'Dodaj krewetki i paprykę wędzoną.',
      'Smaż 2 minuty, mieszając — krewetki są gotowe, gdy zwiną się w literę C.',
      'Skrop cytryną i podawaj z pieczywem do maczania.',
    ],
  },

  // ---------- silesian-noodles-details ----------
  {
    slug: 'traditional-silesian-noodles-details',
    parent: 'silesian-noodles-details',
    nazwa: 'Kluski śląskie',
    opis: 'Białe kluski z ziemniaków i skrobi, z charakterystycznym wgłębieniem na sos.',
    porcje: 4,
    czasMinut: 60,
    skladniki: ['1 kg ziemniaków', 'skrobia ziemniaczana', '1 jajko', 'sól'],
    kroki: [
      'Ziemniaki ugotuj i przeciśnij przez praskę, ostudź.',
      'Wyrównaj masę w misce i wykrój ćwiartkę — tę część uzupełnij skrobią.',
      'Dodaj jajko i zagnieć gładkie ciasto.',
      'Formuj kulki i zrób w każdej wgłębienie kciukiem.',
      'Gotuj 3 minuty od wypłynięcia.',
    ],
  },
  {
    slug: 'drop-noodles-details',
    parent: 'silesian-noodles-details',
    nazwa: 'Kluski kładzione',
    opis: 'Najprostsze kluski, kładzione łyżką prosto do wrzątku.',
    porcje: 4,
    czasMinut: 30,
    skladniki: ['300 g mąki', '2 jajka', '150 ml wody', 'sól', 'masło'],
    kroki: [
      'Wymieszaj mąkę z jajkami i wodą na gęste, kleiste ciasto.',
      'Nabieraj łyżką i zanurzaj ją we wrzątku przed każdą porcją — ciasto samo się wtedy zsuwa.',
      'Gotuj 4 minuty od wypłynięcia.',
      'Polej roztopionym masłem.',
    ],
  },
  {
    slug: 'lazy-dumplings-details',
    parent: 'silesian-noodles-details',
    nazwa: 'Kluski leniwe',
    opis: 'Kluski z twarogu, krojone ukośnie z wałka, podawane z masłem i cukrem.',
    porcje: 4,
    czasMinut: 35,
    skladniki: ['500 g twarogu', '2 jajka', '150 g mąki', '2 łyżki kaszy manny', 'sól', 'masło', 'cukier', 'cynamon'],
    kroki: [
      'Twaróg zmiel lub przeciśnij przez sito.',
      'Wymieszaj z jajkami, mąką i kaszą manną, odstaw na 15 minut.',
      'Uformuj wałki, spłaszcz i pokrój ukośnie.',
      'Gotuj 3 minuty i podawaj z masłem, cukrem i cynamonem.',
    ],
  },
  {
    slug: 'steamed-dumplings-details',
    parent: 'silesian-noodles-details',
    nazwa: 'Pyzy na parze',
    opis: 'Drożdżowe kluski gotowane na parze, podawane do mięsa z sosem.',
    porcje: 4,
    czasMinut: 120,
    skladniki: ['500 g mąki', '250 ml mleka', '15 g drożdży', '1 jajko', '2 łyżki cukru', 'sól', 'masło'],
    kroki: [
      'Zrób rozczyn i pozwól mu ruszyć przez 15 minut.',
      'Zagnieć ciasto i odstaw do podwojenia objętości.',
      'Formuj kulki i pozwól im wyrosnąć jeszcze 20 minut.',
      'Gotuj na parze 12 minut, NIE otwierając pokrywki — inaczej opadną.',
    ],
  },
  {
    slug: 'filled-dumplings-details',
    parent: 'silesian-noodles-details',
    nazwa: 'Pyzy z mięsem',
    opis: 'Ziemniaczane kluski nadziewane mięsem, podawane ze skwarkami.',
    porcje: 4,
    czasMinut: 90,
    skladniki: ['1,5 kg ziemniaków', '300 g mielonego mięsa', '1 cebula', 'skrobia ziemniaczana', '1 jajko', 'boczek', 'sól, pieprz, majeranek'],
    kroki: [
      'Połowę ziemniaków ugotuj, połowę zetrzyj na surowo i odciśnij.',
      'Połącz obie części ze skrobią i jajkiem.',
      'Farsz z podsmażonego mięsa z cebulą dopraw majerankiem.',
      'Formuj kule z nadzieniem w środku i gotuj 20 minut.',
      'Podawaj ze skwarkami.',
    ],
  },

  // ---------- sour-rye-soup-details ----------
  {
    slug: 'classic-sour-rye-soup-details',
    parent: 'sour-rye-soup-details',
    nazwa: 'Żurek',
    opis: 'Kwaśna zupa na zakwasie żytnim, z białą kiełbasą i jajkiem.',
    porcje: 6,
    czasMinut: 60,
    skladniki: ['500 ml zakwasu żytniego', '1,5 l wywaru', '400 g białej kiełbasy', '4 jajka', '150 g boczku wędzonego', 'czosnek', 'majeranek', 'chrzan'],
    kroki: [
      'Ugotuj wywar z boczku i włoszczyzny.',
      'Dodaj kiełbasę i gotuj 20 minut, potem wyjmij i pokrój.',
      'Wlej zakwas, cały czas mieszając, i zagotuj.',
      'Dopraw czosnkiem, majerankiem i łyżką chrzanu.',
      'Podawaj z połówką jajka na twardo.',
    ],
  },
  {
    slug: 'sour-rye-soup-with-bacon-and-eggs-details',
    parent: 'sour-rye-soup-details',
    nazwa: 'Żurek z boczkiem i jajkiem',
    opis: 'Wersja bez kiełbasy, za to z dużą ilością wędzonego boczku.',
    porcje: 6,
    czasMinut: 55,
    skladniki: ['500 ml zakwasu', '1,5 l wywaru warzywnego', '300 g boczku wędzonego', '4 jajka', 'śmietana 18%', 'czosnek', 'majeranek'],
    kroki: [
      'Boczek pokrój w kostkę i wytop do chrupkości.',
      'Wywar zagotuj z wytopionym boczkiem.',
      'Wlej zakwas i zagotuj, mieszając.',
      'Zahartuj śmietanę i wmieszaj.',
      'Podawaj z jajkiem i skwarkami.',
    ],
  },
  {
    slug: 'sour-rye-soup-with-mushroom-details',
    parent: 'sour-rye-soup-details',
    nazwa: 'Żurek grzybowy',
    opis: 'Postna wersja na wywarze z suszonych grzybów.',
    porcje: 6,
    czasMinut: 70,
    skladniki: ['500 ml zakwasu', '40 g suszonych grzybów', '1,5 l wody', 'ziemniaki', 'czosnek', 'majeranek', 'liść laurowy', 'olej'],
    kroki: [
      'Grzyby namocz przez noc, ugotuj i pokrój; wodę zachowaj.',
      'Zagotuj wywar grzybowy z ziemniakami.',
      'Wlej zakwas i zagotuj.',
      'Dopraw czosnkiem i majerankiem.',
    ],
  },
  {
    slug: 'sour-rye-soup-with-white-sausage-details',
    parent: 'sour-rye-soup-details',
    nazwa: 'Żurek z białą kiełbasą',
    opis: 'Klasyczna wielkanocna wersja z dużą porcją kiełbasy i chrzanem.',
    porcje: 6,
    czasMinut: 60,
    skladniki: ['500 ml zakwasu', '1,5 l wywaru', '600 g białej kiełbasy', '4 jajka', 'chrzan tarty', 'śmietana', 'czosnek', 'majeranek'],
    kroki: [
      'Kiełbasę gotuj w wywarze 25 minut, nie nakłuwając jej.',
      'Wyjmij, pokrój w plastry i podsmaż na patelni dla smaku.',
      'Wlej zakwas do wywaru i zagotuj.',
      'Dodaj chrzan i śmietanę, wróć kiełbasę.',
    ],
  },
  {
    slug: 'vegetarian-sour-rye-soup-details',
    parent: 'sour-rye-soup-details',
    nazwa: 'Żurek wegetariański',
    opis: 'Na wywarze warzywnym, z wędzoną papryką zamiast mięsa.',
    porcje: 6,
    czasMinut: 55,
    skladniki: ['500 ml zakwasu', '1,5 l wywaru warzywnego', '2 łyżeczki papryki wędzonej', 'ziemniaki', '4 jajka', 'śmietana roślinna', 'czosnek', 'majeranek'],
    kroki: [
      'Ugotuj wywar warzywny z ziemniakami.',
      'Dodaj paprykę wędzoną — to ona zastępuje dymny smak wędzonki.',
      'Wlej zakwas i zagotuj.',
      'Dopraw czosnkiem i majerankiem, podawaj z jajkiem.',
    ],
  },

  // ---------- spaghetti-details ----------
  {
    slug: 'spaghetti-carbonara-details',
    parent: 'spaghetti-details',
    nazwa: 'Spaghetti carbonara',
    opis: 'Cztery składniki: guanciale, jajka, pecorino i pieprz. Bez śmietany.',
    porcje: 4,
    czasMinut: 25,
    skladniki: ['400 g spaghetti', '200 g guanciale', '4 żółtka', '1 jajko', '100 g pecorino romano', 'czarny pieprz'],
    kroki: [
      'Guanciale wytop powoli, aż stanie się chrupiące.',
      'Żółtka utrzyj z serem i pieprzem na gęstą pastę.',
      'Makaron ugotuj al dente, zachowaj wodę.',
      'Zdejmij patelnię z ognia, dodaj makaron, potem masę jajeczną.',
      'Mieszaj z wodą z makaronu — temperatura ma zrobić krem, nie jajecznicę.',
    ],
  },
  {
    slug: 'spaghetti-bolognese-details',
    parent: 'spaghetti-details',
    nazwa: 'Spaghetti bolognese',
    opis: 'Makaron z długo duszonym ragù mięsnym.',
    porcje: 4,
    czasMinut: 180,
    skladniki: ['400 g spaghetti', '500 g mielonej wołowiny', '150 g boczku', 'włoszczyzna', '200 ml czerwonego wina', '400 g pomidorów', '200 ml mleka', 'parmezan'],
    kroki: [
      'Zrób sofrito i obsmaż mięso z boczkiem.',
      'Wlej mleko i odparuj, potem wino i odparuj.',
      'Dodaj pomidory i duś 2 godziny.',
      'Wymieszaj z makaronem na patelni i posyp parmezanem.',
    ],
  },
  {
    slug: 'spaghetti-aglio-e-olio-details',
    parent: 'spaghetti-details',
    nazwa: 'Spaghetti aglio e olio',
    opis: 'Czosnek, oliwa, chili i natka — danie z trzech składników i wody z makaronu.',
    porcje: 4,
    czasMinut: 20,
    skladniki: ['400 g spaghetti', '6 ząbków czosnku', '100 ml oliwy', '2 papryczki chili', 'natka pietruszki', 'sól'],
    kroki: [
      'Czosnek pokrój w cienkie plasterki.',
      'Smaż w oliwie na małym ogniu, aż będzie jasnozłoty — przypalony zgorzknieje i danie jest do wyrzucenia.',
      'Dodaj chili i wyłącz ogień.',
      'Wrzuć makaron z chochlą wody i mieszaj energicznie, aż powstanie kremowa emulsja.',
      'Posyp natką.',
    ],
  },
  {
    slug: 'spaghetti-alle-vongole-details',
    parent: 'spaghetti-details',
    nazwa: 'Spaghetti alle vongole',
    opis: 'Z małżami vongole, białym winem i czosnkiem.',
    porcje: 4,
    czasMinut: 35,
    skladniki: ['400 g spaghetti', '1 kg małży vongole', '150 ml białego wina', '4 ząbki czosnku', 'chili', 'natka pietruszki', 'oliwa'],
    kroki: [
      'Małże mocz w słonej wodzie 2 godziny, żeby pozbyły się piasku.',
      'Podsmaż czosnek z chili, wrzuć małże i wlej wino.',
      'Przykryj na 4 minuty, aż się otworzą; zamknięte wyrzuć.',
      'Makaron ugotuj do 2 minut przed al dente i dokończ na patelni.',
      'Sos zemulguj wodą z makaronu i posyp natką.',
    ],
  },
  {
    slug: 'spaghetti-alla-puttanesca-details',
    parent: 'spaghetti-details',
    nazwa: 'Spaghetti alla puttanesca',
    opis: 'Ostry sos z anchois, kaparów, oliwek i pomidorów.',
    porcje: 4,
    czasMinut: 30,
    skladniki: ['400 g spaghetti', '6 filetów anchois', '3 łyżki kaparów', '100 g oliwek czarnych', '800 g pomidorów', '3 ząbki czosnku', 'chili', 'natka'],
    kroki: [
      'Anchois rozpuść w oliwie z czosnkiem na małym ogniu — mają zniknąć.',
      'Dodaj kapary, oliwki i chili.',
      'Wlej pomidory i gotuj 15 minut.',
      'Wymieszaj z makaronem; soli zwykle nie trzeba.',
    ],
  },

  // ---------- sushi-details ----------
  {
    slug: 'nigiri-sushi-details',
    parent: 'sushi-details',
    nazwa: 'Nigiri sushi',
    opis: 'Ręcznie formowany wałeczek ryżu z plastrem ryby na wierzchu.',
    porcje: 4,
    czasMinut: 90,
    skladniki: ['400 g ryżu do sushi', '60 ml octu ryżowego', '2 łyżki cukru', '1 łyżeczka soli', '300 g ryby w jakości sashimi', 'wasabi', 'sos sojowy'],
    kroki: [
      'Ryż płucz, aż woda będzie przezroczysta, i ugotuj.',
      'Wymieszaj ocet z cukrem i solą, wmieszaj w ciepły ryż drewnianą łopatką, tnąc, nie mieszając.',
      'Ostudź do temperatury ciała.',
      'Zwilż dłonie, uformuj wałeczek, posmaruj wasabi i przykryj plastrem ryby.',
      'Dociśnij dwoma palcami — ryż ma się rozpaść w ustach, nie w palcach.',
    ],
  },
  {
    slug: 'maki-sushi-details',
    parent: 'sushi-details',
    nazwa: 'Maki sushi',
    opis: 'Rolki zawijane w nori na macie bambusowej.',
    porcje: 4,
    czasMinut: 75,
    skladniki: ['400 g ryżu do sushi', 'ocet ryżowy', '4 arkusze nori', 'łosoś', 'ogórek', 'awokado', 'wasabi', 'mata bambusowa'],
    kroki: [
      'Nori połóż szorstką stroną do góry na macie.',
      'Rozłóż ryż, zostawiając 2 cm wolnego brzegu u góry.',
      'Ułóż nadzienie w poprzek, bliżej siebie.',
      'Zwijaj matą, dociskając po każdym obrocie.',
      'Kroj mokrym nożem na 6–8 kawałków.',
    ],
  },
  {
    slug: 'temaki-sushi-details',
    parent: 'sushi-details',
    nazwa: 'Temaki sushi',
    opis: 'Ręcznie zwijane rożki z nori — je się je od razu, zanim nori zmięknie.',
    porcje: 4,
    czasMinut: 40,
    skladniki: ['400 g ryżu do sushi', '8 arkuszy nori przeciętych na pół', 'łosoś', 'tuńczyk', 'awokado', 'ogórek', 'majonez japoński'],
    kroki: [
      'Połówkę nori trzymaj na dłoni.',
      'Nałóż ryż na lewą połowę, ukośnie.',
      'Ułóż nadzienie po przekątnej.',
      'Zawiń w rożek, zaczynając od dolnego lewego rogu.',
      'Podawaj natychmiast — nori traci chrupkość w kilka minut.',
    ],
  },
  {
    slug: 'chirashi-sushi-details',
    parent: 'sushi-details',
    nazwa: 'Chirashi sushi',
    opis: 'Ryż w misce, na nim rozsypane kawałki ryby i warzyw — sushi bez zwijania.',
    porcje: 4,
    czasMinut: 45,
    skladniki: ['400 g ryżu do sushi', 'ocet ryżowy', '300 g mieszanych ryb sashimi', 'ikura', 'omlet tamagoyaki', 'ogórek', 'marynowany imbir', 'nori'],
    kroki: [
      'Przygotuj ryż z octem i ostudź.',
      'Rozłóż w płaskich miskach.',
      'Ułóż na wierzchu plastry ryb, omlet i warzywa.',
      'Udekoruj ikurą i paskami nori.',
    ],
  },

  // ---------- sweet-crepes-details ----------
  {
    slug: 'nutella-and-banana-crepes-details',
    parent: 'sweet-crepes-details',
    nazwa: 'Nutella and banana crepes',
    opis: 'Naleśniki z kremem czekoladowo-orzechowym i bananem.',
    porcje: 4,
    czasMinut: 35,
    skladniki: ['200 g mąki', '500 ml mleka', '3 jajka', '4 banany', '200 g kremu czekoladowo-orzechowego', 'masło', 'cukier puder'],
    kroki: [
      'Ciasto naleśnikowe odstaw na 30 minut — mąka musi napęcznieć.',
      'Smaż cienkie naleśniki na dobrze rozgrzanej patelni.',
      'Ciepły naleśnik posmaruj kremem, ułóż plastry banana.',
      'Złóż na cztery i oprósz cukrem pudrem.',
    ],
  },
  {
    slug: 'strawberry-crepes-details',
    parent: 'sweet-crepes-details',
    nazwa: 'Strawberry crepes',
    opis: 'Z truskawkami i bitą śmietaną.',
    porcje: 4,
    czasMinut: 35,
    skladniki: ['200 g mąki', '500 ml mleka', '3 jajka', '400 g truskawek', '250 ml śmietanki 30%', 'cukier puder', 'wanilia'],
    kroki: [
      'Usmaż cienkie naleśniki.',
      'Truskawki pokrój i wymieszaj z łyżką cukru, odstaw na 10 minut.',
      'Ubij śmietanę z wanilią.',
      'Nałóż nadzienie i zwiń naleśniki w rulony.',
    ],
  },
  {
    slug: 'lemon-and-sugar-crepes-details',
    parent: 'sweet-crepes-details',
    nazwa: 'Lemon and sugar crepes',
    opis: 'Najprostsza brytyjska wersja: sok z cytryny i cukier.',
    porcje: 4,
    czasMinut: 30,
    skladniki: ['200 g mąki', '500 ml mleka', '3 jajka', '2 cytryny', '100 g cukru', 'masło'],
    kroki: [
      'Usmaż cienkie naleśniki na maśle.',
      'Jeszcze gorący posyp cukrem.',
      'Skrop obficie sokiem z cytryny.',
      'Zwiń w rulon i podawaj od razu.',
    ],
  },
  {
    slug: 'blueberry-and-ricotta-crepes-details',
    parent: 'sweet-crepes-details',
    nazwa: 'Blueberry and ricotta crepes',
    opis: 'Z ricottą utartą z cukrem i borówkami.',
    porcje: 4,
    czasMinut: 40,
    skladniki: ['200 g mąki', '500 ml mleka', '3 jajka', '400 g ricotty', '300 g borówek', '3 łyżki cukru pudru', 'skórka z cytryny'],
    kroki: [
      'Ricottę utrzyj z cukrem pudrem i skórką z cytryny.',
      'Połowę borówek podduś z łyżką cukru na sos.',
      'Naleśniki posmaruj masą i nałóż świeże borówki.',
      'Złóż i polej sosem.',
    ],
  },
  {
    slug: 'apple-cinamon-sweet-crepes-details',
    parent: 'sweet-crepes-details',
    nazwa: 'Apple cinnamon crepes',
    opis: 'Z jabłkami duszonymi z cynamonem i masłem.',
    porcje: 4,
    czasMinut: 40,
    skladniki: ['200 g mąki', '500 ml mleka', '3 jajka', '4 jabłka', '50 g masła', '3 łyżki brązowego cukru', 'cynamon', 'rodzynki'],
    kroki: [
      'Jabłka pokrój w plastry i duś na maśle z cukrem i cynamonem 10 minut.',
      'Dodaj rodzynki na ostatnie 2 minuty.',
      'Usmaż naleśniki.',
      'Nałóż jabłka, złóż i podawaj ciepłe.',
    ],
  },
];
