import { Przepis } from '../przepis.model';

/** Barszcze, boba tea, pieczywo z oliwą, bruschetta, gołąbki, calzone,
 *  caprese, cheeseburgery, dorsz, confit, coq au vin, naleśniki. */
export const PACZKA_1: Przepis[] = [
  // ---------- Beetroot soup ----------
  {
    slug: 'classic-borscht-details',
    parent: 'beetroot-soup-details',
    nazwa: 'Classic borscht',
    opis: 'Czerwony barszcz na wywarze warzywnym z burakami, zakwaszony octem lub sokiem z cytryny.',
    porcje: 4,
    czasMinut: 75,
    skladniki: ['600 g buraków', '1 marchewka', '1 pietruszka', '1 cebula', '1,5 l bulionu warzywnego', '2 ząbki czosnku', '2 łyżki octu winnego', 'sól, pieprz, majeranek'],
    kroki: [
      'Buraki obierz i zetrzyj na grubych oczkach, warzywa korzeniowe pokrój w kostkę.',
      'Podsmaż cebulę na maśle, dodaj warzywa i smaż 5 minut.',
      'Wlej bulion, gotuj pod przykryciem 40 minut, aż buraki zmiękną.',
      'Dopraw octem, czosnkiem i majerankiem — ocet dodaj na końcu, żeby barszcz nie stracił koloru.',
      'Odstaw na 10 minut przed podaniem.',
    ],
  },
  {
    slug: 'ukrainian-borscht-details',
    parent: 'beetroot-soup-details',
    nazwa: 'Ukrainian borscht',
    opis: 'Gęsty barszcz ukraiński na wołowinie, z kapustą i fasolą, podawany ze śmietaną i pampuszkami.',
    porcje: 6,
    czasMinut: 150,
    skladniki: ['700 g łopatki wołowej', '500 g buraków', '300 g kapusty białej', '2 ziemniaki', '1 puszka białej fasoli', '2 łyżki koncentratu pomidorowego', 'koperek', 'śmietana 18%'],
    kroki: [
      'Ugotuj wywar z wołowiny — około 90 minut, zbierając szumowiny.',
      'Wyjmij mięso, pokrój, wywar przecedź.',
      'Dodaj ziemniaki i poszatkowaną kapustę, gotuj 15 minut.',
      'Dorzuć starte buraki, fasolę i koncentrat, gotuj kolejne 20 minut.',
      'Wróć mięso do garnka, dopraw i podawaj ze śmietaną i koperkiem.',
    ],
  },
  {
    slug: 'polish-barszcz-details',
    parent: 'beetroot-soup-details',
    nazwa: 'Polish barszcz',
    opis: 'Klarowny barszcz czysty na zakwasie buraczanym — wigilijny, podawany z uszkami.',
    porcje: 6,
    czasMinut: 60,
    skladniki: ['500 ml zakwasu buraczanego', '1,5 l wywaru grzybowego', '2 buraki', '4 ziarna ziela angielskiego', '2 liście laurowe', '3 ząbki czosnku', 'sól, pieprz, cukier'],
    kroki: [
      'Zagotuj wywar grzybowy z zielem angielskim i liściem laurowym.',
      'Dodaj pokrojone buraki i gotuj 25 minut na małym ogniu.',
      'Przecedź przez gęste sito — barszcz czysty nie może być mętny.',
      'Wlej zakwas i podgrzej, ale NIE gotuj — gotowanie zabija kolor i kwasowość.',
      'Dopraw czosnkiem, solą i szczyptą cukru.',
    ],
  },
  {
    slug: 'lithuanian-saltibarščiai-details',
    parent: 'beetroot-soup-details',
    nazwa: 'Lithuanian šaltibarščiai',
    opis: 'Litewski chłodnik na kefirze — jaskrawo różowy, podawany latem z gorącymi ziemniakami.',
    porcje: 4,
    czasMinut: 30,
    skladniki: ['1 l kefiru', '400 g ugotowanych buraków', '2 ogórki świeże', '3 jajka ugotowane na twardo', 'pęczek koperku', 'pęczek szczypiorku', 'sól, pieprz'],
    kroki: [
      'Buraki zetrzyj na grubych oczkach, ogórki pokrój w drobną kostkę.',
      'Wymieszaj z kefirem i posiekanymi ziołami.',
      'Dopraw solą i pieprzem, wstaw do lodówki na minimum 2 godziny.',
      'Podawaj z połówką jajka i osobno ugotowanymi gorącymi ziemniakami — to obowiązkowy kontrast.',
    ],
  },
  {
    slug: 'russian-svekolnik-details',
    parent: 'beetroot-soup-details',
    nazwa: 'Russian svekolnik',
    opis: 'Rosyjski chłodnik buraczany na kwasie chlebowym, lżejszy i bardziej kwaśny od litewskiego.',
    porcje: 4,
    czasMinut: 35,
    skladniki: ['700 ml kwasu chlebowego', '400 g buraków', '2 ogórki', '3 jajka', '150 g śmietany', 'koperek', 'sok z połowy cytryny'],
    kroki: [
      'Buraki ugotuj, ostudź i zetrzyj.',
      'Ogórki i jajka pokrój w kostkę.',
      'Zalej kwasem chlebowym, dodaj śmietanę i sok z cytryny.',
      'Schłodź przez 2 godziny, dopraw i posyp koperkiem.',
    ],
  },

  // ---------- Boba tea ----------
  {
    slug: 'classic-boba-tea-details',
    parent: 'boba-tea-details',
    nazwa: 'Classic boba tea',
    opis: 'Tajwański napój z czarnej herbaty z mlekiem i kulkami tapioki na dnie kubka.',
    porcje: 2,
    czasMinut: 40,
    skladniki: ['2 łyżki czarnej herbaty liściastej', '1 szklanka wrzątku', '2 łyżki syropu tapiokowego', '1/4 szklanki kulek tapioki', '1/2 szklanki mleka', 'cukier trzcinowy', 'lód', 'szeroka słomka'],
    kroki: [
      'Gotuj kulki tapioki we wrzątku 15–20 minut, aż zmiękną.',
      'Dodaj cukier trzcinowy i pogotuj jeszcze 5 minut, potem odstaw na 10 minut.',
      'Zaparz herbatę przez 3–5 minut i ostudź.',
      'Przełóż tapiokę na dno szklanki, dodaj lód.',
      'Zalej herbatą, wlej mleko i syrop, wymieszaj.',
    ],
  },
  {
    slug: 'fruit-boba-tea-details',
    parent: 'boba-tea-details',
    nazwa: 'Fruit boba tea',
    opis: 'Owocowa wersja na zielonej herbacie, bez mleka — lżejsza i bardziej orzeźwiająca.',
    porcje: 2,
    czasMinut: 35,
    skladniki: ['2 łyżki zielonej herbaty', '200 ml soku z mango lub marakui', '1/4 szklanki kulek tapioki', '1 łyżka miodu', 'plasterki limonki', 'lód'],
    kroki: [
      'Ugotuj tapiokę i przełóż do zimnej wody, żeby nie skleiła się w bryłę.',
      'Zaparz zieloną herbatę 2 minuty w wodzie 80°C — wrzątek daje goryczkę.',
      'Ostudź herbatę i wymieszaj z sokiem owocowym i miodem.',
      'Wlej na tapiokę z lodem, udekoruj limonką.',
    ],
  },
  {
    slug: 'matcha-boba-tea-details',
    parent: 'boba-tea-details',
    nazwa: 'Matcha boba tea',
    opis: 'Kremowa wersja na sproszkowanej zielonej herbacie matcha, o wyraźnie trawiastym smaku.',
    porcje: 2,
    czasMinut: 30,
    skladniki: ['2 łyżeczki matchy', '60 ml gorącej wody (80°C)', '250 ml mleka', '1/4 szklanki kulek tapioki', '2 łyżki syropu cukrowego', 'lód'],
    kroki: [
      'Ugotuj i osłodź tapiokę.',
      'Przesiej matchę, zalej gorącą wodą i ubij bambusowym pędzelkiem na gładko.',
      'Wymieszaj z syropem cukrowym.',
      'Wlej mleko na tapiokę z lodem, na wierzch wylej matchę.',
    ],
  },
  {
    slug: 'taro-boba-tea-details',
    parent: 'boba-tea-details',
    nazwa: 'Taro boba tea',
    opis: 'Fioletowy napój z korzenia taro — słodki, orzechowy, z wyraźnie kremową konsystencją.',
    porcje: 2,
    czasMinut: 45,
    skladniki: ['200 g korzenia taro', '250 ml mleka', '2 łyżki cukru', '1/4 szklanki kulek tapioki', 'szczypta soli', 'lód'],
    kroki: [
      'Taro obierz, pokrój i gotuj na parze 20 minut, aż będzie miękkie.',
      'Zblenduj z mlekiem, cukrem i szczyptą soli na gładką masę.',
      'Ugotuj tapiokę i przełóż do szklanki.',
      'Zalej masą taro, dodaj lód.',
    ],
  },
  {
    slug: 'thai-boba-tea-details',
    parent: 'boba-tea-details',
    nazwa: 'Thai boba tea',
    opis: 'Mocna herbata tajska z mlekiem skondensowanym — pomarańczowa, bardzo słodka, przyprawiona anyżem.',
    porcje: 2,
    czasMinut: 35,
    skladniki: ['3 łyżki herbaty tajskiej', '400 ml wrzątku', '3 łyżki mleka skondensowanego', '50 ml mleka', '1 gwiazdka anyżu', '1/4 szklanki kulek tapioki', 'lód'],
    kroki: [
      'Zaparz herbatę z anyżem przez 5 minut i przecedź.',
      'Wmieszaj mleko skondensowane, jeszcze gdy herbata jest gorąca.',
      'Ostudź całkowicie.',
      'Nalej na tapiokę i lód, na wierzch wlej zwykłe mleko dla efektu warstw.',
    ],
  },

  // ---------- Bread with oil ----------
  {
    slug: 'ciabatta-with-oil-details',
    parent: 'bread-with-oil-details',
    nazwa: 'Ciabatta with oil',
    opis: 'Włoska przystawka: chrupiąca ciabatta z oliwą extra vergine i octem balsamicznym.',
    porcje: 2,
    czasMinut: 10,
    skladniki: ['1/2 bochenka ciabatty', '4 łyżki oliwy extra vergine', '1 łyżka octu balsamicznego', 'sól morska', 'świeżo mielony pieprz'],
    kroki: [
      'Ciabattę pokrój na grube kromki i podpiecz 3 minuty.',
      'Na płaskim talerzu wylej oliwę, na środek kropnij ocet balsamiczny.',
      'Posyp solą morską i pieprzem.',
      'Podawaj od razu — pieczywo maczasz samodzielnie przy stole.',
    ],
  },
  {
    slug: 'baguette-with-oil-details',
    parent: 'bread-with-oil-details',
    nazwa: 'Baguette with oil',
    opis: 'Francuska bagietka z oliwą i grubo mielonym pieprzem, podawana do wina.',
    porcje: 2,
    czasMinut: 10,
    skladniki: ['1 bagietka', '4 łyżki oliwy', '1 ząbek czosnku', 'gruby pieprz', 'sól'],
    kroki: [
      'Bagietkę przekrój wzdłuż i podpiecz pod grillem 2 minuty.',
      'Przetrzyj gorącą skórkę przekrojonym ząbkiem czosnku.',
      'Skrop oliwą, dopraw solą i pieprzem.',
    ],
  },
  {
    slug: 'greek-olive-bread-details',
    parent: 'bread-with-oil-details',
    nazwa: 'Greek olive bread',
    opis: 'Grecki chleb z oliwkami kalamata, wypiekany z oregano w cieście.',
    porcje: 6,
    czasMinut: 150,
    skladniki: ['500 g mąki pszennej', '7 g drożdży suszonych', '300 ml letniej wody', '150 g oliwek kalamata', '3 łyżki oliwy', '1 łyżeczka suszonego oregano', '10 g soli'],
    kroki: [
      'Rozczyn z drożdży, wody i łyżki mąki odstaw na 15 minut.',
      'Zagnieć ciasto z pozostałą mąką, oliwą i solą; wyrabiaj 10 minut.',
      'Wmieszaj pokrojone oliwki i oregano, odstaw do wyrośnięcia na godzinę.',
      'Uformuj bochenek, odstaw na 30 minut i piecz 35 minut w 220°C.',
    ],
  },
  {
    slug: 'herb-and-garlic-details',
    parent: 'bread-with-oil-details',
    nazwa: 'Herb and garlic bread',
    opis: 'Pieczywo czosnkowe z masłem ziołowym, zapiekane w folii do miękkości.',
    porcje: 4,
    czasMinut: 25,
    skladniki: ['1 bagietka', '100 g masła', '4 ząbki czosnku', 'pęczek natki pietruszki', '1 łyżeczka tymianku', 'sól'],
    kroki: [
      'Masło utrzyj z przeciśniętym czosnkiem i posiekanymi ziołami.',
      'Bagietkę natnij co 2 cm, nie przecinając do końca.',
      'Włóż masło w nacięcia, zawiń w folię aluminiową.',
      'Piecz 15 minut w 200°C, ostatnie 5 minut bez folii, żeby skórka się zarumieniła.',
    ],
  },

  // ---------- Bruschetta ----------
  {
    slug: 'tomato-and-basil-details',
    parent: 'bruschetta-details',
    nazwa: 'Tomato and basil bruschetta',
    opis: 'Klasyczna rzymska bruschetta z pomidorami, bazylią i czosnkiem na grillowanym pieczywie.',
    porcje: 4,
    czasMinut: 20,
    skladniki: ['4 kromki chleba wiejskiego', '4 dojrzałe pomidory', 'pęczek bazylii', '2 ząbki czosnku', '3 łyżki oliwy', 'sól, pieprz'],
    kroki: [
      'Pomidory sparz, obierz ze skórki i pokrój w kostkę; odsącz nadmiar soku.',
      'Wymieszaj z porwaną bazylią, oliwą, solą i pieprzem.',
      'Kromki opiecz na grillu lub patelni grillowej.',
      'Przetrzyj czosnkiem i nałóż pomidory bezpośrednio przed podaniem — inaczej chleb rozmięknie.',
    ],
  },
  {
    slug: 'Mushroom-and-goat-cheese-details',
    parent: 'bruschetta-details',
    nazwa: 'Mushroom and goat cheese bruschetta',
    opis: 'Cieplejsza wersja: podsmażone pieczarki z tymiankiem na kremowym kozim serze.',
    porcje: 4,
    czasMinut: 25,
    skladniki: ['4 kromki bagietki', '250 g pieczarek', '100 g sera koziego', '1 szalotka', '2 gałązki tymianku', '2 łyżki masła', 'sól, pieprz'],
    kroki: [
      'Pieczarki pokrój w plastry i smaż na maśle na dużym ogniu, aż odparuje woda.',
      'Dodaj szalotkę i tymianek, smaż jeszcze 3 minuty.',
      'Kromki opiecz i posmaruj serem kozim.',
      'Nałóż gorące pieczarki i dopraw pieprzem.',
    ],
  },
  {
    slug: 'fig-and-prosciutto-details',
    parent: 'bruschetta-details',
    nazwa: 'Fig and prosciutto bruschetta',
    opis: 'Słodko-słona kompozycja fig, szynki parmeńskiej i miodu.',
    porcje: 4,
    czasMinut: 15,
    skladniki: ['4 kromki chleba', '4 świeże figi', '80 g prosciutto', '2 łyżki miodu', '50 g mascarpone', 'rukola'],
    kroki: [
      'Kromki opiecz i posmaruj mascarpone.',
      'Figi pokrój w ćwiartki i ułóż na serze.',
      'Na wierzch połóż plaster prosciutto i garść rukoli.',
      'Skrop miodem tuż przed podaniem.',
    ],
  },
  {
    slug: 'avocado-and-tomato-details',
    parent: 'bruschetta-details',
    nazwa: 'Avocado and tomato bruschetta',
    opis: 'Lekka wersja z rozgniecionym awokado i pomidorkami koktajlowymi.',
    porcje: 4,
    czasMinut: 15,
    skladniki: ['4 kromki chleba żytniego', '2 awokado', '150 g pomidorków koktajlowych', 'sok z połowy limonki', 'płatki chili', 'sól, oliwa'],
    kroki: [
      'Awokado rozgnieć widelcem z sokiem z limonki i solą.',
      'Pomidorki przekrój na połówki.',
      'Kromki opiecz i rozsmaruj awokado.',
      'Ułóż pomidorki, skrop oliwą i posyp chili.',
    ],
  },
  {
    slug: 'peach-and-burrata-details',
    parent: 'bruschetta-details',
    nazwa: 'Peach and burrata bruschetta',
    opis: 'Letnia bruschetta z grillowaną brzoskwinią i kremową burratą.',
    porcje: 4,
    czasMinut: 20,
    skladniki: ['4 kromki chleba', '2 brzoskwinie', '1 burrata', 'listki bazylii', 'ocet balsamiczny', 'oliwa, sól'],
    kroki: [
      'Brzoskwinie pokrój w ósemki i grilluj po 2 minuty z każdej strony.',
      'Kromki opiecz i skrop oliwą.',
      'Rozłóż burratę, dodaj brzoskwinie i bazylię.',
      'Skrop octem balsamicznym i posól.',
    ],
  },

  // ---------- Cabbage rolls ----------
  {
    slug: 'polish-gołąbki-details',
    parent: 'cabbage-rolls-details',
    nazwa: 'Polish gołąbki',
    opis: 'Liście kapusty nadziewane mięsem mielonym z ryżem, duszone w sosie pomidorowym.',
    porcje: 4,
    czasMinut: 120,
    skladniki: ['1 główka kapusty białej', '500 g mięsa mielonego wieprzowo-wołowego', '150 g ryżu', '1 cebula', '500 ml passaty pomidorowej', 'sól, pieprz, majeranek'],
    kroki: [
      'Kapustę sparz w całości we wrzątku, oddzielaj liście w miarę mięknięcia.',
      'Ryż ugotuj na półtwardo, cebulę zeszklij.',
      'Wymieszaj mięso z ryżem i cebulą, dopraw solidnie.',
      'Nałóż farsz na liście, zawiń w rulony podwijając boki.',
      'Ułóż ciasno w garnku, zalej passatą i duś pod przykryciem 60 minut.',
    ],
  },
  {
    slug: 'ukrainian-holubtsi-details',
    parent: 'cabbage-rolls-details',
    nazwa: 'Ukrainian holubtsi',
    opis: 'Ukraińska wersja gołąbków — mniejsze, z kaszą gryczaną, duszone ze śmietaną.',
    porcje: 4,
    czasMinut: 110,
    skladniki: ['1 główka kapusty', '400 g mięsa mielonego', '150 g kaszy gryczanej', '1 marchewka', '200 ml śmietany 18%', '2 łyżki koncentratu pomidorowego', 'koper'],
    kroki: [
      'Kaszę ugotuj i wymieszaj z mięsem oraz startą marchewką.',
      'Sparz liście kapusty i zawiń niewielkie rulony.',
      'Ułóż w naczyniu żaroodpornym.',
      'Zalej śmietaną wymieszaną z koncentratem i duś 70 minut w 180°C.',
    ],
  },
  {
    slug: 'turkish-lahana-sarma-details',
    parent: 'cabbage-rolls-details',
    nazwa: 'Turkish lahana sarma',
    opis: 'Tureckie zawijańce z kapusty z ryżem, orzeszkami piniowymi i rodzynkami, podawane na zimno.',
    porcje: 4,
    czasMinut: 90,
    skladniki: ['1 główka kapusty', '200 g ryżu', '50 g orzeszków piniowych', '50 g rodzynek', '1 cebula', 'sok z cytryny', 'oliwa', 'mięta, cynamon'],
    kroki: [
      'Cebulę zeszklij na oliwie, dodaj orzeszki i podsmaż na złoto.',
      'Wmieszaj ryż, rodzynki, miętę i szczyptę cynamonu.',
      'Nadziewaj sparzone liście i zwijaj ciasne rulony.',
      'Ułóż w garnku, zalej wodą z sokiem z cytryny i gotuj 45 minut.',
      'Podawaj schłodzone — to przystawka, nie danie gorące.',
    ],
  },
  {
    slug: 'romanian-sarmale-details',
    parent: 'cabbage-rolls-details',
    nazwa: 'Romanian sarmale',
    opis: 'Rumuńskie sarmale z kapusty kiszonej, z boczkiem, duszone godzinami do miękkości.',
    porcje: 6,
    czasMinut: 210,
    skladniki: ['1 główka kapusty kiszonej', '600 g mięsa mielonego wieprzowego', '150 g ryżu', '150 g wędzonego boczku', '2 cebule', 'przecier pomidorowy', 'tymianek, liść laurowy'],
    kroki: [
      'Liście kapusty kiszonej wypłucz i osusz.',
      'Wymieszaj mięso z ryżem, podsmażoną cebulą i tymiankiem.',
      'Zawiń małe rulony i ułóż warstwami, przekładając plastrami boczku.',
      'Zalej przecierem z wodą, dodaj liść laurowy.',
      'Duś na najmniejszym ogniu 3 godziny — im dłużej, tym lepiej.',
    ],
  },
  {
    slug: 'middle-eastern-mahshi-malfouf-details',
    parent: 'cabbage-rolls-details',
    nazwa: 'Mahshi malfouf',
    opis: 'Bliskowschodnie zawijańce z kapusty z ryżem i jagnięciną, doprawione czosnkiem i miętą.',
    porcje: 4,
    czasMinut: 100,
    skladniki: ['1 główka kapusty', '300 g mielonej jagnięciny', '200 g ryżu', '6 ząbków czosnku', 'suszona mięta', 'sok z 2 cytryn', 'oliwa', 'siedem przypraw'],
    kroki: [
      'Wymieszaj surowy ryż z mięsem, oliwą i przyprawami.',
      'Nakładaj cienką warstwę farszu na sparzone liście i zwijaj wąskie rulony.',
      'Układaj ciasno, przekładając plastrami czosnku.',
      'Zalej wodą z sokiem z cytryny, przyciśnij talerzem i gotuj 50 minut.',
      'Na koniec posyp suszoną miętą.',
    ],
  },

  // ---------- Calzone ----------
  {
    slug: 'ham-and-cheese-calzone-details',
    parent: 'calzone-details',
    nazwa: 'Ham and cheese calzone',
    opis: 'Zamknięta pizza z Neapolu, nadziewana szynką i mozzarellą, pieczona do chrupkości.',
    porcje: 2,
    czasMinut: 100,
    skladniki: ['400 g ciasta na pizzę', '150 g szynki', '200 g mozzarelli', '150 g ricotty', 'oregano', 'oliwa', 'jajko do posmarowania'],
    kroki: [
      'Ciasto podziel na dwie części i rozwałkuj na okrągłe placki.',
      'Na połowie każdego placka ułóż ricottę, szynkę i mozzarellę.',
      'Złóż na pół i dokładnie zlep brzegi — nieszczelny calzone wyleje się w piekarniku.',
      'Posmaruj jajkiem, natnij wierzch dla ujścia pary.',
      'Piecz 15 minut w 240°C.',
    ],
  },
  {
    slug: 'mushroom-calzone-details',
    parent: 'calzone-details',
    nazwa: 'Mushroom calzone',
    opis: 'Wersja z podsmażonymi pieczarkami i czosnkiem, bez mięsa.',
    porcje: 2,
    czasMinut: 100,
    skladniki: ['400 g ciasta na pizzę', '300 g pieczarek', '200 g mozzarelli', '2 ząbki czosnku', 'tymianek', 'oliwa', 'sól, pieprz'],
    kroki: [
      'Pieczarki pokrój i smaż na dużym ogniu, aż odparuje cała woda.',
      'Dodaj czosnek i tymianek, smaż minutę.',
      'Rozłóż na cieście z mozzarellą, złóż i zlep brzegi.',
      'Piecz 15 minut w 240°C.',
    ],
  },
  {
    slug: 'vegetarian-calzone-details',
    parent: 'calzone-details',
    nazwa: 'Vegetarian calzone',
    opis: 'Nadzienie z grillowanych warzyw: cukinii, bakłażana i papryki.',
    porcje: 2,
    czasMinut: 105,
    skladniki: ['400 g ciasta na pizzę', '1 cukinia', '1 bakłażan', '1 papryka', '200 g mozzarelli', '4 łyżki passaty', 'bazylia', 'oliwa'],
    kroki: [
      'Warzywa pokrój w plastry i grilluj po 2 minuty z każdej strony.',
      'Rozwałkuj ciasto, rozsmaruj passatę na połowie.',
      'Ułóż warzywa i mozzarellę, złóż i zlep.',
      'Piecz 15 minut w 240°C, posyp bazylią po wyjęciu.',
    ],
  },
  {
    slug: 'sausage-calzone-details',
    parent: 'calzone-details',
    nazwa: 'Sausage calzone',
    opis: 'Mocna wersja z kiełbasą włoską i cebulą, doprawiona koprem włoskim.',
    porcje: 2,
    czasMinut: 100,
    skladniki: ['400 g ciasta na pizzę', '250 g kiełbasy włoskiej', '1 cebula', '200 g mozzarelli', '1 łyżeczka nasion kopru włoskiego', 'passata'],
    kroki: [
      'Kiełbasę wyjmij z osłonki i podsmaż, rozdrabniając widelcem.',
      'Dodaj cebulę i koper włoski, smaż 5 minut.',
      'Nałóż na ciasto z mozzarellą i passatą.',
      'Złóż, zlep i piecz 15 minut w 240°C.',
    ],
  },
  {
    slug: 'ricotta-and-spinach-calzone-details',
    parent: 'calzone-details',
    nazwa: 'Ricotta and spinach calzone',
    opis: 'Delikatne nadzienie ze szpinaku i ricotty z gałką muszkatołową.',
    porcje: 2,
    czasMinut: 95,
    skladniki: ['400 g ciasta na pizzę', '300 g szpinaku', '250 g ricotty', '50 g parmezanu', 'gałka muszkatołowa', '1 ząbek czosnku', 'oliwa'],
    kroki: [
      'Szpinak podduś z czosnkiem i odciśnij z wody — mokry farsz rozmoczy ciasto.',
      'Wymieszaj z ricottą, parmezanem i gałką muszkatołową.',
      'Nałóż na ciasto, złóż i dokładnie zlep brzegi.',
      'Piecz 15 minut w 240°C.',
    ],
  },

  // ---------- Caprese ----------
  {
    slug: 'caprese-with-tomatoes-and-mozzarella-details',
    parent: 'caprese-details',
    nazwa: 'Caprese with tomatoes and mozzarella',
    opis: 'Sałatka z Capri w barwach włoskiej flagi: pomidor, mozzarella, bazylia.',
    porcje: 2,
    czasMinut: 10,
    skladniki: ['3 dojrzałe pomidory', '250 g mozzarelli di bufala', 'pęczek bazylii', '4 łyżki oliwy extra vergine', 'sól morska', 'pieprz'],
    kroki: [
      'Pomidory i mozzarellę pokrój w plastry tej samej grubości.',
      'Układaj naprzemiennie na płaskim talerzu, przekładając listkami bazylii.',
      'Skrop oliwą, posyp solą i pieprzem.',
      'Podawaj w temperaturze pokojowej — zimna mozzarella nie ma smaku.',
    ],
  },
  {
    slug: 'avocado-caprese-details',
    parent: 'caprese-details',
    nazwa: 'Avocado caprese',
    opis: 'Caprese wzbogacone o plastry awokado, bardziej sycące.',
    porcje: 2,
    czasMinut: 10,
    skladniki: ['2 pomidory', '200 g mozzarelli', '1 awokado', 'bazylia', 'oliwa', 'sok z limonki', 'sól'],
    kroki: [
      'Awokado pokrój w plastry i skrop sokiem z limonki, żeby nie ściemniało.',
      'Układaj naprzemiennie z pomidorem i mozzarellą.',
      'Przełóż bazylią, skrop oliwą i dopraw.',
    ],
  },
  {
    slug: 'sun-dried-caprese-details',
    parent: 'caprese-details',
    nazwa: 'Sun dried caprese',
    opis: 'Wersja z pomidorami suszonymi — intensywniejsza i bardziej słona.',
    porcje: 2,
    czasMinut: 10,
    skladniki: ['150 g pomidorów suszonych w oliwie', '200 g mozzarelli', '2 świeże pomidory', 'bazylia', 'oliwa z zalewy', 'pieprz'],
    kroki: [
      'Pomidory suszone odsącz, zachowując oliwę z zalewy.',
      'Układaj naprzemiennie ze świeżymi pomidorami i mozzarellą.',
      'Skrop oliwą z zalewy — ma więcej smaku niż czysta.',
      'Posyp bazylią i pieprzem; soli zwykle nie trzeba.',
    ],
  },
  {
    slug: 'roasted-pepper-caprese-details',
    parent: 'caprese-details',
    nazwa: 'Roasted pepper caprese',
    opis: 'Z pieczoną papryką, która wnosi słodycz i lekko wędzony aromat.',
    porcje: 2,
    czasMinut: 45,
    skladniki: ['2 papryki czerwone', '200 g mozzarelli', 'bazylia', 'oliwa', '1 ząbek czosnku', 'sól, pieprz'],
    kroki: [
      'Papryki piecz w 220°C przez 25 minut, aż skórka zczernieje.',
      'Włóż do miski przykrytej folią na 10 minut, potem obierz ze skórki.',
      'Pokrój w paski i wymieszaj z oliwą i czosnkiem.',
      'Ułóż z mozzarellą i bazylią, dopraw.',
    ],
  },
  {
    slug: 'arugula-caprese-details',
    parent: 'caprese-details',
    nazwa: 'Arugula caprese',
    opis: 'Caprese na rukoli, z octem balsamicznym — pieprzna i wytrawna.',
    porcje: 2,
    czasMinut: 10,
    skladniki: ['100 g rukoli', '200 g mozzarelli', '2 pomidory', '2 łyżki octu balsamicznego', 'oliwa', 'sól, pieprz'],
    kroki: [
      'Rukolę rozłóż na talerzu jako podstawę.',
      'Ułóż plastry pomidora i mozzarelli.',
      'Skrop oliwą i octem balsamicznym.',
      'Dopraw solą i grubo mielonym pieprzem.',
    ],
  },

  // ---------- Cheeseburger ----------
  {
    slug: 'classic-cheesburger-details',
    parent: 'cheeseburger-details',
    nazwa: 'Classic cheeseburger',
    opis: 'Wołowy burger z serem cheddar, sałatą, pomidorem i ogórkiem konserwowym.',
    porcje: 2,
    czasMinut: 25,
    skladniki: ['300 g mielonej wołowiny (20% tłuszczu)', '2 bułki do burgerów', '2 plastry cheddara', 'sałata lodowa', '1 pomidor', 'ogórki konserwowe', 'ketchup, musztarda', 'sól, pieprz'],
    kroki: [
      'Uformuj dwa kotlety, lekko wgnieć środek — inaczej wybrzuszą się przy smażeniu.',
      'Posól bezpośrednio przed smażeniem, nie wcześniej.',
      'Smaż na bardzo gorącej patelni po 3 minuty z każdej strony.',
      'Na minutę przed końcem połóż ser, żeby się roztopił.',
      'Podpiecz bułki i złóż burgera.',
    ],
  },
  {
    slug: 'bacon-cheesburger-details',
    parent: 'cheeseburger-details',
    nazwa: 'Bacon cheeseburger',
    opis: 'Klasyk wzmocniony chrupiącym boczkiem i karmelizowaną cebulą.',
    porcje: 2,
    czasMinut: 35,
    skladniki: ['300 g mielonej wołowiny', '4 plastry boczku', '2 bułki', '2 plastry cheddara', '1 cebula', 'sos majonezowy', 'sól, pieprz'],
    kroki: [
      'Boczek wysmaż na chrupko i odłóż na ręcznik papierowy.',
      'Na tłuszczu z boczku karmelizuj cebulę przez 10 minut.',
      'Usmaż kotlety i stop na nich ser.',
      'Złóż burgera: sos, kotlet z serem, boczek, cebula.',
    ],
  },
  {
    slug: 'mushroom-swiss-cheesburger-details',
    parent: 'cheeseburger-details',
    nazwa: 'Mushroom swiss cheeseburger',
    opis: 'Burger z pieczarkami i serem szwajcarskim, bez sosów pomidorowych.',
    porcje: 2,
    czasMinut: 30,
    skladniki: ['300 g mielonej wołowiny', '200 g pieczarek', '2 plastry sera szwajcarskiego', '2 bułki', '1 łyżka masła', 'tymianek', 'majonez'],
    kroki: [
      'Pieczarki smaż na maśle z tymiankiem, aż się zarumienią.',
      'Usmaż kotlety, na każdy połóż ser.',
      'Nałóż pieczarki na ser, przykryj pokrywką na 30 sekund.',
      'Złóż burgera z majonezem.',
    ],
  },
  {
    slug: 'bbq-cheesburger-details',
    parent: 'cheeseburger-details',
    nazwa: 'BBQ cheeseburger',
    opis: 'Z sosem barbecue i chrupiącą cebulą — słodko-dymny.',
    porcje: 2,
    czasMinut: 30,
    skladniki: ['300 g mielonej wołowiny', '2 bułki', '2 plastry cheddara', '4 łyżki sosu BBQ', 'smażona cebulka', 'sałata', 'sól, pieprz'],
    kroki: [
      'Usmaż kotlety, w ostatniej minucie posmaruj je sosem BBQ.',
      'Nałóż ser i pozwól mu się rozpuścić.',
      'Podpiecz bułki i posmaruj resztą sosu.',
      'Złóż z sałatą i smażoną cebulką na wierzchu.',
    ],
  },
  {
    slug: 'jalapeno-pepper-cheesburger-details',
    parent: 'cheeseburger-details',
    nazwa: 'Jalapeño cheeseburger',
    opis: 'Ostra wersja z papryczkami jalapeño i serem pepper jack.',
    porcje: 2,
    czasMinut: 30,
    skladniki: ['300 g mielonej wołowiny', '2 bułki', '2 plastry sera pepper jack', '2 papryczki jalapeño', 'sos chipotle', 'kolendra', 'sól'],
    kroki: [
      'Jalapeño pokrój w plasterki; usuń pestki, jeśli ma być łagodniej.',
      'Usmaż kotlety i stop na nich ser.',
      'Posmaruj bułki sosem chipotle.',
      'Złóż burgera z papryczkami i świeżą kolendrą.',
    ],
  },

  // ---------- Cod fillet ----------
  {
    slug: 'baked-cod-fllet-with-lemon-and-herbs-details',
    parent: 'cod-fillet-details',
    nazwa: 'Baked cod fillet with lemon and herbs',
    opis: 'Dorsz pieczony z cytryną i ziołami — prosty sposób, który nie przesusza ryby.',
    porcje: 2,
    czasMinut: 30,
    skladniki: ['2 filety z dorsza po 180 g', '1 cytryna', '3 łyżki oliwy', 'natka pietruszki', 'tymianek', 'sól, pieprz'],
    kroki: [
      'Filety osusz i dopraw solą 10 minut przed pieczeniem.',
      'Ułóż w naczyniu, skrop oliwą i sokiem z cytryny.',
      'Na wierzch połóż plasterki cytryny i zioła.',
      'Piecz 15 minut w 200°C — ryba jest gotowa, gdy mięso rozdziela się na płatki.',
    ],
  },
  {
    slug: 'pan-seared-cod-fllet-with-tomato-sauce-details',
    parent: 'cod-fillet-details',
    nazwa: 'Pan seared cod fillet with tomato sauce',
    opis: 'Dorsz smażony na patelni, podany w sosie pomidorowym z kaparami i oliwkami.',
    porcje: 2,
    czasMinut: 35,
    skladniki: ['2 filety z dorsza', '400 g pomidorów z puszki', '2 łyżki kaparów', '50 g oliwek', '2 ząbki czosnku', 'oliwa', 'bazylia'],
    kroki: [
      'Na oliwie zeszklij czosnek, dodaj pomidory i duś 15 minut.',
      'Wmieszaj kapary i oliwki.',
      'Filety osusz i smaż po 3 minuty z każdej strony na mocno rozgrzanej patelni.',
      'Przełóż rybę do sosu i pogotuj razem 2 minuty.',
    ],
  },
  {
    slug: 'grilled-cod-fllet-with-garlic-butter-details',
    parent: 'cod-fillet-details',
    nazwa: 'Grilled cod fillet with garlic butter',
    opis: 'Grillowany dorsz polany masłem czosnkowym z natką.',
    porcje: 2,
    czasMinut: 25,
    skladniki: ['2 filety z dorsza', '80 g masła', '3 ząbki czosnku', 'natka pietruszki', 'sok z cytryny', 'sól, pieprz'],
    kroki: [
      'Rozgrzej patelnię grillową do bardzo wysokiej temperatury.',
      'Filety posmaruj oliwą, grilluj po 3–4 minuty z każdej strony.',
      'Roztop masło z czosnkiem, nie doprowadzając do zbrązowienia.',
      'Polej rybę masłem, dodaj natkę i sok z cytryny.',
    ],
  },
  {
    slug: 'crispy-cod-fllet-with-tartar-sauce-details',
    parent: 'cod-fillet-details',
    nazwa: 'Crispy cod fillet with tartar sauce',
    opis: 'Dorsz w chrupiącej panierce piwnej z sosem tatarskim — brytyjska klasyka.',
    porcje: 2,
    czasMinut: 40,
    skladniki: ['2 filety z dorsza', '150 g mąki', '200 ml zimnego piwa', '1 łyżeczka proszku do pieczenia', 'olej do smażenia', 'majonez', 'ogórki konserwowe', 'kapary'],
    kroki: [
      'Wymieszaj mąkę z proszkiem i zimnym piwem — ciasto ma być rzadkie i lodowate.',
      'Filety osusz, obtocz w mące, potem zanurz w cieście.',
      'Smaż w głębokim oleju 180°C przez 6 minut, aż panierka będzie złota.',
      'Sos: majonez wymieszany z posiekanymi ogórkami i kaparami.',
    ],
  },
  {
    slug: 'steamed-cod-fllet-with-ginger-and-soy-sauce-details',
    parent: 'cod-fillet-details',
    nazwa: 'Steamed cod fillet with ginger and soy sauce',
    opis: 'Dorsz gotowany na parze po kantońsku, z imbirem, sosem sojowym i dymką.',
    porcje: 2,
    czasMinut: 25,
    skladniki: ['2 filety z dorsza', '30 g świeżego imbiru', '3 łyżki sosu sojowego', '2 łyżki oleju sezamowego', 'dymka', '1 łyżeczka cukru'],
    kroki: [
      'Filety ułóż na talerzu, posyp połową imbiru pokrojonego w zapałki.',
      'Gotuj na parze 8 minut.',
      'Odlej wodę, która zebrała się na talerzu — jest gorzka.',
      'Polej sosem sojowym z cukrem, posyp dymką i resztą imbiru.',
      'Rozgrzej olej sezamowy do dymu i polej rybę — to on uwalnia aromat.',
    ],
  },

  // ---------- Confit de canard ----------
  {
    slug: 'traditional-confit-de-canard-details',
    parent: 'confit-de-canard-details',
    nazwa: 'Traditional confit de canard',
    opis: 'Udka kaczki peklowane i gotowane we własnym tłuszczu — gaskońska metoda konserwowania mięsa.',
    porcje: 2,
    czasMinut: 300,
    skladniki: ['2 udka kacze', '500 g smalcu gęsiego lub kaczego', '3 łyżki soli gruboziarnistej', '4 ząbki czosnku', 'tymianek', 'liść laurowy', 'pieprz'],
    kroki: [
      'Udka natrzyj solą z tymiankiem i czosnkiem, odstaw do lodówki na 12 godzin.',
      'Opłucz z soli i dokładnie osusz — resztki soli sprawią, że mięso będzie niejadalnie słone.',
      'Zalej roztopionym smalcem tak, by przykrył mięso.',
      'Gotuj w 90°C przez 3 godziny; tłuszcz nie może wrzeć.',
      'Przed podaniem podsmaż skórę na patelni do chrupkości.',
    ],
  },
  {
    slug: 'confit-duck-leg-with-orange-sauce-details',
    parent: 'confit-de-canard-details',
    nazwa: 'Confit duck leg with orange sauce',
    opis: 'Konfitowane udko z sosem pomarańczowym w stylu à l’orange.',
    porcje: 2,
    czasMinut: 60,
    skladniki: ['2 konfitowane udka kacze', '2 pomarańcze', '50 ml likieru pomarańczowego', '2 łyżki cukru', '200 ml bulionu drobiowego', '1 łyżka octu winnego'],
    kroki: [
      'Skarmelizuj cukier na suchej patelni, zgas octem.',
      'Dodaj sok z pomarańczy, bulion i likier, redukuj o połowę.',
      'Udka podpiecz w 200°C przez 20 minut, aż skóra będzie chrupiąca.',
      'Polej sosem i udekoruj cząstkami pomarańczy.',
    ],
  },
  {
    slug: 'confit-duck-leg-with-cherry-sauce-details',
    parent: 'confit-de-canard-details',
    nazwa: 'Confit duck leg with cherry sauce',
    opis: 'Udko z sosem wiśniowym — kwaśne owoce przełamują tłustość kaczki.',
    porcje: 2,
    czasMinut: 55,
    skladniki: ['2 konfitowane udka kacze', '250 g wiśni bez pestek', '100 ml czerwonego wina', '1 łyżka miodu', '1 gałązka tymianku', 'sól, pieprz'],
    kroki: [
      'Wiśnie duś z winem, miodem i tymiankiem przez 15 minut.',
      'Zblenduj połowę sosu i wróć do garnka, żeby zgęstniał.',
      'Udka podpiecz w 200°C przez 20 minut.',
      'Podawaj polane sosem.',
    ],
  },
  {
    slug: 'confit-duck-leg-with-red-wine-sauce-details',
    parent: 'confit-de-canard-details',
    nazwa: 'Confit duck leg with red wine sauce',
    opis: 'Wersja z wytrawnym sosem na czerwonym winie i szalotce.',
    porcje: 2,
    czasMinut: 60,
    skladniki: ['2 konfitowane udka kacze', '300 ml czerwonego wina', '3 szalotki', '200 ml bulionu', '30 g masła', 'tymianek', 'sól, pieprz'],
    kroki: [
      'Szalotki posiekaj i zeszklij na maśle.',
      'Wlej wino, redukuj do połowy, dodaj bulion i redukuj ponownie.',
      'Zmontuj sos zimnym masłem, zdejmując z ognia.',
      'Udka podpiecz w 200°C przez 20 minut i polej sosem.',
    ],
  },
  {
    slug: 'confit-duck-leg-salad-details',
    parent: 'confit-de-canard-details',
    nazwa: 'Confit duck leg salad',
    opis: 'Ciepła sałatka z rozdrobnionym konfitowanym mięsem, orzechami i winegretem.',
    porcje: 2,
    czasMinut: 30,
    skladniki: ['2 konfitowane udka kacze', '100 g mieszanki sałat', '50 g orzechów włoskich', '1 gruszka', '2 łyżki octu balsamicznego', '4 łyżki oliwy', 'miód'],
    kroki: [
      'Mięso zdejmij z kości i podsmaż na patelni do chrupkości.',
      'Orzechy upraż na sucho.',
      'Winegret: oliwa, ocet balsamiczny i łyżeczka miodu.',
      'Wymieszaj sałatę z gruszką, dodaj ciepłe mięso i orzechy, polej winegretem.',
    ],
  },

  // ---------- Coq au vin ----------
  {
    slug: 'traditional-coq-au-vin-details',
    parent: 'coq-au-vin-details',
    nazwa: 'Traditional coq au vin',
    opis: 'Kurczak duszony w czerwonym winie burgundzkim z boczkiem, cebulkami i pieczarkami.',
    porcje: 4,
    czasMinut: 150,
    skladniki: ['1 kurczak podzielony na części', '750 ml czerwonego wina', '150 g boczku', '250 g pieczarek', '12 cebulek szalotek', '2 łyżki mąki', 'tymianek, liść laurowy'],
    kroki: [
      'Kurczaka zamarynuj w winie z ziołami na noc.',
      'Osusz mięso, obsmaż na tłuszczu z boczku na złoto.',
      'Oprósz mąką, wlej marynatę i duś pod przykryciem 90 minut.',
      'Osobno podsmaż cebulki i pieczarki, dodaj na ostatnie 20 minut.',
      'Sos powinien oblepiać łyżkę — jeśli jest rzadki, odparuj go bez przykrycia.',
    ],
  },
  {
    slug: 'white-coq-au-vin-wine-details',
    parent: 'coq-au-vin-details',
    nazwa: 'Coq au vin blanc',
    opis: 'Alzacka wersja na białym winie i śmietanie — jaśniejsza i delikatniejsza.',
    porcje: 4,
    czasMinut: 100,
    skladniki: ['1 kurczak w kawałkach', '500 ml białego wytrawnego wina', '200 ml śmietany 30%', '250 g pieczarek', '2 szalotki', 'estragon', 'masło'],
    kroki: [
      'Kurczaka obsmaż na maśle, nie przypalając — ma pozostać jasny.',
      'Dodaj szalotki, wlej wino i duś 45 minut.',
      'Dodaj pieczarki i gotuj kolejne 15 minut.',
      'Wlej śmietanę, zagotuj i dopraw estragonem.',
    ],
  },
  {
    slug: 'mushroom-coq-au-vin-details',
    parent: 'coq-au-vin-details',
    nazwa: 'Mushroom coq au vin',
    opis: 'Wariant z potrójną porcją grzybów, w tym suszonymi borowikami.',
    porcje: 4,
    czasMinut: 140,
    skladniki: ['1 kurczak w kawałkach', '600 ml czerwonego wina', '400 g pieczarek', '30 g suszonych borowików', '2 marchewki', 'czosnek', 'tymianek'],
    kroki: [
      'Borowiki namocz w gorącej wodzie na 30 minut, wodę zachowaj.',
      'Obsmaż kurczaka, dodaj warzywa i czosnek.',
      'Wlej wino i wodę z namaczania grzybów, duś 80 minut.',
      'Pieczarki podsmaż osobno i dodaj na końcu.',
    ],
  },
  {
    slug: 'vegetable-coq-au-vin-details',
    parent: 'coq-au-vin-details',
    nazwa: 'Vegetable coq au vin',
    opis: 'Bezmięsna wersja z seitanem lub kalafiorem, duszona w tym samym winnym sosie.',
    porcje: 4,
    czasMinut: 75,
    skladniki: ['1 kalafior', '300 g pieczarek', '500 ml czerwonego wina', '12 cebulek', '2 marchewki', '2 łyżki koncentratu pomidorowego', 'tymianek, oliwa'],
    kroki: [
      'Kalafior podziel na duże różyczki i obsmaż na oliwie.',
      'Dodaj cebulki, marchew i koncentrat, smaż 5 minut.',
      'Wlej wino, duś 35 minut pod przykryciem.',
      'Dodaj pieczarki i gotuj jeszcze 10 minut bez przykrycia.',
    ],
  },
  {
    slug: 'seafood-coq-au-vin-details',
    parent: 'coq-au-vin-details',
    nazwa: 'Seafood coq au vin',
    opis: 'Wariacja z owocami morza duszonymi w białym winie — bliżej matelote niż klasyki.',
    porcje: 4,
    czasMinut: 60,
    skladniki: ['400 g małży', '300 g krewetek', '200 g kalmarów', '500 ml białego wina', '2 szalotki', 'śmietana 30%', 'estragon, masło'],
    kroki: [
      'Małże otwórz w winie z szalotką, wyjmij i przecedź wywar.',
      'Wywar zredukuj o połowę.',
      'Wrzuć krewetki i kalmary, gotuj 3 minuty — dłużej zrobią się gumowate.',
      'Wlej śmietanę, wróć małże, dopraw estragonem.',
    ],
  },

  // ---------- Crepes ----------
  {
    slug: 'suzette-details',
    parent: 'crepes-details',
    nazwa: 'Crêpes Suzette',
    opis: 'Naleśniki w sosie pomarańczowym z Grand Marnier, flambirowane przy stole.',
    porcje: 4,
    czasMinut: 45,
    skladniki: ['200 g mąki', '500 ml mleka', '3 jajka', '2 pomarańcze', '80 g masła', '60 g cukru', '50 ml Grand Marnier'],
    kroki: [
      'Zrób rzadkie ciasto naleśnikowe i odstaw na 30 minut.',
      'Usmaż cienkie naleśniki i złóż w trójkąty.',
      'Na patelni skarmelizuj cukier z masłem, dodaj sok i skórkę z pomarańczy.',
      'Włóż naleśniki do sosu, polej likierem i podpal.',
    ],
  },
  {
    slug: 'chocolate-details',
    parent: 'crepes-details',
    nazwa: 'Chocolate crêpes',
    opis: 'Naleśniki z kakao w cieście, podawane z sosem czekoladowym.',
    porcje: 4,
    czasMinut: 40,
    skladniki: ['180 g mąki', '20 g kakao', '500 ml mleka', '3 jajka', '2 łyżki cukru', '100 g gorzkiej czekolady', '100 ml śmietanki'],
    kroki: [
      'Wymieszaj mąkę z kakao, dodaj jajka i mleko, odstaw na 30 minut.',
      'Smaż cienkie naleśniki na dobrze rozgrzanej patelni.',
      'Czekoladę rozpuść z gorącą śmietanką na gładki sos.',
      'Naleśniki złóż i polej sosem.',
    ],
  },
  {
    slug: 'savory-details',
    parent: 'crepes-details',
    nazwa: 'Savory crêpes',
    opis: 'Wytrawne naleśniki z mąki gryczanej, w bretońskim stylu galette.',
    porcje: 4,
    czasMinut: 50,
    skladniki: ['200 g mąki gryczanej', '400 ml wody', '1 jajko', '150 g szynki', '150 g sera gruyère', '4 jajka do nadzienia', 'masło, sól'],
    kroki: [
      'Wymieszaj mąkę gryczaną z wodą i jajkiem, odstaw na godzinę.',
      'Usmaż naleśnik, na środek wbij jajko i posyp serem.',
      'Dodaj szynkę i podwiń cztery brzegi, zostawiając żółtko odsłonięte.',
      'Przykryj na minutę, aż białko się zetnie.',
    ],
  },
  {
    slug: 'berry-details',
    parent: 'crepes-details',
    nazwa: 'Berry crêpes',
    opis: 'Naleśniki z owocami leśnymi i serkiem mascarpone.',
    porcje: 4,
    czasMinut: 35,
    skladniki: ['200 g mąki', '500 ml mleka', '3 jajka', '300 g owoców leśnych', '250 g mascarpone', '3 łyżki cukru pudru', 'sok z cytryny'],
    kroki: [
      'Przygotuj i odstaw ciasto naleśnikowe na 30 minut.',
      'Owoce podduś z łyżką cukru i sokiem z cytryny przez 5 minut.',
      'Mascarpone utrzyj z resztą cukru pudru.',
      'Naleśniki posmaruj serkiem, nałóż owoce i zwiń.',
    ],
  },
  {
    slug: 'banana-nutella-details',
    parent: 'crepes-details',
    nazwa: 'Banana nutella crêpes',
    opis: 'Najprostsza słodka wersja: krem czekoladowo-orzechowy i plastry banana.',
    porcje: 4,
    czasMinut: 35,
    skladniki: ['200 g mąki', '500 ml mleka', '3 jajka', '4 banany', '200 g kremu czekoladowo-orzechowego', 'masło', 'cukier puder'],
    kroki: [
      'Ciasto naleśnikowe odstaw na 30 minut, potem usmaż cienkie naleśniki.',
      'Ciepły naleśnik posmaruj kremem — na zimnym się nie rozsmaruje.',
      'Ułóż plastry banana i złóż na cztery.',
      'Oprósz cukrem pudrem.',
    ],
  },
];
