import { Przepis } from '../przepis.model';

/** Tagliatelle, tandoori, tosty, tonkatsu, pstrąg, udon,
 *  sałatki, wontony, yakisoba, jogurty. */
export const PACZKA_6: Przepis[] = [
  // ---------- tagliatelle-details ----------
  {
    slug: 'mushroom-tagliatelle-details',
    parent: 'tagliatelle-details',
    nazwa: 'Mushroom tagliatelle',
    opis: 'Wstążki makaronu z grzybami leśnymi w kremowym sosie.',
    porcje: 4,
    czasMinut: 30,
    skladniki: ['400 g tagliatelle', '400 g grzybów leśnych', '200 ml śmietanki 30%', '2 ząbki czosnku', '50 g parmezanu', 'tymianek', 'masło', 'natka'],
    kroki: [
      'Grzyby smaż na maśle na dużym ogniu, aż odparuje woda i się zarumienią.',
      'Dodaj czosnek i tymianek, smaż minutę.',
      'Wlej śmietankę i zredukuj przez 3 minuty.',
      'Wymieszaj z makaronem i wodą z gotowania, posyp parmezanem.',
    ],
  },
  {
    slug: 'spinach-tagliatelle-details',
    parent: 'tagliatelle-details',
    nazwa: 'Spinach tagliatelle',
    opis: 'Zielony makaron ze szpinakiem w cieście, z masłem i parmezanem.',
    porcje: 4,
    czasMinut: 90,
    skladniki: ['300 g mąki 00', '2 jajka', '150 g szpinaku', '80 g masła', '80 g parmezanu', 'gałka muszkatołowa', 'sól'],
    kroki: [
      'Szpinak zblanszuj, odciśnij do sucha i zblenduj z jajkami.',
      'Zagnieć ciasto z mąką, wyrabiaj 10 minut i odstaw na 30 minut.',
      'Rozwałkuj cienko i potnij na wstążki 8 mm.',
      'Gotuj 2 minuty i wymieszaj z masłem oraz parmezanem.',
    ],
  },
  {
    slug: 'shrimp-tagliatelle-details',
    parent: 'tagliatelle-details',
    nazwa: 'Shrimp tagliatelle',
    opis: 'Z krewetkami, pomidorkami i chili, na oliwie.',
    porcje: 4,
    czasMinut: 30,
    skladniki: ['400 g tagliatelle', '400 g krewetek', '250 g pomidorków koktajlowych', '3 ząbki czosnku', 'chili', '100 ml białego wina', 'natka', 'oliwa'],
    kroki: [
      'Krewetki podsmaż 90 sekund z każdej strony i wyjmij.',
      'Na tej samej patelni podsmaż czosnek z chili i pomidorkami.',
      'Wlej wino i zredukuj o połowę.',
      'Wróć krewetki, dodaj makaron i wodę z gotowania.',
    ],
  },
  {
    slug: 'chicken-tagliatelle-details',
    parent: 'tagliatelle-details',
    nazwa: 'Chicken tagliatelle',
    opis: 'Z kurczakiem i pieczarkami w sosie śmietanowym.',
    porcje: 4,
    czasMinut: 35,
    skladniki: ['400 g tagliatelle', '500 g piersi z kurczaka', '250 g pieczarek', '200 ml śmietanki', '1 cebula', 'parmezan', 'tymianek', 'masło'],
    kroki: [
      'Kurczaka pokrój w paski i obsmaż na złoto, odłóż.',
      'Podsmaż cebulę i pieczarki.',
      'Wlej śmietankę, zredukuj, wróć kurczaka.',
      'Wymieszaj z makaronem i posyp parmezanem.',
    ],
  },
  {
    slug: 'tomato-sauce-tagliatelle-details',
    parent: 'tagliatelle-details',
    nazwa: 'Tagliatelle al pomodoro',
    opis: 'Prosty sos pomidorowy z bazylią i masłem — nic więcej nie potrzeba.',
    porcje: 4,
    czasMinut: 45,
    skladniki: ['400 g tagliatelle', '800 g pomidorów pelati', '1 cebula', '80 g masła', 'bazylia', 'parmezan', 'sól'],
    kroki: [
      'Cebulę przekrój na pół i włóż do garnka z pomidorami i masłem.',
      'Gotuj 40 minut na małym ogniu, od czasu do czasu mieszając.',
      'Wyjmij cebulę i rozgnieć pomidory.',
      'Wymieszaj z makaronem, dodaj bazylię i parmezan.',
    ],
  },

  // ---------- tandoori-details ----------
  {
    slug: 'chicken-tandoori-details',
    parent: 'tandoori-details',
    nazwa: 'Chicken tandoori',
    opis: 'Kurczak marynowany w jogurcie z przyprawami, pieczony w bardzo wysokiej temperaturze.',
    porcje: 4,
    czasMinut: 300,
    skladniki: ['1 kg podudzi z kurczaka', '300 g jogurtu naturalnego', '2 łyżki pasty tandoori masala', '20 g imbiru', '4 ząbki czosnku', 'sok z cytryny', 'papryka słodka', 'garam masala'],
    kroki: [
      'Mięso ponacinaj głęboko do kości — marynata musi wejść do środka.',
      'Pierwsza marynata: sok z cytryny, sól, papryka; odstaw na 30 minut.',
      'Druga marynata: jogurt z imbirem, czosnkiem i przyprawami; odstaw na 4 godziny.',
      'Piecz 25 minut w 250°C na kratce, żeby nadmiar marynaty skapywał.',
      'Ostatnie 3 minuty pod grillem, dla przypalonych brzegów.',
    ],
  },
  {
    slug: 'lamb-tandoori-details',
    parent: 'tandoori-details',
    nazwa: 'Lamb tandoori',
    opis: 'Jagnięcina w intensywniejszej marynacie, z dodatkiem gorczycy.',
    porcje: 4,
    czasMinut: 360,
    skladniki: ['1 kg udźca jagnięcego', '300 g jogurtu', 'tandoori masala', 'olej gorczycowy', 'imbir', 'czosnek', 'garam masala', 'sok z cytryny'],
    kroki: [
      'Mięso pokrój w duże kostki i ponacinaj.',
      'Marynuj w jogurcie z przyprawami przez 6 godzin.',
      'Nadziewaj na szpadki, przekładając cebulą.',
      'Piecz 20 minut w 250°C, obracając raz.',
    ],
  },
  {
    slug: 'fish-tandoori-details',
    parent: 'tandoori-details',
    nazwa: 'Fish tandoori',
    opis: 'Ryba w krótkiej marynacie — dłuższa rozłożyłaby delikatne mięso.',
    porcje: 4,
    czasMinut: 60,
    skladniki: ['600 g filetów z ryby', '200 g jogurtu', 'tandoori masala', 'mąka z ciecierzycy', 'sok z limonki', 'imbir', 'czosnek', 'kolendra'],
    kroki: [
      'Marynuj rybę maksymalnie 30 minut — kwas z jogurtu szybko ją „gotuje".',
      'Dodaj łyżkę mąki z ciecierzycy, żeby marynata się trzymała.',
      'Piecz 12 minut w 240°C.',
      'Podawaj z limonką i kolendrą.',
    ],
  },
  {
    slug: 'paneer-tandoori-details',
    parent: 'tandoori-details',
    nazwa: 'Paneer tandoori',
    opis: 'Indyjski ser paneer z papryką i cebulą, pieczony na szpadkach.',
    porcje: 4,
    czasMinut: 90,
    skladniki: ['500 g paneeru', '200 g jogurtu', 'tandoori masala', '2 papryki', '1 cebula', 'mąka z ciecierzycy', 'imbir', 'czosnek', 'chaat masala'],
    kroki: [
      'Paneer pokrój w kostkę 3 cm.',
      'Marynuj w gęstym jogurcie z przyprawami przez godzinę.',
      'Nadziewaj na szpadki na przemian z papryką i cebulą.',
      'Piecz 15 minut w 240°C i posyp chaat masalą.',
    ],
  },
  {
    slug: 'mixed-grill-tandoori-details',
    parent: 'tandoori-details',
    nazwa: 'Mixed grill tandoori',
    opis: 'Półmisek z kurczakiem, jagnięciną i paneerem — każde marynowane osobno.',
    porcje: 6,
    czasMinut: 360,
    skladniki: ['500 g kurczaka', '400 g jagnięciny', '300 g paneeru', 'jogurt', 'tandoori masala', 'garam masala', 'cebula', 'limonka'],
    kroki: [
      'Każdy składnik marynuj osobno — mają różne czasy.',
      'Jagnięcinę 6 godzin, kurczaka 4, paneer godzinę.',
      'Piecz kolejno, zaczynając od jagnięciny.',
      'Podawaj na wspólnym półmisku z cebulą i limonką.',
    ],
  },

  // ---------- toasts-details ----------
  {
    slug: 'avocado-details',
    parent: 'toasts-details',
    nazwa: 'Avocado toast',
    opis: 'Rozgniecione awokado na chlebie na zakwasie, z chili i limonką.',
    porcje: 2,
    czasMinut: 10,
    skladniki: ['2 kromki chleba na zakwasie', '2 awokado', 'sok z limonki', 'płatki chili', 'sól morska', 'oliwa', 'jajko w koszulce'],
    kroki: [
      'Kromki opiecz do chrupkości.',
      'Awokado rozgnieć widelcem z sokiem z limonki i solą — nie blenduj.',
      'Rozsmaruj grubą warstwę.',
      'Skrop oliwą, posyp chili i połóż jajko w koszulce.',
    ],
  },
  {
    slug: 'egg-in-a-hole-details',
    parent: 'toasts-details',
    nazwa: 'Egg in a hole',
    opis: 'Jajko usmażone w wyciętym otworze w kromce chleba.',
    porcje: 2,
    czasMinut: 12,
    skladniki: ['2 grube kromki chleba', '2 jajka', '30 g masła', 'sól, pieprz', 'szczypiorek'],
    kroki: [
      'Szklanką wytnij otwór na środku kromki.',
      'Rozgrzej masło i połóż kromkę na patelni.',
      'Wbij jajko w otwór i smaż 3 minuty.',
      'Obróć ostrożnie i smaż jeszcze minutę — żółtko ma zostać płynne.',
    ],
  },
  {
    slug: 'cheese-and-tomato-details',
    parent: 'toasts-details',
    nazwa: 'Cheese and tomato toast',
    opis: 'Zapiekana kromka z serem i pomidorem, z oregano.',
    porcje: 2,
    czasMinut: 15,
    skladniki: ['4 kromki chleba', '150 g sera żółtego', '2 pomidory', 'oregano', 'masło', 'pieprz'],
    kroki: [
      'Kromki posmaruj masłem.',
      'Pomidory pokrój w plastry i osusz na ręczniku.',
      'Ułóż ser, pomidory i znowu ser — ser od spodu chroni chleb przed rozmoczeniem.',
      'Zapiekaj 8 minut w 200°C i posyp oregano.',
    ],
  },
  {
    slug: 'french-details',
    parent: 'toasts-details',
    nazwa: 'French toast',
    opis: 'Tosty francuskie — chleb nasączony masą jajeczną i usmażony na maśle.',
    porcje: 2,
    czasMinut: 20,
    skladniki: ['4 kromki chałki', '2 jajka', '150 ml mleka', '1 łyżka cukru', 'cynamon', 'wanilia', 'masło', 'syrop klonowy'],
    kroki: [
      'Roztrzep jajka z mlekiem, cukrem, cynamonem i wanilią.',
      'Kromki mocz po 20 sekund z każdej strony — dłużej rozpadną się na patelni.',
      'Smaż na maśle po 3 minuty z każdej strony.',
      'Podawaj z syropem klonowym.',
    ],
  },
  {
    slug: 'ham-and-cheese-details',
    parent: 'toasts-details',
    nazwa: 'Ham and cheese toast',
    opis: 'Klasyczny tost z szynką i serem, zapiekany w opiekaczu.',
    porcje: 2,
    czasMinut: 12,
    skladniki: ['4 kromki chleba tostowego', '4 plastry szynki', '100 g sera', 'masło', 'musztarda'],
    kroki: [
      'Posmaruj kromki masłem od zewnątrz i musztardą od środka.',
      'Ułóż szynkę i ser.',
      'Zapiekaj w opiekaczu 4 minuty.',
      'Odstaw minutę przed przekrojeniem, żeby ser nie wypłynął.',
    ],
  },

  // ---------- tonkatsu-details ----------
  {
    slug: 'katsu-don-details',
    parent: 'tonkatsu-details',
    nazwa: 'Katsu don',
    opis: 'Kotlet tonkatsu duszony z cebulą i jajkiem, podany na ryżu.',
    porcje: 2,
    czasMinut: 40,
    skladniki: ['2 kotlety tonkatsu', '2 jajka', '1 cebula', '200 ml dashi', '3 łyżki sosu sojowego', '2 łyżki mirin', 'ryż', 'dymka'],
    kroki: [
      'Usmażony kotlet pokrój w paski.',
      'W płaskim rondlu zagotuj dashi z sosem sojowym i mirin.',
      'Dodaj cebulę, gotuj 3 minuty, ułóż kotlet.',
      'Zalej roztrzepanym jajkiem i przykryj na minutę.',
      'Zsuń na ryż i posyp dymką.',
    ],
  },
  {
    slug: 'chicken-tonkatsu-details',
    parent: 'tonkatsu-details',
    nazwa: 'Chicken katsu',
    opis: 'Wersja z kurczakiem — lżejsza i szybsza od wieprzowej.',
    porcje: 2,
    czasMinut: 30,
    skladniki: ['2 piersi z kurczaka', 'mąka', '2 jajka', '150 g panko', 'olej', 'kapusta', 'sos tonkatsu'],
    kroki: [
      'Piersi rozbij do równej grubości 1,5 cm.',
      'Panieruj w mące, jajku i panko.',
      'Smaż w oleju 170°C przez 5 minut.',
      'Pokrój w paski i podawaj z szatkowaną kapustą.',
    ],
  },
  {
    slug: 'pork-tonkatsu-details',
    parent: 'tonkatsu-details',
    nazwa: 'Pork tonkatsu',
    opis: 'Oryginalna wersja ze schabu, z grubą warstwą panko.',
    porcje: 2,
    czasMinut: 35,
    skladniki: ['2 kotlety schabowe 2 cm', 'mąka', '2 jajka', '200 g panko', 'olej', 'kapusta', 'sos tonkatsu', 'musztarda karashi'],
    kroki: [
      'Natnij tłuszcz po brzegach, żeby kotlet się nie wygiął.',
      'Panieruj, dociskając panko dłonią.',
      'Smaż 7 minut w oleju 170°C — grubszy kotlet potrzebuje niższej temperatury i dłuższego czasu.',
      'Odsącz na kratce, nie na papierze, żeby panierka została chrupiąca.',
    ],
  },
  {
    slug: 'shrimp-tonkatsu-details',
    parent: 'tonkatsu-details',
    nazwa: 'Ebi katsu',
    opis: 'Krewetkowe kotleciki w panko, z sosem tatarskim.',
    porcje: 2,
    czasMinut: 35,
    skladniki: ['400 g krewetek', 'skrobia', '2 jajka', 'panko', 'majonez japoński', 'ogórek konserwowy', 'olej', 'cytryna'],
    kroki: [
      'Połowę krewetek zblenduj na pastę, drugą posiekaj grubo.',
      'Wymieszaj ze skrobią i uformuj kotleciki.',
      'Panieruj w jajku i panko.',
      'Smaż 4 minuty i podawaj z sosem tatarskim.',
    ],
  },
  {
    slug: 'vegetarian-tonkatsu-details',
    parent: 'tonkatsu-details',
    nazwa: 'Vegetarian katsu',
    opis: 'Z bakłażana lub tofu, w tej samej panierce panko.',
    porcje: 2,
    czasMinut: 35,
    skladniki: ['1 bakłażan', '200 g tofu twardego', 'mąka', '2 jajka', 'panko', 'olej', 'sos tonkatsu', 'kapusta'],
    kroki: [
      'Bakłażan pokrój w grube plastry, posól i odstaw na 20 minut, potem osusz.',
      'Tofu odciśnij pod obciążeniem.',
      'Panieruj w mące, jajku i panko.',
      'Smaż po 4 minuty z każdej strony.',
    ],
  },

  // ---------- trout-details ----------
  {
    slug: 'rainbow-trout-details',
    parent: 'trout-details',
    nazwa: 'Rainbow trout',
    opis: 'Pstrąg tęczowy pieczony w całości z cytryną i tymiankiem.',
    porcje: 2,
    czasMinut: 35,
    skladniki: ['2 pstrągi', '1 cytryna', 'tymianek', '4 ząbki czosnku', 'masło', 'oliwa', 'sól, pieprz'],
    kroki: [
      'Ryby oczyść i osusz, natnij skórę po bokach.',
      'Do brzucha włóż cytrynę, czosnek i tymianek.',
      'Piecz 20 minut w 200°C.',
      'Polej roztopionym masłem przed podaniem.',
    ],
  },
  {
    slug: 'brown-trout-details',
    parent: 'trout-details',
    nazwa: 'Brown trout',
    opis: 'Pstrąg potokowy smażony na maśle po młynarsku — meunière.',
    porcje: 2,
    czasMinut: 25,
    skladniki: ['2 pstrągi', 'mąka', '100 g masła', '1 cytryna', 'natka pietruszki', 'sól, pieprz'],
    kroki: [
      'Ryby osusz i obtocz w mące, strząsając nadmiar.',
      'Smaż na maśle po 5 minut z każdej strony.',
      'Wyjmij ryby, a masło przesmaż na orzechowo.',
      'Dodaj sok z cytryny i natkę, polej ryby.',
    ],
  },
  {
    slug: 'brook-trout-details',
    parent: 'trout-details',
    nazwa: 'Brook trout',
    opis: 'Pstrąg źródlany z grilla, w folii z warzywami.',
    porcje: 2,
    czasMinut: 40,
    skladniki: ['2 pstrągi', '1 cukinia', '1 marchewka', 'koperek', 'białe wino', 'masło', 'cytryna'],
    kroki: [
      'Warzywa pokrój w cienkie słupki.',
      'Ułóż rybę na folii, obłóż warzywami, dodaj masło i wino.',
      'Szczelnie zawiń — para w środku ugotuje rybę.',
      'Piecz 20 minut w 200°C i otwórz przy stole.',
    ],
  },
  {
    slug: 'lake-trout-details',
    parent: 'trout-details',
    nazwa: 'Lake trout',
    opis: 'Pstrąg jeziorowy wędzony na gorąco, z jałowcem.',
    porcje: 4,
    czasMinut: 180,
    skladniki: ['2 pstrągi', '100 g soli', '50 g cukru', 'jałowiec', 'liść laurowy', 'zrębki olchowe'],
    kroki: [
      'Ryby zapekluj w solance z cukrem i jałowcem na 2 godziny.',
      'Opłucz i osusz przez godzinę — skóra musi być sucha, inaczej dym nie przywrze.',
      'Wędź w 80°C przez 45 minut na zrębkach olchowych.',
      'Podawaj na ciepło lub zimno.',
    ],
  },
  {
    slug: 'cutthroat-trout-details',
    parent: 'trout-details',
    nazwa: 'Cutthroat trout',
    opis: 'Pstrąg pieczony w skorupie z soli, która zatrzymuje całą wilgoć.',
    porcje: 2,
    czasMinut: 50,
    skladniki: ['2 pstrągi', '1,5 kg soli gruboziarnistej', '2 białka', 'zioła', 'cytryna', 'oliwa'],
    kroki: [
      'Sól wymieszaj z białkami na wilgotną masę.',
      'Na blasze zrób warstwę soli, ułóż ryby wypełnione ziołami.',
      'Przykryj całkowicie resztą soli i dociśnij.',
      'Piecz 25 minut w 200°C.',
      'Rozbij skorupę przy stole i zdejmij skórę razem z solą.',
    ],
  },

  // ---------- udon-details ----------
  {
    slug: 'tofu-udon-details',
    parent: 'udon-details',
    nazwa: 'Tofu udon',
    opis: 'Grube kluski pszenne w bulionie dashi z tofu i dymką.',
    porcje: 2,
    czasMinut: 25,
    skladniki: ['400 g makaronu udon', '800 ml dashi', '3 łyżki sosu sojowego', '2 łyżki mirin', '200 g tofu', 'dymka', 'shichimi togarashi'],
    kroki: [
      'Zagotuj dashi z sosem sojowym i mirin.',
      'Makaron udon podgrzej we wrzątku 2 minuty i odcedź.',
      'Tofu pokrój w kostkę i podgrzej w bulionie.',
      'Zalej makaron bulionem, posyp dymką i shichimi.',
    ],
  },
  {
    slug: 'beef-udon-details',
    parent: 'udon-details',
    nazwa: 'Beef udon',
    opis: 'Niku udon z cienką wołowiną duszoną w słodko-słonym sosie.',
    porcje: 2,
    czasMinut: 30,
    skladniki: ['400 g udon', '250 g cienko krojonej wołowiny', '800 ml dashi', 'sos sojowy', 'mirin', 'cukier', '1 cebula', 'dymka'],
    kroki: [
      'Wołowinę duś z cebulą w sosie sojowym, mirin i cukrze przez 5 minut.',
      'Osobno zagotuj bulion dashi.',
      'Makaron podgrzej i przełóż do misek.',
      'Zalej bulionem i ułóż mięso na wierzchu.',
    ],
  },
  {
    slug: 'chicken-udon-details',
    parent: 'udon-details',
    nazwa: 'Chicken udon',
    opis: 'Z kurczakiem i porem w klarownym bulionie.',
    porcje: 2,
    czasMinut: 30,
    skladniki: ['400 g udon', '300 g udek z kurczaka', '800 ml dashi', 'sos sojowy', 'mirin', '1 por', 'imbir', 'dymka'],
    kroki: [
      'Kurczaka pokrój i podsmaż na patelni skórą do dołu.',
      'Zagotuj dashi z sosem sojowym, mirin i imbirem.',
      'Dodaj kurczaka i por, gotuj 8 minut.',
      'Zalej makaron i posyp dymką.',
    ],
  },
  {
    slug: 'shrimp-udon-details',
    parent: 'udon-details',
    nazwa: 'Shrimp tempura udon',
    opis: 'Z krewetkami w tempurze, kładzionymi na wierzch tuż przed podaniem.',
    porcje: 2,
    czasMinut: 40,
    skladniki: ['400 g udon', '8 krewetek', 'mąka tempura', 'lodowata woda', '800 ml dashi', 'sos sojowy', 'mirin', 'dymka'],
    kroki: [
      'Ciasto tempura wymieszaj lodowatą wodą, zostawiając grudki.',
      'Krewetki zanurz i smaż 2 minuty w oleju 180°C.',
      'Makaron zalej gorącym bulionem.',
      'Tempurę połóż na wierzchu w ostatniej chwili, żeby została chrupiąca.',
    ],
  },
  {
    slug: 'vegetable-udon-details',
    parent: 'udon-details',
    nazwa: 'Vegetable udon',
    opis: 'Smażone udon z warzywami — yaki udon, bez bulionu.',
    porcje: 2,
    czasMinut: 25,
    skladniki: ['400 g udon', '1 marchewka', '150 g kapusty', '100 g grzybów shiitake', 'papryka', 'sos sojowy', 'sos ostrygowy', 'olej sezamowy'],
    kroki: [
      'Warzywa pokrój w paski i smaż na woku 4 minuty.',
      'Dodaj makaron udon i smaż, rozdzielając kluski.',
      'Wlej sos sojowy z ostrygowym.',
      'Skrop olejem sezamowym na koniec.',
    ],
  },

  // ---------- vegetable-salad-details ----------
  {
    slug: 'caesar-salad-details',
    parent: 'vegetable-salad-details',
    nazwa: 'Caesar salad',
    opis: 'Sałata rzymska z grzankami, parmezanem i sosem na anchois i żółtkach.',
    porcje: 4,
    czasMinut: 30,
    skladniki: ['2 sałaty rzymskie', '4 filety anchois', '2 żółtka', '1 ząbek czosnku', '150 ml oliwy', 'sok z cytryny', 'musztarda dijon', '100 g parmezanu', 'grzanki'],
    kroki: [
      'Anchois i czosnek utrzyj w moździerzu na pastę.',
      'Dodaj żółtka i musztardę, wkraplaj oliwę jak przy majonezie.',
      'Dopraw sokiem z cytryny i parmezanem.',
      'Sałatę porwij ręcznie i wymieszaj z sosem tuż przed podaniem.',
      'Dodaj grzanki i wiórki parmezanu.',
    ],
  },
  {
    slug: 'caprese-salad-details',
    parent: 'vegetable-salad-details',
    nazwa: 'Caprese salad',
    opis: 'Pomidor, mozzarella i bazylia — sałatka z Capri.',
    porcje: 2,
    czasMinut: 10,
    skladniki: ['3 pomidory', '250 g mozzarelli', 'bazylia', 'oliwa extra vergine', 'sól morska', 'pieprz'],
    kroki: [
      'Pokrój pomidory i mozzarellę w plastry równej grubości.',
      'Układaj naprzemiennie z bazylią.',
      'Skrop oliwą, posól i popieprz.',
      'Podawaj w temperaturze pokojowej.',
    ],
  },
  {
    slug: 'cobb-salad-details',
    parent: 'vegetable-salad-details',
    nazwa: 'Cobb salad',
    opis: 'Amerykańska sałatka układana w rzędach: kurczak, bekon, jajko, awokado, ser pleśniowy.',
    porcje: 4,
    czasMinut: 35,
    skladniki: ['1 sałata lodowa', '300 g grillowanego kurczaka', '6 plastrów bekonu', '4 jajka', '2 awokado', '150 g sera pleśniowego', 'pomidorki', 'winegret'],
    kroki: [
      'Wszystkie składniki pokrój w równą kostkę.',
      'Bekon wysmaż na chrupko i pokrusz.',
      'Na sałacie ułóż składniki w osobnych, równoległych pasach.',
      'Winegret podaj osobno i wymieszaj dopiero przy stole.',
    ],
  },
  {
    slug: 'greek-salad-details',
    parent: 'vegetable-salad-details',
    nazwa: 'Greek salad',
    opis: 'Pomidory, ogórek, cebula, oliwki i feta w jednym kawałku.',
    porcje: 4,
    czasMinut: 15,
    skladniki: ['4 pomidory', '1 ogórek', '1 czerwona cebula', '150 g oliwek', '200 g fety', 'oliwa', 'oregano', 'sól'],
    kroki: [
      'Warzywa pokrój w duże kawałki.',
      'Wymieszaj z oliwkami i posól.',
      'Fetę połóż na wierzchu w całości — tak podaje się ją w Grecji.',
      'Skrop oliwą i posyp oregano.',
    ],
  },
  {
    slug: 'waldorf-salad-details',
    parent: 'vegetable-salad-details',
    nazwa: 'Waldorf salad',
    opis: 'Jabłko, seler naciowy i orzechy włoskie w sosie majonezowym.',
    porcje: 4,
    czasMinut: 20,
    skladniki: ['3 jabłka', '3 łodygi selera naciowego', '100 g orzechów włoskich', '100 g winogron', 'majonez', 'jogurt', 'sok z cytryny', 'sałata'],
    kroki: [
      'Jabłka pokrój w kostkę i skrop sokiem z cytryny, żeby nie ściemniały.',
      'Seler pokrój w cienkie plasterki.',
      'Orzechy upraż i posiekaj.',
      'Wymieszaj z sosem z majonezu i jogurtu, podawaj na liściach sałaty.',
    ],
  },

  // ---------- wonton-details ----------
  {
    slug: 'hong-kong-details',
    parent: 'wonton-details',
    nazwa: 'Hong Kong wonton soup',
    opis: 'Delikatne wontony z krewetkami w klarownym bulionie z makaronem jajecznym.',
    porcje: 4,
    czasMinut: 60,
    skladniki: ['30 płatów na wontony', '250 g krewetek', '150 g mielonej wieprzowiny', 'olej sezamowy', 'biały pieprz', '1,5 l bulionu drobiowego', 'makaron jajeczny', 'dymka'],
    kroki: [
      'Krewetki posiekaj grubo, wymieszaj z mięsem i przyprawami.',
      'Nałóż łyżeczkę farszu i zbierz płat w sakiewkę, zwilżając brzegi.',
      'Gotuj wontony 4 minuty w osobnym garnku — mączna woda zmętniłaby bulion.',
      'Przełóż do misek z makaronem i zalej gorącym bulionem.',
    ],
  },
  {
    slug: 'sichuan-details',
    parent: 'wonton-details',
    nazwa: 'Sichuan wontons',
    opis: 'Wontony w ostrym sosie chili z pieprzem syczuańskim, bez bulionu.',
    porcje: 4,
    czasMinut: 50,
    skladniki: ['30 płatów na wontony', '300 g mielonej wieprzowiny', 'imbir', 'dymka', 'olej chili', 'pieprz syczuański', 'sos sojowy', 'ocet czarny', 'czosnek'],
    kroki: [
      'Farsz z mięsa, imbiru i dymki wyrabiaj w jedną stronę, aż się zwiąże.',
      'Zawiń wontony i ugotuj 4 minuty.',
      'Sos: olej chili, sos sojowy, ocet czarny, roztarty czosnek i mielony pieprz syczuański.',
      'Polej odsączone wontony sosem i posyp dymką.',
    ],
  },
  {
    slug: 'fried-details',
    parent: 'wonton-details',
    nazwa: 'Fried wontons',
    opis: 'Smażone na chrupko, podawane z sosem słodko-kwaśnym.',
    porcje: 4,
    czasMinut: 45,
    skladniki: ['30 płatów na wontony', '300 g mielonej wieprzowiny', 'kapusta', 'imbir', 'olej do smażenia', 'sos słodko-kwaśny', 'sos sojowy'],
    kroki: [
      'Przygotuj farsz i zawiń wontony, dokładnie zlepiając brzegi.',
      'Smaż w oleju 170°C przez 3 minuty, po kilka sztuk naraz.',
      'Odsącz na kratce.',
      'Podawaj z sosem słodko-kwaśnym.',
    ],
  },
  {
    slug: 'thai-style-details',
    parent: 'wonton-details',
    nazwa: 'Thai style wontons',
    opis: 'Z kolendrą, sosem rybnym i chili w farszu, podawane z sosem tamaryndowym.',
    porcje: 4,
    czasMinut: 50,
    skladniki: ['30 płatów na wontony', '300 g mielonej wieprzowiny', 'kolendra', 'sos rybny', 'chili', 'czosnek', 'pasta tamaryndowa', 'cukier palmowy', 'limonka'],
    kroki: [
      'Farsz doprawiony sosem rybnym, kolendrą i chili wyrabiaj do zwięzłości.',
      'Zawiń wontony i ugotuj lub usmaż.',
      'Sos: tamaryndowiec, cukier palmowy i sok z limonki.',
      'Podawaj z kolendrą i posiekanym chili.',
    ],
  },

  // ---------- yakisoba-details ----------
  {
    slug: 'chicken-yakisoba-details',
    parent: 'yakisoba-details',
    nazwa: 'Chicken yakisoba',
    opis: 'Smażony makaron pszenny z kurczakiem i kapustą, w słodko-słonym sosie.',
    porcje: 4,
    czasMinut: 30,
    skladniki: ['400 g makaronu yakisoba', '400 g kurczaka', '200 g kapusty', '1 marchewka', 'sos yakisoba', 'aonori', 'beni shoga', 'olej'],
    kroki: [
      'Makaron rozluźnij pod ciepłą wodą, żeby się nie sklejał.',
      'Kurczaka usmaż na woku, dodaj warzywa i smaż 3 minuty.',
      'Wrzuć makaron i wlej sos yakisoba.',
      'Smaż na dużym ogniu 2 minuty, posyp aonori i imbirem beni shoga.',
    ],
  },
  {
    slug: 'beef-yakisoba-details',
    parent: 'yakisoba-details',
    nazwa: 'Beef yakisoba',
    opis: 'Z cienko krojoną wołowiną i papryką.',
    porcje: 4,
    czasMinut: 30,
    skladniki: ['400 g makaronu yakisoba', '400 g wołowiny', '1 papryka', '200 g kapusty', 'cebula', 'sos yakisoba', 'sos sojowy', 'olej'],
    kroki: [
      'Wołowinę pokrój bardzo cienko i usmaż na dużym ogniu 2 minuty.',
      'Odłóż, na tym samym woku podsmaż warzywa.',
      'Dodaj makaron i sos, wymieszaj.',
      'Wróć mięso na ostatnie 30 sekund.',
    ],
  },
  {
    slug: 'vegetarian-yakisoba-details',
    parent: 'yakisoba-details',
    nazwa: 'Vegetarian yakisoba',
    opis: 'Z tofu, kapustą, marchewką i grzybami shiitake.',
    porcje: 4,
    czasMinut: 30,
    skladniki: ['400 g makaronu yakisoba', '250 g tofu', '200 g kapusty', '1 marchewka', '100 g shiitake', 'sos yakisoba', 'olej sezamowy', 'sezam'],
    kroki: [
      'Tofu odciśnij i podsmaż do zarumienienia, odłóż.',
      'Smaż warzywa na dużym ogniu 4 minuty.',
      'Dodaj makaron i sos.',
      'Wróć tofu, skrop olejem sezamowym i posyp sezamem.',
    ],
  },
  {
    slug: 'shrimp-yakisoba-details',
    parent: 'yakisoba-details',
    nazwa: 'Shrimp yakisoba',
    opis: 'Z krewetkami dodawanymi na samym końcu, żeby nie stwardniały.',
    porcje: 4,
    czasMinut: 25,
    skladniki: ['400 g makaronu yakisoba', '400 g krewetek', '200 g kapusty', 'kiełki fasoli', 'dymka', 'sos yakisoba', 'imbir', 'olej'],
    kroki: [
      'Krewetki usmaż 90 sekund i wyjmij.',
      'Podsmaż kapustę i imbir.',
      'Dodaj makaron z sosem i smaż 2 minuty.',
      'Wróć krewetki i kiełki na ostatnie 30 sekund.',
    ],
  },
  {
    slug: 'pork-yakisoba-details',
    parent: 'yakisoba-details',
    nazwa: 'Pork yakisoba',
    opis: 'Najpopularniejsza wersja — z cienkim boczkiem wieprzowym.',
    porcje: 4,
    czasMinut: 30,
    skladniki: ['400 g makaronu yakisoba', '300 g boczku w cienkich plastrach', '200 g kapusty', '1 marchewka', 'cebula', 'sos yakisoba', 'aonori', 'majonez japoński'],
    kroki: [
      'Boczek podsmaż, aż wytopi się tłuszcz — na nim smaż resztę.',
      'Dodaj warzywa i smaż 3 minuty.',
      'Wrzuć makaron i sos, mieszaj 2 minuty.',
      'Podawaj z aonori i zygzakiem majonezu.',
    ],
  },

  // ---------- yoghurt-details ----------
  {
    slug: 'greek-details',
    parent: 'yoghurt-details',
    nazwa: 'Greek yoghurt bowl',
    opis: 'Gęsty jogurt grecki z miodem, orzechami i owocami.',
    porcje: 2,
    czasMinut: 10,
    skladniki: ['400 g jogurtu greckiego', '3 łyżki miodu', '50 g orzechów włoskich', 'świeże owoce', 'cynamon', 'nasiona chia'],
    kroki: [
      'Jogurt przełóż do miski i wygładź łyżką.',
      'Orzechy upraż na suchej patelni i posiekaj.',
      'Ułóż owoce, posyp orzechami i nasionami chia.',
      'Polej miodem i posyp cynamonem.',
    ],
  },
  {
    slug: 'priobiotic-details',
    parent: 'yoghurt-details',
    nazwa: 'Probiotic yoghurt',
    opis: 'Domowy jogurt z żywymi kulturami bakterii, fermentowany 8 godzin.',
    porcje: 6,
    czasMinut: 600,
    skladniki: ['1 l mleka pełnotłustego', '100 g jogurtu naturalnego z żywymi kulturami', 'termometr'],
    kroki: [
      'Mleko podgrzej do 85°C i utrzymaj 10 minut — to denaturuje białka i daje gęstszy jogurt.',
      'Ostudź do 45°C; wyżej bakterie giną.',
      'Wmieszaj jogurt-starter.',
      'Utrzymuj 42–45°C przez 8 godzin.',
      'Schłodź w lodówce przez 4 godziny przed podaniem.',
    ],
  },
  {
    slug: 'plant-based-details',
    parent: 'yoghurt-details',
    nazwa: 'Plant based yoghurt',
    opis: 'Jogurt na mleku kokosowym z kulturami wegańskimi.',
    porcje: 4,
    czasMinut: 720,
    skladniki: ['800 ml mleka kokosowego', 'wegańskie kultury bakterii', '2 łyżki skrobi tapiokowej', 'syrop klonowy'],
    kroki: [
      'Mleko kokosowe podgrzej ze skrobią, mieszając, aż lekko zgęstnieje.',
      'Ostudź do 40°C.',
      'Wmieszaj kultury bakterii.',
      'Fermentuj 12 godzin w cieple, potem schłodź.',
    ],
  },
  {
    slug: 'low-fat-details',
    parent: 'yoghurt-details',
    nazwa: 'Low fat yoghurt',
    opis: 'Jogurt na mleku odtłuszczonym, zagęszczany mlekiem w proszku.',
    porcje: 6,
    czasMinut: 600,
    skladniki: ['1 l mleka odtłuszczonego', '3 łyżki mleka w proszku', '100 g jogurtu-startera'],
    kroki: [
      'Mleko w proszku dodaj do płynnego — bez niego odtłuszczony jogurt jest wodnisty.',
      'Podgrzej do 85°C, potem ostudź do 45°C.',
      'Wmieszaj starter i fermentuj 8 godzin.',
      'Odcedź przez gazę, jeśli chcesz gęstszą konsystencję.',
    ],
  },
  {
    slug: 'fruit-flavored-details',
    parent: 'yoghurt-details',
    nazwa: 'Fruit flavored yoghurt',
    opis: 'Jogurt z domowym musem owocowym na dnie.',
    porcje: 4,
    czasMinut: 30,
    skladniki: ['600 g jogurtu naturalnego', '300 g owoców', '3 łyżki cukru', 'sok z cytryny', 'wanilia'],
    kroki: [
      'Owoce duś z cukrem i sokiem z cytryny przez 10 minut.',
      'Zblenduj i całkowicie ostudź — ciepły mus rozrzedziłby jogurt.',
      'Nałóż mus na dno słoiczków.',
      'Zalej jogurtem i wstaw do lodówki na godzinę.',
    ],
  },
];
