import { Przepis } from '../przepis.model';

/** Pancakes, panini, makarony, pho, pizze, kotlety, żeberka,
 *  placki ziemniaczane, quiche, ramen, ratatouille, ravioli. */
export const PACZKA_4: Przepis[] = [
  // ---------- pancakes-details ----------
  {
    slug: 'classic-details',
    parent: 'pancakes-details',
    nazwa: 'Classic pancakes',
    opis: 'Amerykańskie puszyste placki z proszkiem do pieczenia, podawane z syropem klonowym.',
    porcje: 4,
    czasMinut: 25,
    skladniki: ['250 g mąki', '2 łyżeczki proszku do pieczenia', '2 łyżki cukru', '300 ml maślanki', '2 jajka', '50 g roztopionego masła', 'szczypta soli', 'syrop klonowy'],
    kroki: [
      'Wymieszaj osobno składniki suche i osobno mokre.',
      'Połącz je krótko — ciasto ma zostać grudkowate, mieszanie do gładkości daje gumowate placki.',
      'Odstaw na 10 minut.',
      'Smaż na suchej patelni po 2 minuty, obracając, gdy pojawią się bąbelki.',
      'Podawaj z masłem i syropem klonowym.',
    ],
  },
  {
    slug: 'blueberry-details',
    parent: 'pancakes-details',
    nazwa: 'Blueberry pancakes',
    opis: 'Z borówkami wrzucanymi na placek już na patelni.',
    porcje: 4,
    czasMinut: 25,
    skladniki: ['250 g mąki', '2 łyżeczki proszku do pieczenia', '300 ml maślanki', '2 jajka', '200 g borówek', 'cukier', 'masło'],
    kroki: [
      'Przygotuj ciasto jak na klasyczne pancakes.',
      'Wylej porcję na patelnię i dopiero wtedy rozrzuć borówki po wierzchu.',
      'Dzięki temu nie zabarwią całego ciasta na sino.',
      'Obróć, gdy brzegi się zetną, i dosmaż minutę.',
    ],
  },
  {
    slug: 'banana-details',
    parent: 'pancakes-details',
    nazwa: 'Banana pancakes',
    opis: 'Z bananem wmieszanym w ciasto — słodsze, wilgotniejsze.',
    porcje: 4,
    czasMinut: 25,
    skladniki: ['250 g mąki', '2 dojrzałe banany', '300 ml mleka', '2 jajka', '2 łyżeczki proszku do pieczenia', 'cynamon', 'masło'],
    kroki: [
      'Banany rozgnieć widelcem — im dojrzalsze, tym lepiej.',
      'Wymieszaj z mlekiem i jajkami, potem dodaj suche składniki.',
      'Smaż na średnim ogniu, bo ciasto z bananem szybciej się przypala.',
      'Podawaj z plastrami banana i cynamonem.',
    ],
  },
  {
    slug: 'chocolate-chip-details',
    parent: 'pancakes-details',
    nazwa: 'Chocolate chip pancakes',
    opis: 'Z kawałkami czekolady, które topią się w środku placka.',
    porcje: 4,
    czasMinut: 25,
    skladniki: ['250 g mąki', '300 ml maślanki', '2 jajka', '2 łyżeczki proszku do pieczenia', '150 g kropli czekoladowych', 'cukier', 'masło'],
    kroki: [
      'Przygotuj podstawowe ciasto naleśnikowe amerykańskie.',
      'Krople czekolady rozrzuć na placku już na patelni.',
      'Smaż po 2 minuty z każdej strony na średnim ogniu.',
      'Podawaj od razu, póki czekolada jest płynna.',
    ],
  },
  {
    slug: 'buttermilk-details',
    parent: 'pancakes-details',
    nazwa: 'Buttermilk pancakes',
    opis: 'Na samej maślance z sodą — najbardziej puszysta wersja.',
    porcje: 4,
    czasMinut: 25,
    skladniki: ['250 g mąki', '400 ml maślanki', '1 łyżeczka sody oczyszczonej', '1 łyżeczka proszku do pieczenia', '2 jajka', '50 g masła', 'sól'],
    kroki: [
      'Soda reaguje z kwasem maślanki — to ona daje puszystość.',
      'Wymieszaj składniki krótko i smaż od razu, nie odstawiaj ciasta.',
      'Smaż po 2 minuty z każdej strony.',
      'Nie dociskaj placków łopatką.',
    ],
  },

  // ---------- panini-details ----------
  {
    slug: 'caprese-details',
    parent: 'panini-details',
    nazwa: 'Caprese panini',
    opis: 'Grillowana kanapka z mozzarellą, pomidorem i bazylią.',
    porcje: 2,
    czasMinut: 15,
    skladniki: ['2 bułki ciabatta', '200 g mozzarelli', '2 pomidory', 'bazylia', 'pesto', 'oliwa', 'sól'],
    kroki: [
      'Bułki przekrój i posmaruj pesto od środka.',
      'Ułóż plastry mozzarelli i pomidora, dodaj bazylię.',
      'Posmaruj wierzch oliwą.',
      'Grilluj w prasie 5 minut, aż ser się roztopi.',
    ],
  },
  {
    slug: 'turkey-details',
    parent: 'panini-details',
    nazwa: 'Turkey panini',
    opis: 'Z pieczonym indykiem, serem provolone i musztardą miodową.',
    porcje: 2,
    czasMinut: 15,
    skladniki: ['2 bułki', '200 g pieczonego indyka', '100 g sera provolone', 'musztarda miodowa', 'sałata', 'pomidor', 'masło'],
    kroki: [
      'Posmaruj bułki musztardą miodową.',
      'Ułóż indyka, ser i pomidora.',
      'Zewnętrzną stronę posmaruj masłem — to ono daje chrupiącą skorupkę.',
      'Grilluj 5 minut, sałatę dodaj po wyjęciu.',
    ],
  },
  {
    slug: 'chicken-pesto-details',
    parent: 'panini-details',
    nazwa: 'Chicken pesto panini',
    opis: 'Z grillowanym kurczakiem, pesto i suszonymi pomidorami.',
    porcje: 2,
    czasMinut: 25,
    skladniki: ['2 bułki', '300 g piersi z kurczaka', '3 łyżki pesto', '50 g suszonych pomidorów', '100 g mozzarelli', 'rukola', 'oliwa'],
    kroki: [
      'Kurczaka rozbij, dopraw i grilluj po 4 minuty z każdej strony.',
      'Pokrój w plastry.',
      'Posmaruj bułki pesto, ułóż kurczaka, pomidory i ser.',
      'Grilluj 5 minut, rukolę dodaj na końcu.',
    ],
  },
  {
    slug: 'veggie-details',
    parent: 'panini-details',
    nazwa: 'Veggie panini',
    opis: 'Z grillowaną cukinią, bakłażanem i papryką, z hummusem.',
    porcje: 2,
    czasMinut: 25,
    skladniki: ['2 bułki', '1 cukinia', '1 bakłażan', '1 papryka', '4 łyżki hummusu', '100 g sera halloumi', 'oliwa', 'oregano'],
    kroki: [
      'Warzywa pokrój w plastry i grilluj po 3 minuty z każdej strony.',
      'Halloumi podsmaż na suchej patelni.',
      'Posmaruj bułki hummusem i ułóż warzywa.',
      'Grilluj kanapkę 5 minut.',
    ],
  },
  {
    slug: 'italian-details',
    parent: 'panini-details',
    nazwa: 'Italian panini',
    opis: 'Z salami, szynką parmeńską, provolone i papryką w zalewie.',
    porcje: 2,
    czasMinut: 15,
    skladniki: ['2 bułki ciabatta', '80 g salami', '80 g prosciutto', '100 g provolone', 'papryka w zalewie', 'oliwa', 'oregano'],
    kroki: [
      'Skrop wnętrze bułek oliwą i posyp oregano.',
      'Ułóż wędliny warstwami, między nie wsuń ser.',
      'Dodaj odsączoną paprykę.',
      'Grilluj 5 minut pod obciążeniem.',
    ],
  },

  // ---------- pasta-details ----------
  {
    slug: 'fusilli-with-pesto-details',
    parent: 'pasta-details',
    nazwa: 'Fusilli with pesto',
    opis: 'Świderki z pesto genovese, ziemniakami i fasolką — tak jak w Ligurii.',
    porcje: 4,
    czasMinut: 30,
    skladniki: ['400 g fusilli', '80 g bazylii', '50 g parmezanu', '30 g orzeszków piniowych', '1 ząbek czosnku', '120 ml oliwy', '200 g ziemniaków', '150 g fasolki szparagowej'],
    kroki: [
      'Utrzyj bazylię z czosnkiem, orzeszkami i solą, dodaj ser i oliwę.',
      'Ziemniaki i fasolkę gotuj w tej samej wodzie co makaron.',
      'Odlej szklankę wody z gotowania.',
      'Wymieszaj makaron z pesto poza ogniem, rozrzedzając wodą — gorąca patelnia zabija aromat bazylii.',
    ],
  },
  {
    slug: 'spaghetti-bolognese-details',
    parent: 'pasta-details',
    nazwa: 'Spaghetti bolognese',
    opis: 'Makaron z ragù alla bolognese duszonym co najmniej dwie godziny.',
    porcje: 4,
    czasMinut: 180,
    skladniki: ['400 g spaghetti', '500 g mielonej wołowiny', '150 g boczku', '1 cebula', '1 marchewka', '1 seler naciowy', '200 ml czerwonego wina', '400 g pomidorów', '200 ml mleka'],
    kroki: [
      'Sofrito z cebuli, marchwi i selera smaż 10 minut.',
      'Dodaj boczek i mięso, obsmaż na dużym ogniu.',
      'Wlej mleko i odparuj — zmiękcza mięso i łagodzi kwasowość.',
      'Dodaj wino, odparuj, potem pomidory.',
      'Duś 2 godziny na najmniejszym ogniu.',
    ],
  },
  {
    slug: 'penne-arabbiata-details',
    parent: 'pasta-details',
    nazwa: 'Penne all’arrabbiata',
    opis: 'Ostry sos pomidorowy z czosnkiem i chili — cała robota to pięć składników.',
    porcje: 4,
    czasMinut: 25,
    skladniki: ['400 g penne', '800 g pomidorów pelati', '4 ząbki czosnku', '2 papryczki chili', '60 ml oliwy', 'natka pietruszki', 'sól'],
    kroki: [
      'Czosnek i chili podsmaż w oliwie na małym ogniu 3 minuty — czosnek nie może zbrązowieć.',
      'Dodaj rozgniecione pomidory i gotuj 15 minut.',
      'Makaron ugotuj al dente i przełóż na patelnię z sosem.',
      'Smaż razem minutę, dodając wodę z makaronu.',
    ],
  },
  {
    slug: 'tagliatelle-carbonara-details',
    parent: 'pasta-details',
    nazwa: 'Tagliatelle carbonara',
    opis: 'Bez śmietany: jajka, guanciale, pecorino i pieprz — nic więcej.',
    porcje: 4,
    czasMinut: 25,
    skladniki: ['400 g tagliatelle', '200 g guanciale', '4 żółtka', '1 całe jajko', '100 g pecorino romano', 'czarny pieprz w ziarnach'],
    kroki: [
      'Guanciale pokrój w słupki i wytop powoli, bez dodatku tłuszczu.',
      'Żółtka wymieszaj z serem i mnóstwem świeżo mielonego pieprzu.',
      'Makaron odcedź, zachowując wodę.',
      'Zdejmij patelnię z ognia, wrzuć makaron i dopiero wtedy masę jajeczną.',
      'Mieszaj energicznie, dodając wodę — jajko ma stworzyć krem, nie jajecznicę.',
    ],
  },
  {
    slug: 'seafood-linguine-details',
    parent: 'pasta-details',
    nazwa: 'Seafood linguine',
    opis: 'Linguine allo scoglio z małżami, krewetkami i pomidorkami.',
    porcje: 4,
    czasMinut: 35,
    skladniki: ['400 g linguine', '500 g małży', '250 g krewetek', '200 g kalmarów', '200 g pomidorków', '150 ml białego wina', 'czosnek', 'natka', 'chili'],
    kroki: [
      'Małże otwórz w winie z czosnkiem, wyjmij i przecedź płyn.',
      'Podsmaż kalmary i krewetki 2 minuty.',
      'Dodaj pomidorki i przecedzony płyn z małży.',
      'Makaron ugotuj al dente i dokończ na patelni w sosie.',
      'Wróć małże na ostatnie 30 sekund.',
    ],
  },

  // ---------- pho-details ----------
  {
    slug: 'beef-pho-details',
    parent: 'pho-details',
    nazwa: 'Beef pho',
    opis: 'Wietnamska zupa z wołowiną — sekret leży w opalonym imbirze i cebuli oraz długim wywarze.',
    porcje: 4,
    czasMinut: 300,
    skladniki: ['1,5 kg kości wołowych', '300 g polędwicy', '2 cebule', '80 g imbiru', '4 gwiazdki anyżu', '1 laska cynamonu', '4 goździki', 'makaron ryżowy', 'sos rybny', 'kolendra, bazylia tajska'],
    kroki: [
      'Cebulę i imbir opal nad ogniem, aż zwęglą się z zewnątrz — to daje kolor i głębię.',
      'Kości sparz przez 10 minut, wylej wodę i wypłucz — dzięki temu wywar będzie klarowny.',
      'Gotuj kości z przyprawami 4 godziny na najmniejszym ogniu, nie mieszając.',
      'Dopraw sosem rybnym.',
      'Do miski włóż makaron i surową, cienko krojoną polędwicę; zalej wrzącym wywarem — ugotuje się sama.',
    ],
  },
  {
    slug: 'chicken-pho-details',
    parent: 'pho-details',
    nazwa: 'Chicken pho',
    opis: 'Pho gà — lżejsza wersja na kurczaku, gotowa w dwie godziny.',
    porcje: 4,
    czasMinut: 150,
    skladniki: ['1 kurczak', '2 cebule', '60 g imbiru', '3 gwiazdki anyżu', 'kolendra', 'makaron ryżowy', 'sos rybny', 'dymka', 'limonka'],
    kroki: [
      'Opal cebulę i imbir nad płomieniem.',
      'Gotuj kurczaka w całości z przyprawami przez 90 minut.',
      'Wyjmij mięso, obierz z kości i pokrój.',
      'Wywar dopraw sosem rybnym.',
      'Podawaj na makaronie z mięsem, dymką i ziołami.',
    ],
  },
  {
    slug: 'vegetarian-pho-details',
    parent: 'pho-details',
    nazwa: 'Vegetarian pho',
    opis: 'Wywar warzywno-grzybowy z tymi samymi przyprawami korzennymi.',
    porcje: 4,
    czasMinut: 90,
    skladniki: ['30 g suszonych grzybów shiitake', '2 cebule', '60 g imbiru', '2 marchewki', '1 rzodkiew daikon', 'anyż, cynamon, goździki', 'sos sojowy', 'tofu', 'makaron ryżowy'],
    kroki: [
      'Opal cebulę i imbir, tak samo jak w wersji mięsnej.',
      'Gotuj warzywa i grzyby z przyprawami przez 60 minut.',
      'Przecedź i dopraw sosem sojowym.',
      'Podawaj z podsmażonym tofu i świeżymi ziołami.',
    ],
  },
  {
    slug: 'seafood-pho-details',
    parent: 'pho-details',
    nazwa: 'Seafood pho',
    opis: 'Z krewetkami i kalmarami w klarownym wywarze rybnym.',
    porcje: 4,
    czasMinut: 90,
    skladniki: ['1 l wywaru rybnego', '250 g krewetek', '150 g kalmarów', 'imbir', 'anyż', 'sos rybny', 'makaron ryżowy', 'kolendra', 'chili'],
    kroki: [
      'Wywar rybny zagotuj z opalonym imbirem i anyżem, gotuj 30 minut.',
      'Przecedź i dopraw sosem rybnym.',
      'Owoce morza włóż do miski surowe i zalej wrzącym wywarem.',
      'Podawaj z chili i kolendrą.',
    ],
  },
  {
    slug: 'spicy-beef-pho-details',
    parent: 'pho-details',
    nazwa: 'Spicy beef pho',
    opis: 'Ostra odmiana bo kho z chili i cytronelą.',
    porcje: 4,
    czasMinut: 300,
    skladniki: ['1,5 kg kości wołowych', '400 g mostku', '4 papryczki chili', '2 łodygi cytronelli', 'imbir', 'anyż', 'sos rybny', 'makaron ryżowy', 'bazylia tajska'],
    kroki: [
      'Przygotuj wywar jak w klasycznym pho, dodając cytronelę i chili.',
      'Mostek gotuj w wywarze 3 godziny, potem pokrój w plastry.',
      'Dopraw sosem rybnym i sokiem z limonki.',
      'Podawaj z dodatkowym chili na talerzyku obok.',
    ],
  },

  // ---------- pizza-details ----------
  {
    slug: 'pizza-margherita-details',
    parent: 'pizza-details',
    nazwa: 'Pizza margherita',
    opis: 'Pomidory, mozzarella, bazylia — kolory włoskiej flagi na cieście.',
    porcje: 2,
    czasMinut: 90,
    skladniki: ['250 g mąki typu 00', '160 ml wody', '5 g soli', '2 g drożdży', '200 g pomidorów pelati', '150 g mozzarelli', 'bazylia', 'oliwa'],
    kroki: [
      'Zagnieć ciasto i zostaw do wyrośnięcia minimum 8 godzin.',
      'Rozciągnij placek rękami, nie wałkiem — wałek wygniata bąbelki z rantu.',
      'Rozsmaruj rozgniecione pomidory, dodaj mozzarellę.',
      'Piecz 6 minut w maksymalnej temperaturze piekarnika na rozgrzanym kamieniu.',
      'Bazylię i oliwę dodaj po upieczeniu.',
    ],
  },
  {
    slug: 'bbq-chicken-pizza-details',
    parent: 'pizza-details',
    nazwa: 'BBQ chicken pizza',
    opis: 'Amerykańska pizza z sosem barbecue zamiast pomidorowego.',
    porcje: 2,
    czasMinut: 90,
    skladniki: ['ciasto na pizzę', '150 ml sosu BBQ', '250 g grillowanego kurczaka', '1 czerwona cebula', '200 g mozzarelli', 'kolendra'],
    kroki: [
      'Rozciągnij ciasto i rozsmaruj sos BBQ.',
      'Ułóż kurczaka, cebulę i ser.',
      'Piecz 8 minut w 250°C.',
      'Posyp kolendrą po wyjęciu.',
    ],
  },
  {
    slug: 'hawaiian-pizza-details',
    parent: 'pizza-details',
    nazwa: 'Hawaiian pizza',
    opis: 'Szynka i ananas — pizza wynaleziona w Kanadzie, sporna do dziś.',
    porcje: 2,
    czasMinut: 90,
    skladniki: ['ciasto na pizzę', '200 g passaty', '150 g szynki', '150 g ananasa', '200 g mozzarelli', 'oregano'],
    kroki: [
      'Ananas dobrze odsącz — nadmiar soku rozmoczy ciasto.',
      'Rozsmaruj passatę, ułóż ser, szynkę i ananasa.',
      'Piecz 8 minut w 250°C.',
      'Posyp oregano.',
    ],
  },
  {
    slug: 'pizza-margherita-con-bufala-details',
    parent: 'pizza-details',
    nazwa: 'Margherita con bufala',
    opis: 'Margherita z mozzarellą bawolą dodawaną po upieczeniu.',
    porcje: 2,
    czasMinut: 90,
    skladniki: ['ciasto na pizzę', '200 g pomidorów pelati', '200 g mozzarelli di bufala', 'bazylia', 'oliwa extra vergine', 'sól'],
    kroki: [
      'Mozzarellę bawolą odsącz przez 30 minut — jest bardzo wodnista.',
      'Piecz pizzę z samym sosem pomidorowym przez 5 minut.',
      'Dodaj mozzarellę i dopiekaj 2 minuty.',
      'Bazylię i oliwę dołóż na koniec.',
    ],
  },
  {
    slug: 'neapolitan-pizza-details',
    parent: 'pizza-details',
    nazwa: 'Neapolitan pizza',
    opis: 'Wysoki, poparzony rant i miękki środek — pieczona 90 sekund w 450°C.',
    porcje: 2,
    czasMinut: 1500,
    skladniki: ['250 g mąki typu 00', '165 ml wody', '7 g soli', '0,5 g drożdży', 'pomidory San Marzano', 'fior di latte', 'bazylia', 'oliwa'],
    kroki: [
      'Ciasto o wysokim uwodnieniu wyrastaj 24 godziny w temperaturze pokojowej.',
      'Formuj kulki i odstaw na kolejne 6 godzin.',
      'Rozciągaj wyłącznie palcami, przesuwając powietrze do rantu.',
      'Piecz jak najkrócej w jak najwyższej temperaturze — w domowym piekarniku użyj kamienia i funkcji grill.',
    ],
  },
  {
    slug: 'pizza-pepperoni-details',
    parent: 'pizza-details',
    nazwa: 'Pizza pepperoni',
    opis: 'Z ostrą kiełbasą pepperoni, która zwija się w miseczki i wytapia tłuszcz.',
    porcje: 2,
    czasMinut: 90,
    skladniki: ['ciasto na pizzę', '200 g passaty', '200 g mozzarelli', '120 g pepperoni', 'oregano', 'chili'],
    kroki: [
      'Rozsmaruj sos i ser.',
      'Ułóż plastry pepperoni z odstępami — rozszerzą się podczas pieczenia.',
      'Piecz 8 minut w 250°C.',
      'Posyp oregano i płatkami chili.',
    ],
  },
  {
    slug: 'quattro-satgioni-pizza-details',
    parent: 'pizza-details',
    nazwa: 'Quattro stagioni',
    opis: 'Cztery pory roku na czterech ćwiartkach: karczochy, szynka, grzyby, oliwki.',
    porcje: 2,
    czasMinut: 90,
    skladniki: ['ciasto na pizzę', '200 g passaty', '200 g mozzarelli', 'karczochy', 'szynka', 'pieczarki', 'oliwki czarne'],
    kroki: [
      'Rozsmaruj sos i ser na całości.',
      'Podziel powierzchnię na cztery ćwiartki.',
      'Na każdą nałóż inny dodatek, nie mieszając ich.',
      'Piecz 8 minut w 250°C.',
    ],
  },
  {
    slug: 'supreme-pizza-details',
    parent: 'pizza-details',
    nazwa: 'Supreme pizza',
    opis: 'Wszystkiego po trochu: kiełbasa, papryka, cebula, oliwki, pieczarki.',
    porcje: 2,
    czasMinut: 90,
    skladniki: ['ciasto na pizzę', '200 g passaty', '200 g mozzarelli', '100 g kiełbasy', '1 papryka', '1 cebula', 'oliwki', 'pieczarki'],
    kroki: [
      'Warzywa pokrój cienko — grube kawałki nie zdążą się upiec.',
      'Rozłóż sos, ser i wszystkie dodatki.',
      'Piecz 9 minut w 250°C, bo pizza jest obciążona.',
      'Odstaw minutę przed krojeniem.',
    ],
  },
  {
    slug: 'white-pizza-details',
    parent: 'pizza-details',
    nazwa: 'White pizza',
    opis: 'Pizza bianca bez sosu pomidorowego — na ricotcie i czosnku.',
    porcje: 2,
    czasMinut: 90,
    skladniki: ['ciasto na pizzę', '250 g ricotty', '150 g mozzarelli', '50 g parmezanu', '3 ząbki czosnku', 'rozmaryn', 'oliwa'],
    kroki: [
      'Ricottę wymieszaj z czosnkiem, oliwą i solą.',
      'Rozsmaruj na cieście zamiast sosu pomidorowego.',
      'Dodaj mozzarellę i parmezan.',
      'Piecz 8 minut w 250°C, posyp rozmarynem.',
    ],
  },
  {
    slug: 'chicago-deep-dish-details',
    parent: 'pizza-details',
    nazwa: 'Chicago deep dish',
    opis: 'Gruba pizza z Chicago pieczona w formie: ser na spodzie, sos na wierzchu.',
    porcje: 4,
    czasMinut: 150,
    skladniki: ['400 g mąki', '100 g masła', '250 ml wody', '7 g drożdży', '400 g mozzarelli w plastrach', '300 g kiełbasy włoskiej', '600 g pomidorów', 'oregano'],
    kroki: [
      'Ciasto z dodatkiem masła wyłóż na wysoką formę, podciągając na boki.',
      'Na spód ułóż plastry mozzarelli — chronią ciasto przed rozmoczeniem.',
      'Dodaj kiełbasę, a na samą górę gęsty sos pomidorowy.',
      'Piecz 35 minut w 200°C.',
      'Odstaw 10 minut przed krojeniem, inaczej się rozpadnie.',
    ],
  },

  // ---------- pork-cutlet-details ----------
  {
    slug: 'tonkatsu-details',
    parent: 'pork-cutlet-details',
    nazwa: 'Tonkatsu',
    opis: 'Japoński kotlet schabowy w panierce panko, podawany z kapustą i sosem tonkatsu.',
    porcje: 2,
    czasMinut: 35,
    skladniki: ['2 kotlety schabowe', 'mąka', '2 jajka', '150 g panko', 'olej do smażenia', 'kapusta biała', 'sos tonkatsu', 'musztarda karashi'],
    kroki: [
      'Kotlety natnij po brzegach, żeby się nie zwinęły, i rozbij lekko.',
      'Panieruj w mące, jajku i panko, dociskając okruchy.',
      'Smaż w oleju 170°C przez 6 minut, obracając raz.',
      'Odsącz i pokrój w paski przed podaniem.',
      'Podawaj z górą cienko szatkowanej kapusty.',
    ],
  },
  {
    slug: 'schnitzel-details',
    parent: 'pork-cutlet-details',
    nazwa: 'Wiener schnitzel',
    opis: 'Cielęcy sznycel po wiedeńsku — panierka ma odstawać od mięsa.',
    porcje: 2,
    czasMinut: 30,
    skladniki: ['2 plastry cielęciny', 'mąka', '2 jajka', 'bułka tarta', '200 g masła klarowanego', 'cytryna', 'sól'],
    kroki: [
      'Mięso rozbij na grubość 4 mm.',
      'Panieruj kolejno w mące, jajku i bułce tartej, nie dociskając panierki.',
      'Smaż w dużej ilości masła klarowanego, potrząsając patelnią — to sprawia, że panierka się podnosi.',
      'Smaż po 2 minuty z każdej strony i podawaj z cytryną.',
    ],
  },
  {
    slug: 'milanesa-details',
    parent: 'pork-cutlet-details',
    nazwa: 'Milanesa',
    opis: 'Argentyńska wersja z czosnkiem i natką w panierce.',
    porcje: 2,
    czasMinut: 40,
    skladniki: ['2 plastry wołowiny', '2 jajka', '3 ząbki czosnku', 'natka pietruszki', 'bułka tarta', 'olej', 'cytryna'],
    kroki: [
      'Jajka roztrzep z posiekanym czosnkiem i natką.',
      'Mięso rozbij i zanurz w jajku na 30 minut — to marynata, nie tylko klej.',
      'Obtocz w bułce tartej.',
      'Smaż po 3 minuty z każdej strony.',
    ],
  },
  {
    slug: 'pork-katsu-curry-details',
    parent: 'pork-cutlet-details',
    nazwa: 'Pork katsu curry',
    opis: 'Tonkatsu podane z japońskim gęstym curry i ryżem.',
    porcje: 2,
    czasMinut: 60,
    skladniki: ['2 kotlety schabowe', 'panko', '2 jajka', 'kostki japońskiego curry', '2 marchewki', '2 ziemniaki', '1 cebula', 'ryż'],
    kroki: [
      'Warzywa pokrój i gotuj 20 minut w wodzie.',
      'Zdejmij z ognia i rozpuść kostki curry — wrzenie sprawia, że sos się warzy.',
      'Kotlety zpanieruj w panko i usmaż.',
      'Podawaj na ryżu: kotlet pokrojony w paski, obok sos curry.',
    ],
  },
  {
    slug: 'cordon-bleu-details',
    parent: 'pork-cutlet-details',
    nazwa: 'Cordon bleu',
    opis: 'Kotlet nadziewany szynką i serem, panierowany i smażony.',
    porcje: 2,
    czasMinut: 50,
    skladniki: ['2 duże plastry schabu', '4 plastry szynki', '100 g sera ementaler', 'mąka', '2 jajka', 'bułka tarta', 'olej'],
    kroki: [
      'Mięso rozbij cienko i nadziej szynką oraz serem.',
      'Zwiń i spnij wykałaczkami, dociskając brzegi.',
      'Panieruj podwójnie — jajko, bułka, jajko, bułka — żeby ser nie wyciekł.',
      'Smaż 8 minut, potem dopiecz 10 minut w 180°C.',
    ],
  },
  {
    slug: 'schabowy-details',
    parent: 'pork-cutlet-details',
    nazwa: 'Kotlet schabowy',
    opis: 'Polski kotlet schabowy smażony na smalcu, podawany z ziemniakami i mizerią.',
    porcje: 4,
    czasMinut: 40,
    skladniki: ['4 kotlety schabowe', 'mąka', '2 jajka', 'bułka tarta', 'smalec', 'sól, pieprz'],
    kroki: [
      'Kotlety rozbij tłuczkiem do grubości 1 cm.',
      'Dopraw solą i pieprzem po obu stronach.',
      'Panieruj w mące, jajku i bułce tartej.',
      'Smaż na smalcu po 4 minuty z każdej strony na średnim ogniu.',
    ],
  },

  // ---------- pork-ribbs-details ----------
  {
    slug: 'baby-back-ribs-details',
    parent: 'pork-ribbs-details',
    nazwa: 'Baby back ribs',
    opis: 'Krótkie żeberka od grzbietu, pieczone powoli i lakierowane sosem BBQ.',
    porcje: 4,
    czasMinut: 240,
    skladniki: ['2 płaty żeberek', 'papryka wędzona', 'brązowy cukier', 'czosnek w proszku', 'sól, pieprz', '200 ml sosu BBQ', 'ocet jabłkowy'],
    kroki: [
      'Zdejmij błonę ze spodu żeberek — bez tego przyprawy nie wnikną, a mięso zostanie twarde.',
      'Natrzyj mieszanką przypraw i odstaw na godzinę.',
      'Piecz zawinięte w folię 2,5 godziny w 150°C.',
      'Rozwiń, posmaruj sosem i piecz jeszcze 30 minut w 200°C.',
    ],
  },
  {
    slug: 'country-style-ribs-details',
    parent: 'pork-ribbs-details',
    nazwa: 'Country style ribs',
    opis: 'Grube kawałki z karkówki, bardziej mięsne niż klasyczne żeberka.',
    porcje: 4,
    czasMinut: 180,
    skladniki: ['1,2 kg karkówki w kawałkach', 'cebula', 'sos BBQ', 'bulion', 'papryka wędzona', 'czosnek', 'musztarda'],
    kroki: [
      'Mięso obsmaż ze wszystkich stron.',
      'Ułóż w naczyniu z cebulą, zalej bulionem do połowy wysokości.',
      'Piecz pod przykryciem 2 godziny w 160°C.',
      'Odkryj, posmaruj sosem i dopiekaj 30 minut.',
    ],
  },
  {
    slug: 'spareribs-ribs-details',
    parent: 'pork-ribbs-details',
    nazwa: 'Spareribs',
    opis: 'Żeberka z boku, tłustsze i bardziej aromatyczne, wędzone lub pieczone.',
    porcje: 4,
    czasMinut: 300,
    skladniki: ['2 płaty żeberek', 'mieszanka przypraw BBQ', 'sok jabłkowy', 'miód', 'masło', 'sos BBQ'],
    kroki: [
      'Natrzyj żeberka przyprawami i zostaw na noc w lodówce.',
      'Piecz 3 godziny w 120°C, spryskując sokiem jabłkowym co 45 minut.',
      'Zawiń w folię z miodem i masłem, piecz kolejne 2 godziny.',
      'Rozwiń, posmaruj sosem i zapiecz 20 minut w 200°C.',
    ],
  },
  {
    slug: 'st.-louis-style-ribs-details',
    parent: 'pork-ribbs-details',
    nazwa: 'St. Louis style ribs',
    opis: 'Żeberka przycięte na prostokąt, przez co pieką się równomiernie.',
    porcje: 4,
    czasMinut: 270,
    skladniki: ['2 płaty żeberek', 'mieszanka przypraw', 'ocet jabłkowy', 'brązowy cukier', 'sos BBQ', 'masło'],
    kroki: [
      'Przytnij płat, usuwając chrząstki i końcówki — stąd nazwa stylu.',
      'Natrzyj przyprawami i odstaw na 2 godziny.',
      'Piecz 3 godziny w 130°C.',
      'Lakieruj sosem trzy razy w odstępach 15 minut.',
    ],
  },
  {
    slug: 'pork-ribs-tips-details',
    parent: 'pork-ribbs-details',
    nazwa: 'Rib tips',
    opis: 'Chrząstkowe końcówki odcinane przy formowaniu St. Louis — tanie i bardzo smaczne.',
    porcje: 4,
    czasMinut: 180,
    skladniki: ['1 kg końcówek żeberek', 'mieszanka przypraw', 'sos BBQ', 'ocet', 'papryka wędzona', 'cebula'],
    kroki: [
      'Pokrój końcówki na kawałki wielkości kęsa.',
      'Natrzyj przyprawami i piecz 2 godziny w 150°C pod folią.',
      'Odkryj, wymieszaj z sosem.',
      'Dopiekaj 30 minut, aż brzegi się przypieką.',
    ],
  },

  // ---------- potato-cakes-details ----------
  {
    slug: 'traditional-potato-cakes-details',
    parent: 'potato-cakes-details',
    nazwa: 'Traditional potato cakes',
    opis: 'Placki ziemniaczane smażone na złoto, podawane ze śmietaną albo cukrem.',
    porcje: 4,
    czasMinut: 40,
    skladniki: ['1 kg ziemniaków', '1 cebula', '1 jajko', '3 łyżki mąki', 'sól, pieprz', 'olej do smażenia'],
    kroki: [
      'Ziemniaki i cebulę zetrzyj na drobnych oczkach.',
      'Odciśnij nadmiar wody — od tego zależy, czy placki będą chrupiące.',
      'Dodaj jajko, mąkę i przyprawy.',
      'Smaż na dobrze rozgrzanym oleju po 3 minuty z każdej strony.',
    ],
  },
  {
    slug: 'cheese-potato-cakes-details',
    parent: 'potato-cakes-details',
    nazwa: 'Cheese potato cakes',
    opis: 'Z serem żółtym w masie, ciągnącym się po przekrojeniu.',
    porcje: 4,
    czasMinut: 40,
    skladniki: ['1 kg ziemniaków', '150 g sera żółtego', '1 cebula', '1 jajko', '3 łyżki mąki', 'szczypiorek', 'olej'],
    kroki: [
      'Zetrzyj ziemniaki i odciśnij.',
      'Wmieszaj starty ser, jajko, mąkę i szczypiorek.',
      'Smaż na średnim ogniu — ser przy zbyt dużym wypływa i przypala się.',
      'Podawaj od razu.',
    ],
  },
  {
    slug: 'bacon-potato-cakes-details',
    parent: 'potato-cakes-details',
    nazwa: 'Bacon potato cakes',
    opis: 'Ze skwarkami z boczku wmieszanymi w masę.',
    porcje: 4,
    czasMinut: 45,
    skladniki: ['1 kg ziemniaków', '200 g boczku', '1 cebula', '1 jajko', '3 łyżki mąki', 'majeranek', 'sól, pieprz'],
    kroki: [
      'Boczek pokrój w kostkę i wytop na chrupko; tłuszcz zachowaj.',
      'Zetrzyj ziemniaki i odciśnij.',
      'Dodaj skwarki, jajko, mąkę i majeranek.',
      'Smaż na wytopionym tłuszczu z boczku.',
    ],
  },
  {
    slug: 'sweet-potato-cakes-details',
    parent: 'potato-cakes-details',
    nazwa: 'Sweet potato cakes',
    opis: 'Z batatów — słodsze, o pomarańczowym miąższu.',
    porcje: 4,
    czasMinut: 40,
    skladniki: ['800 g batatów', '1 jajko', '4 łyżki mąki', 'papryka wędzona', 'kmin rzymski', 'kolendra', 'jogurt do podania'],
    kroki: [
      'Bataty zetrzyj — puszczają mniej wody niż zwykłe ziemniaki.',
      'Wymieszaj z jajkiem, mąką i przyprawami.',
      'Smaż po 3 minuty z każdej strony na średnim ogniu.',
      'Podawaj z jogurtem i kolendrą.',
    ],
  },
  {
    slug: 'herbed-potato-cakes-details',
    parent: 'potato-cakes-details',
    nazwa: 'Herbed potato cakes',
    opis: 'Z dużą ilością świeżych ziół: koperku, natki i szczypiorku.',
    porcje: 4,
    czasMinut: 40,
    skladniki: ['1 kg ziemniaków', 'pęczek koperku', 'pęczek szczypiorku', 'natka pietruszki', '1 jajko', '3 łyżki mąki', 'czosnek', 'olej'],
    kroki: [
      'Zetrzyj ziemniaki i odciśnij dokładnie.',
      'Posiekaj zioła i wmieszaj razem z czosnkiem.',
      'Dodaj jajko i mąkę.',
      'Smaż na złoto i podawaj ze śmietaną.',
    ],
  },

  // ---------- quiche-details ----------
  {
    slug: 'spinach-and-feta-details',
    parent: 'quiche-details',
    nazwa: 'Spinach and feta quiche',
    opis: 'Tarta na kruchym cieście ze szpinakiem i fetą w masie jajecznej.',
    porcje: 6,
    czasMinut: 90,
    skladniki: ['250 g mąki', '125 g zimnego masła', '1 jajko do ciasta', '400 g szpinaku', '200 g fety', '3 jajka', '250 ml śmietanki 30%', 'gałka muszkatołowa'],
    kroki: [
      'Zagnieć kruche ciasto i chłodź 30 minut.',
      'Wyłóż formę i podpiecz na ślepo 15 minut z obciążeniem.',
      'Szpinak podduś i mocno odciśnij.',
      'Wymieszaj jajka ze śmietanką, dopraw gałką muszkatołową.',
      'Rozłóż szpinak i fetę, zalej masą i piecz 35 minut w 180°C.',
    ],
  },
  {
    slug: 'bacon-and-cheddar-details',
    parent: 'quiche-details',
    nazwa: 'Bacon and cheddar quiche',
    opis: 'Wersja bliska quiche lorraine, z boczkiem i dojrzewającym cheddarem.',
    porcje: 6,
    czasMinut: 90,
    skladniki: ['kruche ciasto', '250 g boczku', '200 g cheddara', '3 jajka', '250 ml śmietanki', '1 cebula', 'pieprz'],
    kroki: [
      'Podpiecz spód na ślepo przez 15 minut.',
      'Boczek wysmaż z cebulą i odsącz z tłuszczu.',
      'Rozłóż na cieście razem z serem.',
      'Zalej masą jajeczną i piecz 35 minut w 180°C.',
    ],
  },
  {
    slug: 'mushroom-and-swiss-details',
    parent: 'quiche-details',
    nazwa: 'Mushroom and swiss quiche',
    opis: 'Z pieczarkami i serem szwajcarskim, doprawiona tymiankiem.',
    porcje: 6,
    czasMinut: 95,
    skladniki: ['kruche ciasto', '400 g pieczarek', '200 g sera szwajcarskiego', '3 jajka', '250 ml śmietanki', 'tymianek', 'szalotka'],
    kroki: [
      'Pieczarki smaż na dużym ogniu, aż odparuje cała woda — inaczej quiche będzie mokry.',
      'Podpiecz spód na ślepo.',
      'Rozłóż grzyby i ser, zalej masą jajeczną.',
      'Piecz 35 minut w 180°C.',
    ],
  },
  {
    slug: 'broccoli-and-cheddar-details',
    parent: 'quiche-details',
    nazwa: 'Broccoli and cheddar quiche',
    opis: 'Z brokułami blanszowanymi na jasnozielono i ostrym cheddarem.',
    porcje: 6,
    czasMinut: 90,
    skladniki: ['kruche ciasto', '400 g brokułów', '200 g cheddara', '3 jajka', '250 ml śmietanki', 'musztarda dijon', 'pieprz'],
    kroki: [
      'Brokuły blanszuj 3 minuty i przełóż do lodowatej wody.',
      'Podpiecz spód na ślepo.',
      'Do masy jajecznej dodaj łyżeczkę musztardy — podbija smak sera.',
      'Rozłóż brokuły i ser, zalej i piecz 35 minut.',
    ],
  },
  {
    slug: 'tomato-and-basil-details',
    parent: 'quiche-details',
    nazwa: 'Tomato and basil quiche',
    opis: 'Letnia tarta z pomidorami i bazylią, z odrobiną musztardy na spodzie.',
    porcje: 6,
    czasMinut: 90,
    skladniki: ['kruche ciasto', '5 pomidorów', 'bazylia', '150 g sera gruyère', '3 jajka', '250 ml śmietanki', 'musztarda dijon'],
    kroki: [
      'Podpiecz spód i posmaruj go cienko musztardą — to bariera przed wilgocią z pomidorów.',
      'Pomidory pokrój w plastry, posól i odsącz na ręczniku przez 15 minut.',
      'Ułóż na cieście z serem, zalej masą jajeczną.',
      'Piecz 35 minut w 180°C, posyp bazylią po wyjęciu.',
    ],
  },

  // ---------- ramen-details ----------
  {
    slug: 'shoyu-ramen-details',
    parent: 'ramen-details',
    nazwa: 'Shoyu ramen',
    opis: 'Ramen na klarownym bulionie drobiowym doprawionym sosem sojowym.',
    porcje: 4,
    czasMinut: 240,
    skladniki: ['1 kurczak', 'kombu', 'suszone shiitake', '150 ml sosu sojowego', 'mirin', 'makaron ramen', 'jajka', 'chashu', 'dymka', 'nori'],
    kroki: [
      'Gotuj kurczaka z kombu i shiitake przez 3 godziny na najmniejszym ogniu — bulion ma pozostać klarowny.',
      'Tare: zredukuj sos sojowy z mirin i sake.',
      'Jajka gotuj 6,5 minuty i marynuj w sosie sojowym przez noc.',
      'Do miski wlej tare, zalej gorącym bulionem, dodaj ugotowany makaron.',
      'Ułóż chashu, jajko, nori i dymkę.',
    ],
  },
  {
    slug: 'tonkotsu-ramen-details',
    parent: 'ramen-details',
    nazwa: 'Tonkotsu ramen',
    opis: 'Mętny, kremowy bulion z kości wieprzowych gotowany na wrzącym ogniu kilkanaście godzin.',
    porcje: 4,
    czasMinut: 720,
    skladniki: ['2 kg kości wieprzowych', 'nóżki wieprzowe', 'czosnek', 'imbir', 'makaron ramen', 'chashu', 'jajka', 'grzyby kikurage', 'dymka'],
    kroki: [
      'Kości sparz i wypłucz z krwi.',
      'Gotuj je na MOCNYM ogniu 12 godzin — to burzliwe wrzenie emulguje tłuszcz i daje mleczny kolor.',
      'Dolewaj wrzątek, żeby poziom się nie obniżał.',
      'Przecedź, dopraw tare i podawaj z makaronem oraz dodatkami.',
    ],
  },
  {
    slug: 'miso-ramen-details',
    parent: 'ramen-details',
    nazwa: 'Miso ramen',
    opis: 'Wersja z Hokkaido — bulion doprawiony pastą miso, z masłem i kukurydzą.',
    porcje: 4,
    czasMinut: 240,
    skladniki: ['bulion wieprzowo-drobiowy', '4 łyżki pasty miso', 'mielona wieprzowina', 'kukurydza', 'masło', 'kiełki fasoli', 'czosnek', 'makaron ramen'],
    kroki: [
      'Podsmaż mieloną wieprzowinę z czosnkiem i pastą miso.',
      'Zalej gorącym bulionem i wymieszaj.',
      'Ugotuj makaron i przełóż do misek.',
      'Dodaj kukurydzę, kiełki i kostkę masła na wierzch.',
    ],
  },
  {
    slug: 'shio-ramen-details',
    parent: 'ramen-details',
    nazwa: 'Shio ramen',
    opis: 'Najlżejszy z ramenów — doprawiany solą, o jasnym, przejrzystym bulionie.',
    porcje: 4,
    czasMinut: 200,
    skladniki: ['bulion drobiowy', 'kombu', 'suszone przegrzebki', 'sól morska', 'makaron ramen', 'jajko', 'kurczak', 'dymka', 'menma'],
    kroki: [
      'Bulion gotuj z kombu i suszonymi przegrzebkami przez 3 godziny.',
      'Tare zrób z soli morskiej rozpuszczonej w sake i odrobinie bulionu.',
      'Zalej makaron bulionem z tare.',
      'Dodaj kurczaka, jajko, menmę i dymkę.',
    ],
  },
  {
    slug: 'tantanmen-ramen-details',
    parent: 'ramen-details',
    nazwa: 'Tantanmen',
    opis: 'Japońska wersja dan dan mian: pikantny bulion z pastą sezamową i mieloną wieprzowiną.',
    porcje: 4,
    czasMinut: 60,
    skladniki: ['bulion drobiowy', '4 łyżki pasty sezamowej tahini', 'olej chili', 'doubanjiang', '300 g mielonej wieprzowiny', 'makaron ramen', 'bok choy', 'dymka'],
    kroki: [
      'Wieprzowinę podsmaż z doubanjiang do zbrązowienia.',
      'W misce wymieszaj tahini z olejem chili i sosem sojowym.',
      'Zalej gorącym bulionem, energicznie mieszając, żeby powstała emulsja.',
      'Dodaj makaron, mięso i blanszowany bok choy.',
    ],
  },

  // ---------- ratatouille-details ----------
  {
    slug: 'traditional-ratatouille-details',
    parent: 'ratatouille-details',
    nazwa: 'Traditional ratatouille',
    opis: 'Prowansalski gulasz warzywny, w którym każde warzywo smaży się osobno.',
    porcje: 4,
    czasMinut: 75,
    skladniki: ['1 bakłażan', '2 cukinie', '2 papryki', '4 pomidory', '2 cebule', '4 ząbki czosnku', 'zioła prowansalskie', 'oliwa'],
    kroki: [
      'Każde warzywo podsmaż osobno na oliwie — to sedno tego przepisu.',
      'Wspólne smażenie sprawiłoby, że cukinia się rozpadnie, zanim bakłażan zmięknie.',
      'Połącz wszystko w jednym garnku z czosnkiem i ziołami.',
      'Duś razem 20 minut, żeby smaki się połączyły.',
    ],
  },
  {
    slug: 'layered-ratatouille-details',
    parent: 'ratatouille-details',
    nazwa: 'Layered ratatouille',
    opis: 'Warzywa ułożone w koncentryczne kręgi i zapiekane — wersja z filmu.',
    porcje: 4,
    czasMinut: 90,
    skladniki: ['1 bakłażan', '2 cukinie', '4 pomidory', '2 papryki', '1 cebula', 'czosnek', 'tymianek', 'oliwa'],
    kroki: [
      'Zrób sos z podsmażonej cebuli, papryki i pomidorów, zblenduj i wylej na dno formy.',
      'Warzywa pokrój w cienkie plastry tej samej grubości.',
      'Ustawiaj je pionowo, na przemian, w ciasnej spirali.',
      'Skrop oliwą, przykryj papierem i piecz 50 minut w 180°C.',
    ],
  },
  {
    slug: 'niçoise-ratatouille-details',
    parent: 'ratatouille-details',
    nazwa: 'Ratatouille niçoise',
    opis: 'Wersja z Nicei — z oliwkami, kaparami i odrobiną octu.',
    porcje: 4,
    czasMinut: 70,
    skladniki: ['1 bakłażan', '2 cukinie', '2 papryki', '4 pomidory', '100 g oliwek czarnych', '2 łyżki kaparów', 'ocet winny', 'bazylia', 'oliwa'],
    kroki: [
      'Warzywa podsmaż osobno i połącz.',
      'Dodaj oliwki i kapary.',
      'Duś 20 minut, na koniec dodaj łyżkę octu winnego.',
      'Posyp świeżą bazylią i podawaj także na zimno.',
    ],
  },
  {
    slug: 'tian-ratatouille-details',
    parent: 'ratatouille-details',
    nazwa: 'Tian de légumes',
    opis: 'Warzywa ułożone rzędami w płaskim naczyniu i długo pieczone.',
    porcje: 4,
    czasMinut: 100,
    skladniki: ['2 cukinie', '4 pomidory', '1 bakłażan', '2 cebule', 'czosnek', 'tymianek', 'oliwa', 'parmezan'],
    kroki: [
      'Cebulę podduś i rozłóż na dnie naczynia.',
      'Warzywa pokrój w plastry 3 mm i układaj rzędami, zachodzące na siebie.',
      'Skrop oliwą, posyp tymiankiem i czosnkiem.',
      'Piecz 60 minut w 190°C, ostatnie 10 minut z parmezanem.',
    ],
  },
  {
    slug: 'ratatouille-roulade-details',
    parent: 'ratatouille-details',
    nazwa: 'Ratatouille roulade',
    opis: 'Plastry bakłażana i cukinii zwinięte w ruloniki z nadzieniem warzywnym.',
    porcje: 4,
    czasMinut: 80,
    skladniki: ['1 bakłażan', '2 cukinie', '2 papryki', 'passata', 'ricotta', 'bazylia', 'czosnek', 'oliwa'],
    kroki: [
      'Bakłażan i cukinię pokrój wzdłuż w plastry i grilluj do zmiękczenia.',
      'Paprykę upiecz, obierz i posiekaj, wymieszaj z ricottą.',
      'Nakładaj farsz i zwijaj ruloniki.',
      'Ustaw w naczyniu z passatą i zapiekaj 25 minut w 180°C.',
    ],
  },

  // ---------- ravioli-details ----------
  {
    slug: 'cheese-ravioli-details',
    parent: 'ravioli-details',
    nazwa: 'Cheese ravioli',
    opis: 'Pierożki z ricottą i parmezanem, podawane z masłem szałwiowym.',
    porcje: 4,
    czasMinut: 90,
    skladniki: ['300 g mąki 00', '3 jajka', '400 g ricotty', '100 g parmezanu', 'gałka muszkatołowa', '80 g masła', 'szałwia'],
    kroki: [
      'Zagnieć ciasto z mąki i jajek, wyrabiaj 10 minut i odstaw na 30 minut.',
      'Ricottę odciśnij i wymieszaj z parmezanem oraz gałką muszkatołową.',
      'Rozwałkuj ciasto bardzo cienko, nakładaj farsz co 4 cm.',
      'Przykryj drugim płatem, wyciśnij powietrze i wytnij pierożki.',
      'Gotuj 3 minuty i podawaj z masłem przesmażonym z szałwią.',
    ],
  },
  {
    slug: 'spinach-and-ricotta-ravioli-details',
    parent: 'ravioli-details',
    nazwa: 'Spinach and ricotta ravioli',
    opis: 'Klasyczne zielone nadzienie ze szpinaku i ricotty.',
    porcje: 4,
    czasMinut: 100,
    skladniki: ['ciasto makaronowe', '400 g szpinaku', '300 g ricotty', '80 g parmezanu', 'gałka muszkatołowa', 'masło', 'szałwia'],
    kroki: [
      'Szpinak zblanszuj, odciśnij do sucha i drobno posiekaj.',
      'Wymieszaj z ricottą i parmezanem.',
      'Formuj ravioli, dbając o wyciśnięcie powietrza — inaczej pękną w gotowaniu.',
      'Gotuj 3–4 minuty i podawaj z masłem szałwiowym.',
    ],
  },
  {
    slug: 'mushroom-ravioli-details',
    parent: 'ravioli-details',
    nazwa: 'Mushroom ravioli',
    opis: 'Z farszem z podsmażonych grzybów leśnych i szalotki.',
    porcje: 4,
    czasMinut: 100,
    skladniki: ['ciasto makaronowe', '400 g grzybów leśnych', '2 szalotki', '100 g ricotty', 'tymianek', 'masło', 'parmezan', 'białe wino'],
    kroki: [
      'Grzyby posiekaj i smaż z szalotką, aż odparuje cała woda.',
      'Podlej winem i odparuj, wymieszaj z ricottą.',
      'Nadziewaj ravioli i zlepiaj dokładnie.',
      'Gotuj 3 minuty, podawaj z masłem i parmezanem.',
    ],
  },
  {
    slug: 'lobster-ravioli-details',
    parent: 'ravioli-details',
    nazwa: 'Lobster ravioli',
    opis: 'Odświętna wersja z homarem i sosem z bisque.',
    porcje: 4,
    czasMinut: 150,
    skladniki: ['ciasto makaronowe', '2 homary', '100 g mascarpone', 'szalotka', 'koniak', 'śmietanka 30%', 'estragon', 'masło'],
    kroki: [
      'Homary ugotuj, wyjmij mięso, a pancerze zachowaj.',
      'Z pancerzy zrób bisque: podsmaż, podpal koniakiem, zalej wodą i gotuj godzinę.',
      'Mięso posiekaj i wymieszaj z mascarpone oraz estragonem.',
      'Uformuj ravioli i gotuj 3 minuty.',
      'Bisque zredukuj ze śmietanką i polej pierożki.',
    ],
  },
  {
    slug: 'butternut-squash-ravioli-details',
    parent: 'ravioli-details',
    nazwa: 'Butternut squash ravioli',
    opis: 'Z pieczoną dynią piżmową, amaretti i gałką muszkatołową.',
    porcje: 4,
    czasMinut: 120,
    skladniki: ['ciasto makaronowe', '600 g dyni piżmowej', '50 g amaretti', '80 g parmezanu', 'gałka muszkatołowa', 'masło', 'szałwia', 'orzechy włoskie'],
    kroki: [
      'Dynię upiecz w 200°C przez 40 minut i odparuj nadmiar wilgoci na patelni.',
      'Rozgnieć i wymieszaj z pokruszonymi amaretti oraz parmezanem.',
      'Nadziewaj ravioli.',
      'Gotuj 3 minuty, podawaj z masłem szałwiowym i orzechami.',
    ],
  },
];
