import { Przepis } from '../przepis.model';

/** Croissanty, curry, dim sum, donburi, pierogi, jajka, focaccia,
 *  gulasze, sałatka grecka, dorada, kurczak z grilla, bigosy. */
export const PACZKA_2: Przepis[] = [
  // ---------- Croissant ----------
  {
    slug: 'classic-butter-details',
    parent: 'croissant-details',
    nazwa: 'Classic butter croissant',
    opis: 'Francuski rogalik z ciasta półfrancuskiego — setki warstw masła i ciasta drożdżowego.',
    porcje: 8,
    czasMinut: 720,
    skladniki: ['500 g mąki chlebowej', '250 g zimnego masła', '250 ml mleka', '10 g drożdży', '50 g cukru', '10 g soli', '1 jajko do posmarowania'],
    kroki: [
      'Zagnieć ciasto drożdżowe i chłodź przez noc.',
      'Masło rozbij na płaski prostokąt i zamknij w cieście.',
      'Wykonaj trzy złożenia potrójne, chłodząc ciasto 45 minut po każdym.',
      'Rozwałkuj, potnij na trójkąty i zwiń rogaliki.',
      'Wyrastaj 2 godziny, posmaruj jajkiem i piecz 18 minut w 200°C.',
    ],
  },
  {
    slug: 'almond-details',
    parent: 'croissant-details',
    nazwa: 'Almond croissant',
    opis: 'Rogalik z kremem migdałowym, klasycznie robiony z wczorajszych croissantów.',
    porcje: 6,
    czasMinut: 45,
    skladniki: ['6 croissantów z poprzedniego dnia', '150 g mielonych migdałów', '150 g masła', '150 g cukru', '2 jajka', 'płatki migdałowe', 'syrop cukrowy'],
    kroki: [
      'Utrzyj masło z cukrem, dodaj jajka i mielone migdały.',
      'Croissanty przekrój i nasącz syropem cukrowym.',
      'Nałóż krem do środka i na wierzch.',
      'Posyp płatkami migdałowymi i piecz 15 minut w 180°C.',
    ],
  },
  {
    slug: 'chocolate-details',
    parent: 'croissant-details',
    nazwa: 'Pain au chocolat',
    opis: 'Prostokątny rogalik z dwiema sztabkami ciemnej czekolady w środku.',
    porcje: 8,
    czasMinut: 720,
    skladniki: ['ciasto półfrancuskie z przepisu podstawowego', '16 sztabek czekolady deserowej', '1 jajko', 'szczypta soli'],
    kroki: [
      'Rozwałkuj ciasto na prostokąt grubości 4 mm i potnij na paski.',
      'Na każdy pasek połóż sztabkę czekolady, zawiń, dołóż drugą i zawiń do końca.',
      'Ułóż złączeniem do dołu i wyrastaj 2 godziny.',
      'Posmaruj jajkiem i piecz 18 minut w 200°C.',
    ],
  },
  {
    slug: 'ham-and-cheese-details',
    parent: 'croissant-details',
    nazwa: 'Ham and cheese croissant',
    opis: 'Wytrawny rogalik z szynką, serem i beszamelem, zapiekany do złocistości.',
    porcje: 4,
    czasMinut: 30,
    skladniki: ['4 croissanty', '8 plastrów szynki', '120 g sera gruyère', '200 ml beszamelu', 'musztarda dijon', 'gałka muszkatołowa'],
    kroki: [
      'Croissanty przekrój wzdłuż i posmaruj musztardą.',
      'Nałóż szynkę, ser i łyżkę beszamelu.',
      'Zamknij, na wierzch dodaj resztę beszamelu i tarty ser.',
      'Piecz 12 minut w 190°C.',
    ],
  },
  {
    slug: 'fruit-filled-details',
    parent: 'croissant-details',
    nazwa: 'Fruit filled croissant',
    opis: 'Rogalik z konfiturą owocową i kremem cukierniczym.',
    porcje: 6,
    czasMinut: 40,
    skladniki: ['6 croissantów', '200 g konfitury malinowej', '250 g kremu cukierniczego', 'świeże maliny', 'cukier puder'],
    kroki: [
      'Croissanty nadetnij wzdłuż, nie przecinając do końca.',
      'Wyciśnij krem cukierniczy, a na niego łyżeczkę konfitury.',
      'Podpiecz 6 minut w 170°C, żeby były ciepłe, ale nie wysuszone.',
      'Udekoruj świeżymi malinami i cukrem pudrem.',
    ],
  },

  // ---------- Curry ----------
  {
    slug: 'chicken-curry-details',
    parent: 'curry-details',
    nazwa: 'Chicken curry',
    opis: 'Kurczak duszony w sosie z pomidorów, cebuli i przypraw korzennych, z mlekiem kokosowym.',
    porcje: 4,
    czasMinut: 50,
    skladniki: ['600 g piersi z kurczaka', '400 ml mleka kokosowego', '2 cebule', '400 g pomidorów z puszki', '2 łyżki pasty curry', '20 g imbiru', '3 ząbki czosnku', 'kolendra'],
    kroki: [
      'Cebulę smaż 10 minut, aż mocno się zarumieni — to podstawa smaku.',
      'Dodaj czosnek, imbir i pastę curry, smaż minutę do uwolnienia aromatu.',
      'Wrzuć kurczaka i obsmaż ze wszystkich stron.',
      'Wlej pomidory i mleko kokosowe, duś 25 minut bez przykrycia.',
      'Posyp świeżą kolendrą przed podaniem.',
    ],
  },
  {
    slug: 'lamb-curry-details',
    parent: 'curry-details',
    nazwa: 'Lamb curry',
    opis: 'Jagnięcina duszona długo w gęstym sosie z garam masala — im dłużej, tym bardziej krucha.',
    porcje: 4,
    czasMinut: 150,
    skladniki: ['800 g łopatki jagnięcej', '2 cebule', '200 g jogurtu naturalnego', '2 łyżki garam masala', '1 łyżeczka kurkumy', '4 ząbki czosnku', 'imbir', 'kolendra'],
    kroki: [
      'Mięso zamarynuj w jogurcie z przyprawami na 2 godziny.',
      'Obsmaż partiami na dużym ogniu i odłóż.',
      'Zeszklij cebulę z czosnkiem i imbirem.',
      'Wróć mięso, wlej wodę do przykrycia i duś 2 godziny na małym ogniu.',
    ],
  },
  {
    slug: 'vegetable-curry-details',
    parent: 'curry-details',
    nazwa: 'Vegetable curry',
    opis: 'Warzywne curry z ciecierzycą, kalafiorem i szpinakiem, na mleku kokosowym.',
    porcje: 4,
    czasMinut: 40,
    skladniki: ['1 kalafior', '1 puszka ciecierzycy', '200 g szpinaku', '400 ml mleka kokosowego', '2 łyżki pasty curry', '1 cebula', 'imbir', 'limonka'],
    kroki: [
      'Kalafior podziel na różyczki i podsmaż na oleju do zarumienienia.',
      'Dodaj cebulę, imbir i pastę curry.',
      'Wlej mleko kokosowe, dorzuć ciecierzycę i duś 15 minut.',
      'Na koniec wmieszaj szpinak i sok z limonki.',
    ],
  },
  {
    slug: 'fish-curry-details',
    parent: 'curry-details',
    nazwa: 'Fish curry',
    opis: 'Curry z południa Indii — ryba w kwaśno-kokosowym sosie z tamaryndowcem.',
    porcje: 4,
    czasMinut: 35,
    skladniki: ['600 g białej ryby', '400 ml mleka kokosowego', '2 łyżki pasty tamaryndowej', '1 łyżeczka kurkumy', 'liście curry', 'nasiona gorczycy', 'chili', 'cebula'],
    kroki: [
      'Rozgrzej olej, wrzuć gorczycę i poczekaj, aż zacznie strzelać.',
      'Dodaj liście curry, cebulę i chili, smaż 5 minut.',
      'Wlej mleko kokosowe z kurkumą i tamaryndowcem, gotuj 10 minut.',
      'Włóż kawałki ryby i gotuj 6 minut — nie mieszaj, żeby się nie rozpadła.',
    ],
  },
  {
    slug: 'beef-curry-details',
    parent: 'curry-details',
    nazwa: 'Beef curry',
    opis: 'Wołowina duszona w ciemnym, korzennym sosie z cynamonem i goździkami.',
    porcje: 4,
    czasMinut: 180,
    skladniki: ['800 g pręgi wołowej', '2 cebule', '2 łyżki pasty curry', '1 laska cynamonu', '4 goździki', '400 ml bulionu', '200 ml mleka kokosowego', 'ziemniaki'],
    kroki: [
      'Wołowinę pokrój w kostkę i obsmaż partiami.',
      'Podsmaż cebulę z pastą curry, cynamonem i goździkami.',
      'Wlej bulion, duś 2 godziny pod przykryciem.',
      'Dodaj ziemniaki i mleko kokosowe, gotuj kolejne 30 minut.',
    ],
  },

  // ---------- Dim sum ----------
  {
    slug: 'shumai-details',
    parent: 'dim-sum-details',
    nazwa: 'Shumai',
    opis: 'Otwarte pierożki na parze z wieprzowiną i krewetkami, w cienkim żółtym cieście.',
    porcje: 4,
    czasMinut: 60,
    skladniki: ['300 g mielonej wieprzowiny', '150 g krewetek', '24 okrągłe płaty na wontony', '2 łyżki sosu sojowego', '1 łyżka oleju sezamowego', 'imbir', 'dymka', 'skrobia kukurydziana'],
    kroki: [
      'Krewetki posiekaj grubo i wymieszaj z mięsem, sosem sojowym i imbirem.',
      'Wyrabiaj farsz przez 3 minuty w jedną stronę — dzięki temu się zwiąże.',
      'Nałóż łyżeczkę farszu na płat, ściśnij boki, zostawiając górę otwartą.',
      'Gotuj na parze 12 minut.',
    ],
  },
  {
    slug: 'har-gow-details',
    parent: 'dim-sum-details',
    nazwa: 'Har gow',
    opis: 'Przezroczyste pierożki z krewetkami w cieście ze skrobi pszennej.',
    porcje: 4,
    czasMinut: 75,
    skladniki: ['200 g skrobi pszennej', '50 g skrobi tapiokowej', '300 ml wrzątku', '300 g krewetek', 'pędy bambusa', 'olej sezamowy', 'biały pieprz', 'sól'],
    kroki: [
      'Skrobie zalej wrzątkiem i szybko wymieszaj — ciasto musi być zaparzone.',
      'Wyrabiaj na gorąco, aż będzie gładkie i elastyczne.',
      'Krewetki posiekaj, wymieszaj z bambusem i przyprawami.',
      'Rozwałkuj cienkie krążki, nadziej i zrób 7–10 zakładek.',
      'Gotuj na parze 8 minut — dłużej i ciasto pęknie.',
    ],
  },
  {
    slug: 'char-siu-bao-details',
    parent: 'dim-sum-details',
    nazwa: 'Char siu bao',
    opis: 'Puszyste drożdżowe bułeczki na parze z wieprzowiną char siu w słodkim sosie.',
    porcje: 6,
    czasMinut: 150,
    skladniki: ['500 g mąki', '10 g drożdży', '250 ml mleka', '50 g cukru', '400 g wieprzowiny char siu', '2 łyżki sosu hoisin', '1 łyżka sosu ostrygowego', 'skrobia'],
    kroki: [
      'Zagnieć miękkie ciasto drożdżowe i zostaw do podwojenia objętości.',
      'Mięso pokrój w kostkę, wymieszaj z sosami i zagęść skrobią.',
      'Podziel ciasto na kulki, rozpłaszcz i nadziej farszem.',
      'Zamknij, marszcząc brzegi, ustaw na papierkach.',
      'Wyrastaj 30 minut i gotuj na parze 15 minut.',
    ],
  },
  {
    slug: 'cheung-fun-details',
    parent: 'dim-sum-details',
    nazwa: 'Cheung fun',
    opis: 'Zwijane naleśniki z mąki ryżowej, polane słodkim sosem sojowym.',
    porcje: 4,
    czasMinut: 60,
    skladniki: ['200 g mąki ryżowej', '50 g skrobi tapiokowej', '600 ml wody', '200 g krewetek', 'olej', 'sos sojowy', 'cukier', 'olej sezamowy'],
    kroki: [
      'Wymieszaj mąki z wodą na rzadkie, jednolite ciasto.',
      'Wylej cienką warstwę na naoliwioną tacę i gotuj na parze 4 minuty.',
      'Ułóż krewetki i zwiń naleśnik w rulon.',
      'Polej sosem sojowym z cukrem i olejem sezamowym.',
    ],
  },
  {
    slug: 'turnip-cake-details',
    parent: 'dim-sum-details',
    nazwa: 'Turnip cake',
    opis: 'Placki z rzodkwi białej z suszonymi krewetkami, gotowane na parze i podsmażane.',
    porcje: 6,
    czasMinut: 120,
    skladniki: ['800 g rzodkwi białej', '200 g mąki ryżowej', '50 g suszonych krewetek', '2 chińskie kiełbaski', 'biały pieprz', 'sól', 'olej'],
    kroki: [
      'Rzodkiew zetrzyj i poduś 15 minut, aż puści wodę.',
      'Podsmaż krewetki i kiełbaski, dodaj do rzodkwi.',
      'Wmieszaj mąkę ryżową na gęstą masę.',
      'Przełóż do formy i gotuj na parze 50 minut.',
      'Ostudź, pokrój w plastry i podsmaż na złoto.',
    ],
  },

  // ---------- Donburi ----------
  {
    slug: 'katsu-don-details',
    parent: 'donburi-details',
    nazwa: 'Katsu don',
    opis: 'Panierowany kotlet wieprzowy duszony z cebulą i jajkiem, podany na ryżu.',
    porcje: 2,
    czasMinut: 40,
    skladniki: ['2 kotlety schabowe', 'panko', '2 jajka do panierki', '2 jajka do sosu', '1 cebula', '200 ml dashi', '3 łyżki sosu sojowego', '2 łyżki mirin', 'ryż'],
    kroki: [
      'Kotlety zpanieruj w mące, jajku i panko, usmaż na złoto i pokrój w paski.',
      'W płaskim rondlu zagotuj dashi z sosem sojowym i mirin.',
      'Włóż cebulę i gotuj 3 minuty, potem ułóż na niej kotlet.',
      'Zalej roztrzepanym jajkiem i przykryj na minutę — jajko ma pozostać półpłynne.',
      'Zsuń całość na miskę gorącego ryżu.',
    ],
  },
  {
    slug: 'oyako-don-details',
    parent: 'donburi-details',
    nazwa: 'Oyako don',
    opis: 'Kurczak z jajkiem na ryżu — nazwa znaczy „rodzic i dziecko".',
    porcje: 2,
    czasMinut: 25,
    skladniki: ['300 g udek z kurczaka bez kości', '3 jajka', '1 cebula', '200 ml dashi', '3 łyżki sosu sojowego', '2 łyżki mirin', '1 łyżka cukru', 'ryż', 'dymka'],
    kroki: [
      'Zagotuj dashi z sosem sojowym, mirin i cukrem.',
      'Włóż cebulę i kurczaka, gotuj 7 minut.',
      'Wlej roztrzepane jajka po obwodzie, nie mieszając.',
      'Przykryj na 60 sekund i zsuń na ryż, posyp dymką.',
    ],
  },
  {
    slug: 'gyudon-details',
    parent: 'donburi-details',
    nazwa: 'Gyudon',
    opis: 'Cienko krojona wołowina duszona z cebulą w słodko-słonym sosie, na ryżu.',
    porcje: 2,
    czasMinut: 25,
    skladniki: ['300 g cienko krojonej wołowiny', '1 cebula', '150 ml dashi', '3 łyżki sosu sojowego', '2 łyżki mirin', '1 łyżka sake', 'ryż', 'marynowany imbir'],
    kroki: [
      'Zagotuj dashi z sosem sojowym, mirin i sake.',
      'Włóż cebulę pokrojoną w pióra i gotuj 5 minut.',
      'Dodaj wołowinę i gotuj tylko 3 minuty — dłużej stanie się twarda.',
      'Nałóż na ryż razem z sosem, podawaj z marynowanym imbirem.',
    ],
  },
  {
    slug: 'tekka-don-details',
    parent: 'donburi-details',
    nazwa: 'Tekka don',
    opis: 'Surowy tuńczyk marynowany w sosie sojowym, ułożony na occianym ryżu.',
    porcje: 2,
    czasMinut: 30,
    skladniki: ['300 g tuńczyka w jakości sashimi', '3 łyżki sosu sojowego', '1 łyżka mirin', 'ryż do sushi', 'ocet ryżowy', 'wasabi', 'nori', 'dymka'],
    kroki: [
      'Ryż ugotuj i wymieszaj z octem ryżowym, ostudź do temperatury ciała.',
      'Tuńczyka pokrój w plastry grubości 5 mm.',
      'Marynuj w sosie sojowym z mirin przez 10 minut, nie dłużej.',
      'Ułóż na ryżu, posyp nori i dymką, podawaj z wasabi.',
    ],
  },
  {
    slug: 'unagi-don-details',
    parent: 'donburi-details',
    nazwa: 'Unagi don',
    opis: 'Grillowany węgorz w gęstym słodkim sosie kabayaki, na ryżu.',
    porcje: 2,
    czasMinut: 30,
    skladniki: ['2 filety z węgorza', '4 łyżki sosu sojowego', '4 łyżki mirin', '2 łyżki cukru', '2 łyżki sake', 'ryż', 'sansho'],
    kroki: [
      'Zagotuj sos sojowy z mirin, sake i cukrem, redukuj do konsystencji syropu.',
      'Węgorza podpiecz pod grillem 5 minut skórą do góry.',
      'Posmaruj sosem i grilluj jeszcze 2 minuty; powtórz trzy razy.',
      'Ułóż na ryżu, polej sosem i posyp pieprzem sansho.',
    ],
  },

  // ---------- Dumplings ----------
  {
    slug: 'chinese-dumplings-details',
    parent: 'dumplings-details',
    nazwa: 'Chinese dumplings',
    opis: 'Jiaozi z wieprzowiną i kapustą pekińską, gotowane lub smażone od spodu.',
    porcje: 4,
    czasMinut: 90,
    skladniki: ['300 g mąki', '160 ml wrzątku', '400 g mielonej wieprzowiny', '300 g kapusty pekińskiej', 'imbir', 'dymka', 'sos sojowy', 'olej sezamowy'],
    kroki: [
      'Mąkę zaparz wrzątkiem i wyrabiaj 10 minut, odstaw na 30 minut.',
      'Kapustę posiekaj, posól i odciśnij z wody.',
      'Wymieszaj z mięsem, imbirem, dymką i sosem sojowym.',
      'Rozwałkuj krążki, nadziej i zlep w zakładki.',
      'Gotuj 6 minut albo podsmaż od spodu i podlej wodą pod przykryciem.',
    ],
  },
  {
    slug: 'japanese-dumplings-details',
    parent: 'dumplings-details',
    nazwa: 'Gyoza',
    opis: 'Japońskie pierożki smażone od spodu do chrupkości, dogotowywane na parze.',
    porcje: 4,
    czasMinut: 60,
    skladniki: ['30 płatów gyoza', '300 g mielonej wieprzowiny', '200 g kapusty', 'czosnek', 'imbir', 'olej sezamowy', 'sos sojowy', 'ocet ryżowy'],
    kroki: [
      'Farsz z mięsa, kapusty, czosnku i imbiru wyrabiaj do zwięzłości.',
      'Nadziewaj płaty, zlepiając brzeg w charakterystyczne fałdki po jednej stronie.',
      'Smaż na oleju 2 minuty, aż spód będzie złoty.',
      'Wlej 50 ml wody, przykryj i gotuj 6 minut, aż woda odparuje.',
      'Podawaj z sosem sojowym z octem ryżowym.',
    ],
  },
  {
    slug: 'korean-dumplings-details',
    parent: 'dumplings-details',
    nazwa: 'Mandu',
    opis: 'Koreańskie pierożki z mięsem, tofu i kimchi, gotowane na parze.',
    porcje: 4,
    czasMinut: 70,
    skladniki: ['30 płatów mandu', '200 g mielonej wieprzowiny', '150 g tofu', '150 g kimchi', 'makaron sojowy', 'czosnek', 'olej sezamowy', 'dymka'],
    kroki: [
      'Tofu odciśnij i rozgnieć, kimchi odciśnij i posiekaj.',
      'Makaron sojowy namocz i pokrój na krótkie kawałki.',
      'Wymieszaj wszystko z mięsem i przyprawami.',
      'Nadziej płaty i zlep w półksiężyce, łącząc końce w pierścień.',
      'Gotuj na parze 12 minut.',
    ],
  },
  {
    slug: 'polish-dumplings-details',
    parent: 'dumplings-details',
    nazwa: 'Pierogi ruskie',
    opis: 'Polskie pierogi z farszem z twarogu i ziemniaków, podawane ze skwarkami.',
    porcje: 4,
    czasMinut: 90,
    skladniki: ['400 g mąki', '200 ml ciepłej wody', '1 jajko', '500 g ziemniaków', '250 g twarogu', '2 cebule', '150 g boczku', 'sól, pieprz'],
    kroki: [
      'Zagnieć ciasto z mąki, wody i jajka; przykryj i odstaw na 30 minut.',
      'Ziemniaki ugotuj, ugnieć i wymieszaj z twarogiem oraz zeszkloną cebulą.',
      'Rozwałkuj cienko, wycinaj krążki i nakładaj farsz.',
      'Zlep dokładnie brzegi i gotuj 3 minuty od wypłynięcia.',
      'Podawaj ze skwarkami z boczku i cebulą.',
    ],
  },
  {
    slug: 'tibetan-dumplings-details',
    parent: 'dumplings-details',
    nazwa: 'Momo',
    opis: 'Tybetańskie pierożki na parze z jagnięciną i przyprawami, podawane z ostrym sosem.',
    porcje: 4,
    czasMinut: 80,
    skladniki: ['400 g mąki', '200 ml wody', '400 g mielonej jagnięciny', '1 cebula', 'kolendra', 'kmin rzymski', 'imbir', 'pomidory i chili do sosu'],
    kroki: [
      'Zagnieć proste ciasto z mąki i wody, odstaw na 30 minut.',
      'Farsz: mięso, cebula, kolendra, imbir i kmin rzymski.',
      'Formuj okrągłe sakiewki, zbierając ciasto na górze.',
      'Gotuj na parze 15 minut.',
      'Sos: podpieczone pomidory zblenduj z chili i czosnkiem.',
    ],
  },

  // ---------- Eggs ----------
  {
    slug: 'deviled-details',
    parent: 'eggs-details',
    nazwa: 'Deviled eggs',
    opis: 'Jajka faszerowane własnym żółtkiem utartym z majonezem i musztardą.',
    porcje: 4,
    czasMinut: 25,
    skladniki: ['6 jajek', '4 łyżki majonezu', '1 łyżeczka musztardy dijon', 'papryka wędzona', 'szczypiorek', 'sól, pieprz'],
    kroki: [
      'Jajka gotuj 9 minut i od razu przełóż do lodowatej wody.',
      'Przekrój na połówki, wyjmij żółtka.',
      'Utrzyj żółtka z majonezem i musztardą na gładko.',
      'Nałóż masę do połówek, posyp papryką i szczypiorkiem.',
    ],
  },
  {
    slug: 'florentine-details',
    parent: 'eggs-details',
    nazwa: 'Eggs Florentine',
    opis: 'Jajko w koszulce na szpinaku i muffince angielskiej, pod sosem holenderskim.',
    porcje: 2,
    czasMinut: 35,
    skladniki: ['4 jajka', '200 g szpinaku', '2 muffinki angielskie', '3 żółtka', '150 g masła klarowanego', 'sok z cytryny', 'gałka muszkatołowa'],
    kroki: [
      'Szpinak podduś na maśle i odciśnij, dopraw gałką muszkatołową.',
      'Sos holenderski: żółtka ubijaj nad parą, powoli wlewając masło klarowane.',
      'Jajka gotuj w koszulkach 3 minuty w wodzie z octem.',
      'Na podpieczoną muffinkę nałóż szpinak, jajko i sos.',
    ],
  },
  {
    slug: 'royale-details',
    parent: 'eggs-details',
    nazwa: 'Eggs Royale',
    opis: 'Wersja z łososiem wędzonym zamiast szynki — brytyjskie śniadanie z hotelu.',
    porcje: 2,
    czasMinut: 30,
    skladniki: ['4 jajka', '150 g łososia wędzonego', '2 muffinki angielskie', '3 żółtka', '150 g masła klarowanego', 'sok z cytryny', 'koperek'],
    kroki: [
      'Przygotuj sos holenderski, ubijając żółtka nad parą z masłem.',
      'Ugotuj jajka w koszulkach — woda ma drżeć, nie wrzeć.',
      'Muffinki przekrój i podpiecz.',
      'Ułóż łososia, jajko, polej sosem i posyp koperkiem.',
    ],
  },

  // ---------- Focaccia ----------
  {
    slug: 'classic-focaccia-details',
    parent: 'focaccia-details',
    nazwa: 'Classic focaccia',
    opis: 'Ligurijski płaski chleb z charakterystycznymi dołkami wypełnionymi oliwą i solą.',
    porcje: 8,
    czasMinut: 240,
    skladniki: ['500 g mąki chlebowej', '400 ml wody', '7 g drożdży suszonych', '60 ml oliwy', '10 g soli', 'sól morska w płatkach', 'rozmaryn'],
    kroki: [
      'Wymieszaj składniki na bardzo mokre ciasto i zostaw na 3 godziny, składając co 30 minut.',
      'Przełóż na naoliwioną blachę i rozciągnij palcami.',
      'Zrób głębokie dołki opuszkami palców — to znak rozpoznawczy focaccii.',
      'Skrop oliwą, posyp solą morską i rozmarynem.',
      'Piecz 20 minut w 230°C.',
    ],
  },
  {
    slug: 'rosemary-focaccia-details',
    parent: 'focaccia-details',
    nazwa: 'Rosemary focaccia',
    opis: 'Focaccia z dużą ilością świeżego rozmarynu i grubą solą.',
    porcje: 8,
    czasMinut: 240,
    skladniki: ['ciasto na focaccię', '4 gałązki rozmarynu', '80 ml oliwy', 'sól morska', '2 ząbki czosnku'],
    kroki: [
      'Oliwę podgrzej z rozmarynem i czosnkiem, ostudź — to wyciągnie aromat.',
      'Rozciągnij ciasto na blasze i zrób dołki.',
      'Polej aromatyzowaną oliwą i posyp solą.',
      'Piecz 20 minut w 230°C.',
    ],
  },
  {
    slug: 'tomato-and-basil-focaccia-details',
    parent: 'focaccia-details',
    nazwa: 'Tomato and basil focaccia',
    opis: 'Z pomidorkami koktajlowymi wciśniętymi w ciasto i bazylią dodaną po pieczeniu.',
    porcje: 8,
    czasMinut: 240,
    skladniki: ['ciasto na focaccię', '250 g pomidorków koktajlowych', 'bazylia', 'oliwa', 'sól morska', 'oregano'],
    kroki: [
      'Pomidorki przekrój i wciśnij w dołki w cieście.',
      'Skrop oliwą, posyp solą i oregano.',
      'Piecz 22 minuty w 230°C.',
      'Bazylię dodaj dopiero po wyjęciu — w piekarniku sczerniałaby.',
    ],
  },
  {
    slug: 'onion-focaccia-details',
    parent: 'focaccia-details',
    nazwa: 'Onion focaccia',
    opis: 'Z karmelizowaną czerwoną cebulą i tymiankiem.',
    porcje: 8,
    czasMinut: 260,
    skladniki: ['ciasto na focaccię', '3 czerwone cebule', '2 łyżki octu balsamicznego', 'tymianek', 'oliwa', 'sól'],
    kroki: [
      'Cebulę pokrój w pióra i smaż 20 minut na wolnym ogniu z octem balsamicznym.',
      'Rozłóż na rozciągniętym cieście.',
      'Posyp tymiankiem i skrop oliwą.',
      'Piecz 22 minuty w 230°C.',
    ],
  },
  {
    slug: 'olive-focaccia-details',
    parent: 'focaccia-details',
    nazwa: 'Olive focaccia',
    opis: 'Z oliwkami zielonymi i czarnymi wciśniętymi w ciasto.',
    porcje: 8,
    czasMinut: 240,
    skladniki: ['ciasto na focaccię', '150 g oliwek mieszanych', 'oliwa', 'rozmaryn', 'sól morska'],
    kroki: [
      'Oliwki odsącz i przekrój na połówki.',
      'Wciśnij je w dołki w cieście, żeby nie wypadły podczas pieczenia.',
      'Skrop oliwą, posyp rozmarynem.',
      'Piecz 20 minut w 230°C.',
    ],
  },

  // ---------- Goulash ----------
  {
    slug: 'beef-goulash-details',
    parent: 'goulash-details',
    nazwa: 'Beef goulash',
    opis: 'Węgierski gulasz wołowy z dużą ilością papryki, duszony do rozpadania się mięsa.',
    porcje: 4,
    czasMinut: 180,
    skladniki: ['800 g łopatki wołowej', '3 cebule', '3 łyżki papryki słodkiej mielonej', '2 papryki czerwone', '400 g pomidorów', 'kminek', 'smalec', 'sól'],
    kroki: [
      'Cebulę smaż na smalcu 15 minut, aż będzie miękka i słodka.',
      'Zdejmij z ognia i wsyp paprykę — na gorącym tłuszczu zgorzknieje w kilka sekund.',
      'Dodaj mięso, paprykę świeżą, pomidory i kminek.',
      'Duś pod przykryciem 2,5 godziny, dolewając wody w razie potrzeby.',
    ],
  },
  {
    slug: 'pork-goulash-details',
    parent: 'goulash-details',
    nazwa: 'Pork goulash',
    opis: 'Gulasz wieprzowy z kiszoną kapustą i śmietaną — bliżej kuchni czeskiej.',
    porcje: 4,
    czasMinut: 120,
    skladniki: ['700 g łopatki wieprzowej', '300 g kapusty kiszonej', '2 cebule', '2 łyżki papryki', '200 ml śmietany', 'kminek', 'liść laurowy'],
    kroki: [
      'Mięso obsmaż partiami i odłóż.',
      'Zeszklij cebulę, zdejmij z ognia i wmieszaj paprykę.',
      'Wróć mięso, dodaj kapustę i przyprawy, duś 90 minut.',
      'Zahartuj śmietanę i wmieszaj tuż przed podaniem.',
    ],
  },
  {
    slug: 'chicken-goulash-details',
    parent: 'goulash-details',
    nazwa: 'Chicken goulash',
    opis: 'Lżejszy gulasz z udek kurczaka, gotowy w godzinę.',
    porcje: 4,
    czasMinut: 60,
    skladniki: ['800 g udek z kurczaka', '2 cebule', '2 papryki', '2 łyżki papryki mielonej', '400 ml bulionu', '150 ml śmietany', 'majeranek'],
    kroki: [
      'Udka obsmaż na złoto i odłóż.',
      'Podsmaż cebulę i paprykę, dodaj mieloną paprykę poza ogniem.',
      'Wlej bulion, wróć mięso i duś 35 minut.',
      'Wmieszaj śmietanę i majeranek.',
    ],
  },
  {
    slug: 'lamb-goulash-details',
    parent: 'goulash-details',
    nazwa: 'Lamb goulash',
    opis: 'Jagnięcina z papryką i rozmarynem, duszona w czerwonym winie.',
    porcje: 4,
    czasMinut: 160,
    skladniki: ['800 g łopatki jagnięcej', '200 ml czerwonego wina', '3 cebule', '2 łyżki papryki', '400 g pomidorów', 'rozmaryn', 'czosnek'],
    kroki: [
      'Mięso obsmaż i odstaw.',
      'Cebulę smaż do zmiękczenia, dodaj czosnek i paprykę poza ogniem.',
      'Wlej wino, odparuj alkohol, dodaj pomidory i mięso.',
      'Duś 2 godziny z rozmarynem.',
    ],
  },
  {
    slug: 'vegetarian-goulash-details',
    parent: 'goulash-details',
    nazwa: 'Vegetarian goulash',
    opis: 'Bezmięsny gulasz na fasoli i grzybach, z tą samą paprykową bazą.',
    porcje: 4,
    czasMinut: 60,
    skladniki: ['400 g pieczarek', '1 puszka fasoli czerwonej', '3 papryki', '2 cebule', '2 łyżki papryki mielonej', '400 g pomidorów', 'kminek', 'oliwa'],
    kroki: [
      'Pieczarki podsmaż na dużym ogniu, aż odparuje woda.',
      'Dodaj cebulę i paprykę świeżą, smaż 8 minut.',
      'Poza ogniem wsyp paprykę mieloną, potem dodaj pomidory.',
      'Wrzuć fasolę i duś 25 minut.',
    ],
  },

  // ---------- Greek salad ----------
  {
    slug: 'classic-greek-salad-details',
    parent: 'greek-salad-details',
    nazwa: 'Classic greek salad',
    opis: 'Pomidory, ogórek, cebula, oliwki i plaster fety — bez sałaty i bez sosu poza oliwą.',
    porcje: 4,
    czasMinut: 15,
    skladniki: ['4 pomidory', '1 ogórek', '1 czerwona cebula', '150 g oliwek kalamata', '200 g fety', 'oliwa extra vergine', 'oregano', 'sól'],
    kroki: [
      'Pomidory pokrój w duże cząstki, ogórek w grube półplastry.',
      'Cebulę pokrój w cienkie pióra.',
      'Wymieszaj z oliwkami, posól.',
      'Na wierzch połóż feta w jednym kawałku, skrop oliwą i posyp oregano.',
    ],
  },
  {
    slug: 'horiatiki-greek-salad-details',
    parent: 'greek-salad-details',
    nazwa: 'Horiatiki',
    opis: 'Wiejska wersja z kaparami i papryką zieloną, w oryginalnych proporcjach.',
    porcje: 4,
    czasMinut: 15,
    skladniki: ['5 pomidorów', '1 ogórek', '1 papryka zielona', '1 cebula', '2 łyżki kaparów', '200 g fety', 'oliwki', 'oliwa, oregano'],
    kroki: [
      'Pokrój warzywa na duże, nierówne kawałki — to nie jest sałatka drobna.',
      'Dodaj kapary i oliwki.',
      'Skrop obficie oliwą i posól.',
      'Feta ląduje na wierzchu w całości, posypana oregano.',
    ],
  },
  {
    slug: 'greek-salad-with-avocado-details',
    parent: 'greek-salad-details',
    nazwa: 'Greek salad with avocado',
    opis: 'Nowoczesny wariant z awokado, które zastępuje część oliwy.',
    porcje: 4,
    czasMinut: 15,
    skladniki: ['3 pomidory', '1 ogórek', '2 awokado', '1 cebula', '150 g fety', 'sok z cytryny', 'oliwa', 'oregano'],
    kroki: [
      'Awokado pokrój w kostkę i skrop sokiem z cytryny.',
      'Wymieszaj z pomidorami, ogórkiem i cebulą.',
      'Pokrusz fetę.',
      'Skrop oliwą i posyp oregano.',
    ],
  },
  {
    slug: 'grilled-greek-salad-details',
    parent: 'greek-salad-details',
    nazwa: 'Grilled greek salad',
    opis: 'Z grillowaną papryką, cukinią i fetą podpieczoną w folii.',
    porcje: 4,
    czasMinut: 35,
    skladniki: ['2 papryki', '1 cukinia', '200 g fety', '3 pomidory', 'oliwki', 'oliwa', 'oregano', 'czosnek'],
    kroki: [
      'Paprykę i cukinię pokrój w grube plastry i grilluj po 3 minuty.',
      'Fetę zawiń w folię z oliwą i czosnkiem, piecz 15 minut w 200°C.',
      'Wymieszaj grillowane warzywa ze świeżymi pomidorami i oliwkami.',
      'Połóż ciepłą fetę na wierzchu.',
    ],
  },
  {
    slug: 'quinoa-greek-salad-details',
    parent: 'greek-salad-details',
    nazwa: 'Quinoa greek salad',
    opis: 'Sałatka grecka z komosą ryżową — sycąca, na lunch do pracy.',
    porcje: 4,
    czasMinut: 30,
    skladniki: ['200 g komosy ryżowej', '3 pomidory', '1 ogórek', '150 g fety', 'oliwki', 'natka pietruszki', 'sok z cytryny', 'oliwa'],
    kroki: [
      'Komosę wypłucz i ugotuj w 400 ml wody przez 15 minut, ostudź.',
      'Pokrój warzywa w drobną kostkę.',
      'Wymieszaj wszystko z pokruszoną fetą i natką.',
      'Dopraw sokiem z cytryny i oliwą.',
    ],
  },

  // ---------- Grilled bream ----------
  {
    slug: 'grilled-bream-with-lemon-butter-sauce-details',
    parent: 'grilled-bream-details',
    nazwa: 'Grilled bream with lemon butter sauce',
    opis: 'Dorada z grilla polana masłem cytrynowym — najprostszy sposób na tę rybę.',
    porcje: 2,
    czasMinut: 35,
    skladniki: ['2 dorady', '80 g masła', '1 cytryna', 'natka pietruszki', 'oliwa', 'sól, pieprz'],
    kroki: [
      'Ryby oczyść, natnij skórę co 2 cm i natrzyj solą.',
      'Do brzucha włóż plasterki cytryny.',
      'Grilluj po 6 minut z każdej strony, nie ruszając zbyt wcześnie.',
      'Roztop masło z sokiem z cytryny i natką, polej rybę.',
    ],
  },
  {
    slug: 'mediterranean-spicy-grilled-details',
    parent: 'grilled-bream-details',
    nazwa: 'Mediterranean spicy grilled bream',
    opis: 'Dorada w marynacie z harissy, czosnku i kminu rzymskiego.',
    porcje: 2,
    czasMinut: 60,
    skladniki: ['2 dorady', '2 łyżki harissy', '3 ząbki czosnku', '1 łyżeczka kminu rzymskiego', 'sok z cytryny', 'oliwa', 'kolendra'],
    kroki: [
      'Wymieszaj harissę z czosnkiem, kminem, oliwą i sokiem z cytryny.',
      'Natrzyj ryby marynatą, także w nacięciach, i odstaw na 30 minut.',
      'Grilluj po 6 minut z każdej strony.',
      'Posyp świeżą kolendrą.',
    ],
  },
  {
    slug: 'grilled-bream-with-herbs-details',
    parent: 'grilled-bream-details',
    nazwa: 'Grilled bream with herbs',
    opis: 'Dorada nadziewana pęczkiem ziół — tymianku, rozmarynu i natki.',
    porcje: 2,
    czasMinut: 35,
    skladniki: ['2 dorady', 'pęczek tymianku', 'pęczek rozmarynu', 'natka pietruszki', '1 cytryna', 'oliwa', 'sól gruboziarnista'],
    kroki: [
      'Brzuchy ryb wypełnij ziołami i plasterkami cytryny.',
      'Skórę natrzyj oliwą i solą.',
      'Grilluj po 6–7 minut z każdej strony.',
      'Odstaw na 3 minuty przed podaniem.',
    ],
  },
  {
    slug: 'spicy-grilled-bream-details',
    parent: 'grilled-bream-details',
    nazwa: 'Spicy grilled bream',
    opis: 'Ostra wersja z chili, imbirem i limonką.',
    porcje: 2,
    czasMinut: 45,
    skladniki: ['2 dorady', '2 papryczki chili', '20 g imbiru', '2 limonki', 'sos rybny', 'oliwa', 'kolendra'],
    kroki: [
      'Zblenduj chili, imbir, sok z limonki i sos rybny na marynatę.',
      'Natrzyj ryby i odstaw na 20 minut.',
      'Grilluj po 6 minut z każdej strony.',
      'Podawaj z ćwiartkami limonki i kolendrą.',
    ],
  },
  {
    slug: 'grilled-bream-with-garlic-aioli-details',
    parent: 'grilled-bream-details',
    nazwa: 'Grilled bream with garlic aioli',
    opis: 'Dorada z gęstym sosem czosnkowym aioli.',
    porcje: 2,
    czasMinut: 40,
    skladniki: ['2 dorady', '2 żółtka', '200 ml oliwy', '4 ząbki czosnku', 'sok z cytryny', 'sól'],
    kroki: [
      'Czosnek utrzyj w moździerzu z solą na pastę.',
      'Dodaj żółtka i wkraplaj oliwę, cały czas mieszając, aż sos zgęstnieje.',
      'Dopraw sokiem z cytryny.',
      'Ryby grilluj po 6 minut z każdej strony i podawaj z aioli.',
    ],
  },

  // ---------- Grilled chicken ----------
  {
    slug: 'bbq-grilled-chicken-details',
    parent: 'grilled-chicken-details',
    nazwa: 'BBQ grilled chicken',
    opis: 'Kurczak z grilla lakierowany sosem barbecue w kilku warstwach.',
    porcje: 4,
    czasMinut: 60,
    skladniki: ['1 kg podudzi i skrzydełek', '200 ml sosu BBQ', '2 łyżki miodu', 'papryka wędzona', 'czosnek w proszku', 'sól, pieprz'],
    kroki: [
      'Mięso natrzyj przyprawami i odstaw na 30 minut.',
      'Grilluj 20 minut po stronie kości, na średnim żarze.',
      'Posmaruj sosem i grilluj 5 minut; powtórz trzykrotnie.',
      'Sos nakładaj dopiero pod koniec — cukier w nim szybko się przypala.',
    ],
  },
  {
    slug: 'cajun-grilled-chicken-details',
    parent: 'grilled-chicken-details',
    nazwa: 'Cajun grilled chicken',
    opis: 'Pikantna mieszanka przypraw z Luizjany wcierana w mięso przed grillowaniem.',
    porcje: 4,
    czasMinut: 45,
    skladniki: ['4 piersi z kurczaka', '2 łyżki papryki', '1 łyżeczka pieprzu cayenne', 'czosnek w proszku', 'oregano', 'tymianek', 'oliwa', 'sól'],
    kroki: [
      'Wymieszaj wszystkie przyprawy na suchą mieszankę.',
      'Piersi rozbij do równej grubości, natrzyj oliwą i przyprawami.',
      'Odstaw na 20 minut.',
      'Grilluj po 5 minut z każdej strony i odstaw na 5 minut przed krojeniem.',
    ],
  },
  {
    slug: 'lemon-and-herbs-grilled-chicken-details',
    parent: 'grilled-chicken-details',
    nazwa: 'Lemon and herbs grilled chicken',
    opis: 'Kurczak w marynacie cytrynowo-ziołowej, lekki i soczysty.',
    porcje: 4,
    czasMinut: 90,
    skladniki: ['4 piersi z kurczaka', '2 cytryny', 'rozmaryn', 'tymianek', '4 ząbki czosnku', 'oliwa', 'sól, pieprz'],
    kroki: [
      'Marynata: sok i skórka z cytryn, oliwa, czosnek i posiekane zioła.',
      'Marynuj mięso przez godzinę, nie dłużej — kwas zaczyna je „gotować".',
      'Grilluj po 5–6 minut z każdej strony.',
      'Skrop świeżym sokiem przed podaniem.',
    ],
  },
  {
    slug: 'nediterranean-grilled-chicken-details',
    parent: 'grilled-chicken-details',
    nazwa: 'Mediterranean grilled chicken',
    opis: 'Kurczak w jogurcie z oregano i cytryną, w stylu greckim.',
    porcje: 4,
    czasMinut: 80,
    skladniki: ['4 piersi z kurczaka', '200 g jogurtu greckiego', '2 łyżki oregano', '1 cytryna', '3 ząbki czosnku', 'oliwa', 'sól'],
    kroki: [
      'Wymieszaj jogurt z czosnkiem, oregano i sokiem z cytryny.',
      'Marynuj mięso minimum godzinę — jogurt zmiękcza włókna.',
      'Zetrzyj nadmiar marynaty, żeby nie przypaliła się na ruszcie.',
      'Grilluj po 6 minut z każdej strony.',
    ],
  },
  {
    slug: 'teriyaki-grilled-chicken-details',
    parent: 'grilled-chicken-details',
    nazwa: 'Teriyaki grilled chicken',
    opis: 'Kurczak lakierowany japońskim sosem teriyaki na błyszcząco.',
    porcje: 4,
    czasMinut: 50,
    skladniki: ['4 udka z kurczaka bez kości', '100 ml sosu sojowego', '100 ml mirin', '2 łyżki cukru', '2 łyżki sake', 'imbir', 'sezam'],
    kroki: [
      'Zagotuj sos sojowy z mirin, sake i cukrem, redukuj do konsystencji syropu.',
      'Udka grilluj skórą do dołu przez 8 minut.',
      'Obróć, smaruj sosem i grilluj kolejne 6 minut, smarując dwukrotnie.',
      'Posyp sezamem i pokrój w paski.',
    ],
  },

  // ---------- Hunter's stew ----------
  {
    slug: 'polish-bigos-details',
    parent: 'hunters-stew-details',
    nazwa: 'Polish bigos',
    opis: 'Bigos z kapusty kiszonej i świeżej z kilkoma rodzajami mięsa, gotowany kilka dni.',
    porcje: 8,
    czasMinut: 300,
    skladniki: ['1 kg kapusty kiszonej', '500 g kapusty białej', '400 g karkówki', '300 g kiełbasy', '150 g boczku wędzonego', '30 g suszonych grzybów', 'śliwki suszone', 'ziele angielskie, liść laurowy'],
    kroki: [
      'Grzyby namocz przez noc, ugotuj i pokrój; wodę zachowaj.',
      'Kapustę kiszoną posiekaj, świeżą poszatkuj i podduś osobno.',
      'Mięsa obsmaż i pokrój w kostkę.',
      'Połącz wszystko w dużym garnku, dodaj śliwki i przyprawy.',
      'Duś 3 godziny, a następnego dnia zagotuj ponownie — bigos smakuje najlepiej za drugim razem.',
    ],
  },
  {
    slug: 'german-jäger-eintopf-details',
    parent: 'hunters-stew-details',
    nazwa: 'Jäger Eintopf',
    opis: 'Niemiecki jednogarnkowy gulasz myśliwski z grzybami, boczkiem i ziemniakami.',
    porcje: 6,
    czasMinut: 90,
    skladniki: ['600 g karkówki', '150 g boczku', '400 g pieczarek', '600 g ziemniaków', '2 cebule', '500 ml bulionu', '200 ml śmietany', 'majeranek'],
    kroki: [
      'Boczek wytop, obsmaż na nim mięso.',
      'Dodaj cebulę i pieczarki, smaż 8 minut.',
      'Wlej bulion, dorzuć ziemniaki i duś 40 minut.',
      'Wmieszaj śmietanę i majeranek na koniec.',
    ],
  },
  {
    slug: 'hungarian-gulyás-details',
    parent: 'hunters-stew-details',
    nazwa: 'Hungarian gulyás',
    opis: 'Węgierski gulyás jako zupa — rzadszy niż pörkölt, z ziemniakami i kluseczkami.',
    porcje: 6,
    czasMinut: 150,
    skladniki: ['700 g wołowiny', '3 cebule', '3 łyżki papryki mielonej', '600 g ziemniaków', '2 marchewki', '2 papryki', 'kminek', 'czosnek', 'smalec'],
    kroki: [
      'Cebulę smaż na smalcu do zbrązowienia.',
      'Zdejmij z ognia, wsyp paprykę i od razu wlej trochę wody.',
      'Dodaj mięso i duś 90 minut.',
      'Wrzuć warzywa i gotuj kolejne 30 minut, aż ziemniaki zmiękną.',
    ],
  },
  {
    slug: 'russian-solyanka-details',
    parent: 'hunters-stew-details',
    nazwa: 'Russian solyanka',
    opis: 'Kwaśno-słona zupa z kilku rodzajów wędlin, ogórków kiszonych i oliwek.',
    porcje: 6,
    czasMinut: 90,
    skladniki: ['400 g mieszanych wędlin', '200 g kiełbasy', '4 ogórki kiszone', '100 g oliwek', '2 łyżki koncentratu pomidorowego', '1,5 l bulionu', 'kapary', 'cytryna', 'śmietana'],
    kroki: [
      'Wędliny pokrój w paski i podsmaż.',
      'Ogórki pokrój w kostkę i poduś z koncentratem.',
      'Połącz z bulionem i gotuj 25 minut.',
      'Dodaj oliwki i kapary, podawaj z plasterkiem cytryny i śmietaną.',
    ],
  },
  {
    slug: 'french-cassoulet-details',
    parent: 'hunters-stew-details',
    nazwa: 'French cassoulet',
    opis: 'Zapiekanka z Langwedocji: biała fasola, kiełbasa i konfitowana kaczka pod skorupką z bułki tartej.',
    porcje: 6,
    czasMinut: 300,
    skladniki: ['500 g białej fasoli', '2 konfitowane udka kacze', '300 g kiełbasy tuluzkiej', '200 g boczku', '1 cebula', '2 marchewki', 'bulion', 'bułka tarta', 'tymianek'],
    kroki: [
      'Fasolę mocz przez noc, ugotuj z warzywami do miękkości.',
      'Kiełbasę i boczek obsmaż na złoto.',
      'Układaj warstwami w naczyniu żaroodpornym: fasola, mięso, fasola.',
      'Zalej bulionem, posyp bułką tartą.',
      'Piecz 2,5 godziny w 150°C, rozbijając skorupkę łyżką co 40 minut.',
    ],
  },
];
