// PLIK GENEROWANY — dane wyciagniete z 73 komponentow, ktore wczesniej
// trzymaly te same tablice zakodowane na sztywno, kazdy u siebie.
import { WezelMenu } from './menu.model';

export const MENU: WezelMenu[] = [
  {
    slug: 'beetroot-soup-details',
    tytul: 'Beetroot-soup',
    kategoria: false,
    dzieci: [
      { nazwa: 'Classic-borscht', slug: 'classic-borscht-details', obraz: 'assets/images/meals-obiady/beetroot-soup/Classic-borscht.png', dostepne: false },
      { nazwa: 'Ukrainian...', slug: 'ukrainian-borscht-details', obraz: 'assets/images/meals-obiady/beetroot-soup/Ukrainian....png', dostepne: false },
      { nazwa: 'Polish-barszcz', slug: 'polish-barszcz-details', obraz: 'assets/images/meals-obiady/beetroot-soup/Polish-barszcz.png', dostepne: false },
      { nazwa: 'Lithuanian...', slug: 'lithuanian-saltibarščiai-details', obraz: 'assets/images/meals-obiady/beetroot-soup/Lithuanian....png', dostepne: false },
      { nazwa: 'Russian...', slug: 'russian-svekolnik-details', obraz: 'assets/images/meals-obiady/beetroot-soup/Russian....png', dostepne: false },
    ],
  },
  {
    slug: 'boba-tea-details',
    tytul: 'Boba-tea',
    kategoria: false,
    dzieci: [
      { nazwa: 'Classic', slug: 'classic-boba-tea-details', obraz: 'assets/images/meals-sniadania/boba-tea/Classic.png', dostepne: false },
      { nazwa: 'Fruit', slug: 'fruit-boba-tea-details', obraz: 'assets/images/meals-sniadania/boba-tea/Fruit.png', dostepne: false },
      { nazwa: 'Matcha', slug: 'matcha-boba-tea-details', obraz: 'assets/images/meals-sniadania/boba-tea/Matcha.png', dostepne: false },
      { nazwa: 'Taro', slug: 'taro-boba-tea-details', obraz: 'assets/images/meals-sniadania/boba-tea/Taro.png', dostepne: false },
      { nazwa: 'Thai', slug: 'thai-boba-tea-details', obraz: 'assets/images/meals-sniadania/boba-tea/Thai.png', dostepne: false },
    ],
  },
  {
    slug: 'bread-with-oil-details',
    tytul: 'Bread-with-oil',
    kategoria: false,
    dzieci: [
      { nazwa: 'Ciabatta-with-oil', slug: 'ciabatta-with-oil-details', obraz: 'assets/images/meals-sniadania/bread-with-oil/Ciabatta-with-oil.png', dostepne: false },
      { nazwa: 'Baguette-with-oil', slug: 'baguette-with-oil-details', obraz: 'assets/images/meals-sniadania/bread-with-oil/Baguette-with-oil.png', dostepne: false },
      { nazwa: 'Greek-olive-bread', slug: 'greek-olive-bread-details', obraz: 'assets/images/meals-sniadania/bread-with-oil/Greek-olive-bread.png', dostepne: false },
      { nazwa: 'Herb-and-garlic', slug: 'herb-and-garlic-details', obraz: 'assets/images/meals-sniadania/bread-with-oil/Herb-and-garlic.png', dostepne: false },
    ],
  },
  {
    slug: 'bruschetta-details',
    tytul: 'Bruschetta',
    kategoria: false,
    dzieci: [
      { nazwa: 'Tomato-and...', slug: 'tomato-and-basil-details', obraz: 'assets/images/meals-sniadania/bruschetta/Tomato-and....png', dostepne: false },
      { nazwa: 'Mushroom-and...', slug: 'Mushroom-and-goat-cheese-details', obraz: 'assets/images/meals-sniadania/bruschetta/Mushroom-and....png', dostepne: false },
      { nazwa: 'Fig-and...', slug: 'fig-and-prosciutto-details', obraz: 'assets/images/meals-sniadania/bruschetta/Fig-and....png', dostepne: false },
      { nazwa: 'Avocado-and...', slug: 'avocado-and-tomato-details', obraz: 'assets/images/meals-sniadania/bruschetta/Avocado-and....png', dostepne: false },
      { nazwa: 'Peach-and...', slug: 'peach-and-burrata-details', obraz: 'assets/images/meals-sniadania/bruschetta/Peach-and....png', dostepne: false },
    ],
  },
  {
    slug: 'cabbage-rolls-details',
    tytul: 'Cabbage-rolls',
    kategoria: false,
    dzieci: [
      { nazwa: 'Polish-gołąbki', slug: 'polish-gołąbki-details', obraz: 'assets/images/meals-obiady/cabbage-rolls/Polish-gołąbki.png', dostepne: false },
      { nazwa: 'Ukrainian...', slug: 'ukrainian-holubtsi-details', obraz: 'assets/images/meals-obiady/cabbage-rolls/Ukrainian....png', dostepne: false },
      { nazwa: 'Turkish-lahana...', slug: 'turkish-lahana-sarma-details', obraz: 'assets/images/meals-obiady/cabbage-rolls/Turkish-lahana....png', dostepne: false },
      { nazwa: 'Romanian...', slug: 'romanian-sarmale-details', obraz: 'assets/images/meals-obiady/cabbage-rolls/Romanian....png', dostepne: false },
      { nazwa: 'Middle-eastern...', slug: 'middle-eastern-mahshi-malfouf-details', obraz: 'assets/images/meals-obiady/cabbage-rolls/Middle-eastern....png', dostepne: false },
    ],
  },
  {
    slug: 'calzone-details',
    tytul: 'Calzone',
    kategoria: false,
    dzieci: [
      { nazwa: 'Ham-and...', slug: 'ham-and-cheese-calzone-details', obraz: 'assets/images/meals-kolacje/calzone/Ham-and....png', dostepne: false },
      { nazwa: 'Mushroom', slug: 'mushroom-calzone-details', obraz: 'assets/images/meals-kolacje/calzone/Mushroom.png', dostepne: false },
      { nazwa: 'Vegetarian', slug: 'vegetarian-calzone-details', obraz: 'assets/images/meals-kolacje/calzone/Vegetarian.png', dostepne: false },
      { nazwa: 'Sausage', slug: 'sausage-calzone-details', obraz: 'assets/images/meals-kolacje/calzone/Sausage.png', dostepne: false },
      { nazwa: 'Ricotta-and...', slug: 'ricotta-and-spinach-calzone-details', obraz: 'assets/images/meals-kolacje/calzone/Ricotta-and....png', dostepne: false },
    ],
  },
  {
    slug: 'caprese-details',
    tytul: 'Caprese-salad',
    kategoria: false,
    dzieci: [
      { nazwa: 'With-tomatoes...', slug: 'caprese-with-tomatoes-and-mozzarella-details', obraz: 'assets/images/meals-kolacje/caprese/With-tomatoes....png', dostepne: false },
      { nazwa: 'Avocado', slug: 'avocado-caprese-details', obraz: 'assets/images/meals-kolacje/caprese/Avocado.png', dostepne: false },
      { nazwa: 'Sun-dried', slug: 'sun-dried-caprese-details', obraz: 'assets/images/meals-kolacje/caprese/Sun-dried.png', dostepne: false },
      { nazwa: 'Roasted-pepper', slug: 'roasted-pepper-caprese-details', obraz: 'assets/images/meals-kolacje/caprese/Roasted-pepper.png', dostepne: false },
      { nazwa: 'Arugula', slug: 'arugula-caprese-details', obraz: 'assets/images/meals-kolacje/caprese/Arugula.png', dostepne: false },
    ],
  },
  {
    slug: 'cheeseburger-details',
    tytul: 'Cheeseburger',
    kategoria: false,
    dzieci: [
      { nazwa: 'Classic', slug: 'classic-cheesburger-details', obraz: 'assets/images/meals-obiady/cheeseburger/Classic.png', dostepne: false },
      { nazwa: 'Bacon', slug: 'bacon-cheesburger-details', obraz: 'assets/images/meals-obiady/cheeseburger/Bacon.png', dostepne: false },
      { nazwa: 'Mushroom-swiss', slug: 'mushroom-swiss-cheesburger-details', obraz: 'assets/images/meals-obiady/cheeseburger/Mushroom-swiss.png', dostepne: false },
      { nazwa: 'BBQ', slug: 'bbq-cheesburger-details', obraz: 'assets/images/meals-obiady/cheeseburger/BBQ.png', dostepne: false },
      { nazwa: 'Jalapeno-pepper', slug: 'jalapeno-pepper-cheesburger-details', obraz: 'assets/images/meals-obiady/cheeseburger/Jalapeno-pepper.png', dostepne: false },
    ],
  },
  {
    slug: 'cod-fillet-details',
    tytul: 'Cod-fillet',
    kategoria: false,
    dzieci: [
      { nazwa: 'Baked-with...', slug: 'baked-cod-fllet-with-lemon-and-herbs-details', obraz: 'assets/images/meals-kolacje/cod-fillet/Baked-with....png', dostepne: false },
      { nazwa: 'Pan-seared...', slug: 'pan-seared-cod-fllet-with-tomato-sauce-details', obraz: 'assets/images/meals-kolacje/cod-fillet/Pan-seared....png', dostepne: false },
      { nazwa: 'Grilled-with...', slug: 'grilled-cod-fllet-with-garlic-butter-details', obraz: 'assets/images/meals-kolacje/cod-fillet/Grilled-with....png', dostepne: false },
      { nazwa: 'Crispy-with...', slug: 'crispy-cod-fllet-with-tartar-sauce-details', obraz: 'assets/images/meals-kolacje/cod-fillet/Crispy-with....png', dostepne: false },
      { nazwa: 'Steamed-with...', slug: 'steamed-cod-fllet-with-ginger-and-soy-sauce-details', obraz: 'assets/images/meals-kolacje/cod-fillet/Steamed-with....png', dostepne: false },
    ],
  },
  {
    slug: 'confit-de-canard-details',
    tytul: 'Confit-de-canard',
    kategoria: false,
    dzieci: [
      { nazwa: 'Traditional', slug: 'traditional-confit-de-canard-details', obraz: 'assets/images/meals-kolacje/confit-de-canard/Traditional.png', dostepne: false },
      { nazwa: 'Confit-duck-o...', slug: 'confit-duck-leg-with-orange-sauce-details', obraz: 'assets/images/meals-kolacje/confit-de-canard/Confit-duck-o....png', dostepne: false },
      { nazwa: 'Confit-duck-ch...', slug: 'confit-duck-leg-with-cherry-sauce-details', obraz: 'assets/images/meals-kolacje/confit-de-canard/Confit-duck-ch....png', dostepne: false },
      { nazwa: 'Confit-duck-w...', slug: 'confit-duck-leg-with-red-wine-sauce-details', obraz: 'assets/images/meals-kolacje/confit-de-canard/Confit-duck-w....png', dostepne: false },
      { nazwa: 'Confit-duck-s...', slug: 'confit-duck-leg-salad-details', obraz: 'assets/images/meals-kolacje/confit-de-canard/Confit-duck-s....png', dostepne: false },
    ],
  },
  {
    slug: 'coq-au-vin-details',
    tytul: 'Coq-au-vin',
    kategoria: false,
    dzieci: [
      { nazwa: 'Traditional', slug: 'traditional-coq-au-vin-details', obraz: 'assets/images/meals-obiady/coq-au-vin/Traditional.png', dostepne: false },
      { nazwa: 'White-wine', slug: 'white-coq-au-vin-wine-details', obraz: 'assets/images/meals-obiady/coq-au-vin/White-wine.png', dostepne: false },
      { nazwa: 'Mushroom', slug: 'mushroom-coq-au-vin-details', obraz: 'assets/images/meals-obiady/coq-au-vin/Mushroom.png', dostepne: false },
      { nazwa: 'Vegetable', slug: 'vegetable-coq-au-vin-details', obraz: 'assets/images/meals-obiady/coq-au-vin/Vegetable.png', dostepne: false },
      { nazwa: 'Seafood', slug: 'seafood-coq-au-vin-details', obraz: 'assets/images/meals-obiady/coq-au-vin/Seafood.png', dostepne: false },
    ],
  },
  {
    slug: 'crepes-details',
    tytul: 'Crepes',
    kategoria: false,
    dzieci: [
      { nazwa: 'Suzette', slug: 'suzette-details', obraz: 'assets/images/meals-sniadania/crepes/Suzette.png', dostepne: false },
      { nazwa: 'Chocolate', slug: 'chocolate-details', obraz: 'assets/images/meals-sniadania/crepes/Chocolate.png', dostepne: false },
      { nazwa: 'Savory', slug: 'savory-details', obraz: 'assets/images/meals-sniadania/crepes/Savory.png', dostepne: false },
      { nazwa: 'Berry', slug: 'berry-details', obraz: 'assets/images/meals-sniadania/crepes/Berry.png', dostepne: false },
      { nazwa: 'Banana-nutella', slug: 'banana-nutella-details', obraz: 'assets/images/meals-sniadania/crepes/Banana-nutella.png', dostepne: false },
    ],
  },
  {
    slug: 'croissant-details',
    tytul: 'Breakfast',
    kategoria: false,
    dzieci: [
      { nazwa: 'Classic-butter', slug: 'classic-butter-details', obraz: 'assets/images/meals-sniadania/croissant/Classic-butter.png', dostepne: false },
      { nazwa: 'Almond', slug: 'almond-details', obraz: 'assets/images/meals-sniadania/croissant/Almond.png', dostepne: false },
      { nazwa: 'Chocolate', slug: 'chocolate-details', obraz: 'assets/images/meals-sniadania/croissant/Chocolate.png', dostepne: false },
      { nazwa: 'Ham-and-cheese', slug: 'ham-and-cheese-details', obraz: 'assets/images/meals-sniadania/croissant/Ham-and-cheese.png', dostepne: false },
      { nazwa: 'Fruit-filled', slug: 'fruit-filled-details', obraz: 'assets/images/meals-sniadania/croissant/Fruit-filled.png', dostepne: false },
    ],
  },
  {
    slug: 'curry-details',
    tytul: 'Curry',
    kategoria: false,
    dzieci: [
      { nazwa: 'Chicken', slug: 'chicken-curry-details', obraz: 'assets/images/meals-kolacje/curry/Chicken.png', dostepne: false },
      { nazwa: 'Lamb', slug: 'lamb-curry-details', obraz: 'assets/images/meals-kolacje/curry/Lamb.png', dostepne: false },
      { nazwa: 'Vegetable', slug: 'vegetable-curry-details', obraz: 'assets/images/meals-kolacje/curry/Vegetable.png', dostepne: false },
      { nazwa: 'Fish', slug: 'fish-curry-details', obraz: 'assets/images/meals-kolacje/curry/Fish.png', dostepne: false },
      { nazwa: 'Beef', slug: 'beef-curry-details', obraz: 'assets/images/meals-kolacje/curry/Beef.png', dostepne: false },
    ],
  },
  {
    slug: 'dim-sum-details',
    tytul: 'Dim-sum',
    kategoria: false,
    dzieci: [
      { nazwa: 'Shumai', slug: 'shumai-details', obraz: 'assets/images/meals-sniadania/dim-sum/Shumai.png', dostepne: false },
      { nazwa: 'Har-gow', slug: 'har-gow-details', obraz: 'assets/images/meals-sniadania/dim-sum/Har-gow.png', dostepne: false },
      { nazwa: 'Char-siu-bao', slug: 'char-siu-bao-details', obraz: 'assets/images/meals-sniadania/dim-sum/Char-siu-bao.png', dostepne: false },
      { nazwa: 'Cheung-fun', slug: 'cheung-fun-details', obraz: 'assets/images/meals-sniadania/dim-sum/Cheung-fun.png', dostepne: false },
      { nazwa: 'Turnip-cake', slug: 'turnip-cake-details', obraz: 'assets/images/meals-sniadania/dim-sum/Turnip-cake.png', dostepne: false },
    ],
  },
  {
    slug: 'donburi-details',
    tytul: 'Donburi',
    kategoria: false,
    dzieci: [
      { nazwa: 'Katsu-don', slug: 'katsu-don-details', obraz: 'assets/images/meals-obiady/donburi/Katsu-don.png', dostepne: false },
      { nazwa: 'Oyako-don', slug: 'oyako-don-details', obraz: 'assets/images/meals-obiady/donburi/Oyako-don.png', dostepne: false },
      { nazwa: 'Gyudon', slug: 'gyudon-details', obraz: 'assets/images/meals-obiady/donburi/Gyudon.png', dostepne: false },
      { nazwa: 'Tekka-don', slug: 'tekka-don-details', obraz: 'assets/images/meals-obiady/donburi/Tekka-don.png', dostepne: false },
      { nazwa: 'Unagi-don', slug: 'unagi-don-details', obraz: 'assets/images/meals-obiady/donburi/Unagi-don.png', dostepne: false },
    ],
  },
  {
    slug: 'dumplings-details',
    tytul: 'Dumplings',
    kategoria: false,
    dzieci: [
      { nazwa: 'Chinese', slug: 'chinese-dumplings-details', obraz: 'assets/images/meals-obiady/dumplings/Chinese.png', dostepne: false },
      { nazwa: 'Japanese', slug: 'japanese-dumplings-details', obraz: 'assets/images/meals-obiady/dumplings/Japanese.png', dostepne: false },
      { nazwa: 'Korean', slug: 'korean-dumplings-details', obraz: 'assets/images/meals-obiady/dumplings/Korean.png', dostepne: false },
      { nazwa: 'Polish', slug: 'polish-dumplings-details', obraz: 'assets/images/meals-obiady/dumplings/Polish.png', dostepne: false },
      { nazwa: 'Tibetan', slug: 'tibetan-dumplings-details', obraz: 'assets/images/meals-obiady/dumplings/Tibetan.png', dostepne: false },
    ],
  },
  {
    slug: 'eggs-details',
    tytul: 'Eggs',
    kategoria: false,
    dzieci: [
      { nazwa: 'Deviled', slug: 'deviled-details', obraz: 'assets/images/meals-sniadania/eggs/Deviled.png', dostepne: false },
      { nazwa: 'Florentine', slug: 'florentine-details', obraz: 'assets/images/meals-sniadania/eggs/Florentine.png', dostepne: false },
      { nazwa: 'Royale', slug: 'royale-details', obraz: 'assets/images/meals-sniadania/eggs/Royale.png', dostepne: false },
    ],
  },
  {
    slug: 'focaccia-details',
    tytul: 'Focaccia',
    kategoria: false,
    dzieci: [
      { nazwa: 'Classic', slug: 'classic-focaccia-details', obraz: 'assets/images/meals-obiady/focaccia/Classic.png', dostepne: false },
      { nazwa: 'Rosemary', slug: 'rosemary-focaccia-details', obraz: 'assets/images/meals-obiady/focaccia/Rosemary.png', dostepne: false },
      { nazwa: 'Tomato-and...', slug: 'tomato-and-basil-focaccia-details', obraz: 'assets/images/meals-obiady/focaccia/Tomato-and....png', dostepne: false },
      { nazwa: 'Onion', slug: 'onion-focaccia-details', obraz: 'assets/images/meals-obiady/focaccia/Onion.png', dostepne: false },
      { nazwa: 'Olive', slug: 'olive-focaccia-details', obraz: 'assets/images/meals-obiady/focaccia/Olive.png', dostepne: false },
    ],
  },
  {
    slug: 'goulash-details',
    tytul: 'Goulash',
    kategoria: false,
    dzieci: [
      { nazwa: 'Beef', slug: 'beef-goulash-details', obraz: 'assets/images/meals-kolacje/goulash/Beef.png', dostepne: false },
      { nazwa: 'Pork', slug: 'pork-goulash-details', obraz: 'assets/images/meals-kolacje/goulash/Pork.png', dostepne: false },
      { nazwa: 'Chicken', slug: 'chicken-goulash-details', obraz: 'assets/images/meals-kolacje/goulash/Chicken.png', dostepne: false },
      { nazwa: 'Lamb', slug: 'lamb-goulash-details', obraz: 'assets/images/meals-kolacje/goulash/Lamb.png', dostepne: false },
      { nazwa: 'Vegetarian', slug: 'vegetarian-goulash-details', obraz: 'assets/images/meals-kolacje/goulash/Vegetarian.png', dostepne: false },
    ],
  },
  {
    slug: 'greek-salad-details',
    tytul: 'Greek-salad',
    kategoria: false,
    dzieci: [
      { nazwa: 'Classic', slug: 'classic-greek-salad-details', obraz: 'assets/images/meals-obiady/greek-salad/Classic.png', dostepne: false },
      { nazwa: 'Horiatiki', slug: 'horiatiki-greek-salad-details', obraz: 'assets/images/meals-obiady/greek-salad/Horiatiki.png', dostepne: false },
      { nazwa: 'With-avocado', slug: 'greek-salad-with-avocado-details', obraz: 'assets/images/meals-obiady/greek-salad/With-avocado.png', dostepne: false },
      { nazwa: 'Grilled', slug: 'grilled-greek-salad-details', obraz: 'assets/images/meals-obiady/greek-salad/Grilled.png', dostepne: false },
      { nazwa: 'Quinoa', slug: 'quinoa-greek-salad-details', obraz: 'assets/images/meals-obiady/greek-salad/Quinoa.png', dostepne: false },
    ],
  },
  {
    slug: 'grilled-bream-details',
    tytul: 'Grilled-bream',
    kategoria: false,
    dzieci: [
      { nazwa: 'With-lemon...', slug: 'grilled-bream-with-lemon-butter-sauce-details', obraz: 'assets/images/meals-kolacje/grilled-bream/With-lemon....png', dostepne: false },
      { nazwa: 'Mediterranean', slug: 'mediterranean-spicy-grilled-details', obraz: 'assets/images/meals-kolacje/grilled-bream/Mediterranean.png', dostepne: false },
      { nazwa: 'With-herbs', slug: 'grilled-bream-with-herbs-details', obraz: 'assets/images/meals-kolacje/grilled-bream/With-herbs.png', dostepne: false },
      { nazwa: 'Spicy', slug: 'spicy-grilled-bream-details', obraz: 'assets/images/meals-kolacje/grilled-bream/Spicy.png', dostepne: false },
      { nazwa: 'With-garlic...', slug: 'grilled-bream-with-garlic-aioli-details', obraz: 'assets/images/meals-kolacje/grilled-bream/With-garlic....png', dostepne: false },
    ],
  },
  {
    slug: 'grilled-chicken-details',
    tytul: 'Grilled-chicken',
    kategoria: false,
    dzieci: [
      { nazwa: 'BBQ', slug: 'bbq-grilled-chicken-details', obraz: 'assets/images/meals-kolacje/grilled-chicken/BBQ.png', dostepne: false },
      { nazwa: 'Cajun', slug: 'cajun-grilled-chicken-details', obraz: 'assets/images/meals-kolacje/grilled-chicken/Cajun.png', dostepne: false },
      { nazwa: 'Lemon-and...', slug: 'lemon-and-herbs-grilled-chicken-details', obraz: 'assets/images/meals-kolacje/grilled-chicken/Lemon-and....png', dostepne: false },
      { nazwa: 'Mediterranean', slug: 'nediterranean-grilled-chicken-details', obraz: 'assets/images/meals-kolacje/grilled-chicken/Mediterranean.png', dostepne: false },
      { nazwa: 'Teriyaki', slug: 'teriyaki-grilled-chicken-details', obraz: 'assets/images/meals-kolacje/grilled-chicken/Teriyaki.png', dostepne: false },
    ],
  },
  {
    slug: 'hunters-stew-details',
    tytul: 'Hunter\'s-stew',
    kategoria: false,
    dzieci: [
      { nazwa: 'Polish-bigos', slug: 'polish-bigos-details', obraz: 'assets/images/meals-obiady/hunters-stew/Polish-bigos.png', dostepne: false },
      { nazwa: 'German-jäger...', slug: 'german-jäger-eintopf-details', obraz: 'assets/images/meals-obiady/hunters-stew/German-jäger....png', dostepne: false },
      { nazwa: 'Hungarian...', slug: 'hungarian-gulyás-details', obraz: 'assets/images/meals-obiady/hunters-stew/Hungarian....png', dostepne: false },
      { nazwa: 'Russian...', slug: 'russian-solyanka-details', obraz: 'assets/images/meals-obiady/hunters-stew/Russian....png', dostepne: false },
      { nazwa: 'French-cassoulet', slug: 'french-cassoulet-details', obraz: 'assets/images/meals-obiady/hunters-stew/French-cassoulet.png', dostepne: false },
    ],
  },
  {
    slug: 'kashotto-details',
    tytul: 'Kashotto',
    kategoria: false,
    dzieci: [
      { nazwa: 'Mushroom', slug: 'mushroom-kashotto-details', obraz: 'assets/images/meals-kolacje/kashotto/Mushroom.png', dostepne: false },
      { nazwa: 'Pumpkin-and...', slug: 'pumpkin-and-sage-kashotto-details', obraz: 'assets/images/meals-kolacje/kashotto/Pumpkin-and....png', dostepne: false },
      { nazwa: 'Spinach-and...', slug: 'spinach-and-feta-kashotto-details', obraz: 'assets/images/meals-kolacje/kashotto/Spinach-and....png', dostepne: false },
      { nazwa: 'Butternut...', slug: 'butternut-squash-and-walnut-kashotto-details', obraz: 'assets/images/meals-kolacje/kashotto/Butternut....png', dostepne: false },
      { nazwa: 'Asparagus...', slug: 'asparagus-and-lemon-kashotto-details', obraz: 'assets/images/meals-kolacje/kashotto/Asparagus....png', dostepne: false },
    ],
  },
  {
    slug: 'kolacja',
    tytul: 'Supper',
    kategoria: true,
    dzieci: [
      { nazwa: 'Goulash', slug: 'goulash-details', obraz: 'assets/images/kolacje/Goulash.png', dostepne: true, kuchnia: 'American' },
      { nazwa: 'Grilled-chicken', slug: 'grilled-chicken-details', obraz: 'assets/images/kolacje/Grilled-chicken.png', dostepne: true, kuchnia: 'American' },
      { nazwa: 'Pasta', slug: 'pasta-details', obraz: 'assets/images/kolacje/Pasta.png', dostepne: true, kuchnia: 'American' },
      { nazwa: 'Sashimi', slug: 'sashimi-details', obraz: 'assets/images/kolacje/Sashimi.png', dostepne: true, kuchnia: 'Japanese' },
      { nazwa: 'Yakisoba', slug: 'yakisoba-details', obraz: 'assets/images/kolacje/Yakisoba.png', dostepne: true, kuchnia: 'Japanese' },
      { nazwa: 'Tonkatsu', slug: 'tonkatsu-details', obraz: 'assets/images/kolacje/Tonkatsu.png', dostepne: true, kuchnia: 'Japanese' },
      { nazwa: 'Udon', slug: 'udon-details', obraz: 'assets/images/kolacje/Udon.png', dostepne: true, kuchnia: 'Japanese' },
      { nazwa: 'Tagliatelle', slug: 'tagliatelle-details', obraz: 'assets/images/kolacje/Tagliatelle.png', dostepne: true, kuchnia: 'Italian' },
      { nazwa: 'Osso-buco', slug: 'osso-buco-details', obraz: 'assets/images/kolacje/Osso-buco.png', dostepne: true, kuchnia: 'Italian' },
      { nazwa: 'Calzone', slug: 'calzone-details', obraz: 'assets/images/kolacje/Calzone.png', dostepne: true, kuchnia: 'Italian' },
      { nazwa: 'Caprese', slug: 'caprese-details', obraz: 'assets/images/kolacje/Caprese.png', dostepne: true, kuchnia: 'Italian' },
      { nazwa: 'Grilled-bream', slug: 'grilled-bream-details', obraz: 'assets/images/kolacje/Grilled-bream.png', dostepne: true, kuchnia: 'Mediterranean' },
      { nazwa: 'Tandoori', slug: 'tandoori-details', obraz: 'assets/images/kolacje/Tandoori.png', dostepne: true, kuchnia: 'Asian' },
      { nazwa: 'Pho', slug: 'pho-details', obraz: 'assets/images/kolacje/Pho.png', dostepne: true, kuchnia: 'Asian' },
      { nazwa: 'Curry', slug: 'curry-details', obraz: 'assets/images/kolacje/Curry.png', dostepne: true, kuchnia: 'Asian' },
      { nazwa: 'Confit-de-canard', slug: 'confit-de-canard-details', obraz: 'assets/images/kolacje/Confit-de-canard.png', dostepne: true, kuchnia: 'Continental' },
      { nazwa: 'Cod-fillet', slug: 'cod-fillet-details', obraz: 'assets/images/kolacje/Cod-fillet.png', dostepne: true, kuchnia: 'Continental' },
      { nazwa: 'Ravioli', slug: 'ravioli-details', obraz: 'assets/images/kolacje/Ravioli.png', dostepne: true, kuchnia: 'Continental' },
      { nazwa: 'Potato-cakes', slug: 'potato-cakes-details', obraz: 'assets/images/kolacje/Potato-cakes.png', dostepne: true, kuchnia: 'Regional' },
      { nazwa: 'Vegetable-salad', slug: 'vegetable-salad-details', obraz: 'assets/images/kolacje/Vegetable-salad.png', dostepne: true, kuchnia: 'Regional' },
      { nazwa: 'Kashotto', slug: 'kashotto-details', obraz: 'assets/images/kolacje/Kashotto.png', dostepne: true, kuchnia: 'Regional' },
      { nazwa: 'Sweet-crepes', slug: 'sweet-crepes-details', obraz: 'assets/images/kolacje/Sweet-crepes.png', dostepne: true, kuchnia: 'Regional' },
    ],
  },
  {
    slug: 'kung-pao-details',
    tytul: 'Kung-pao',
    kategoria: false,
    dzieci: [
      { nazwa: 'Chicken', slug: 'chicken-kung-pao-details', obraz: 'assets/images/meals-obiady/kung-pao/Chicken.png', dostepne: false },
      { nazwa: 'Shrimp', slug: 'shrimp-kung-pao-details', obraz: 'assets/images/meals-obiady/kung-pao/Shrimp.png', dostepne: false },
      { nazwa: 'Tofu', slug: 'tofu-kung-pao-details', obraz: 'assets/images/meals-obiady/kung-pao/Tofu.png', dostepne: false },
      { nazwa: 'Beef', slug: 'beef-kung-pao-details', obraz: 'assets/images/meals-obiady/kung-pao/Beef.png', dostepne: false },
      { nazwa: 'Pork', slug: 'pork-kung-pao-details', obraz: 'assets/images/meals-obiady/kung-pao/Pork.png', dostepne: false },
    ],
  },
  {
    slug: 'lasagne-details',
    tytul: 'Lasagne',
    kategoria: false,
    dzieci: [
      { nazwa: 'Beef', slug: 'beef-lasagne-details', obraz: 'assets/images/meals-obiady/lasagne/Beef.png', dostepne: false },
      { nazwa: 'Vegetarian', slug: 'vegetarian-lasagne-details', obraz: 'assets/images/meals-obiady/lasagne/Vegetarian.png', dostepne: false },
      { nazwa: 'Seafood', slug: 'seafood-lasagne-details', obraz: 'assets/images/meals-obiady/lasagne/Seafood.png', dostepne: false },
      { nazwa: 'Chicken-and...', slug: 'chicken-and-spinach-lasagne-details', obraz: 'assets/images/meals-obiady/lasagne/Chicken-and....png', dostepne: false },
      { nazwa: 'Four-cheese', slug: 'four-cheese-lasagne-details', obraz: 'assets/images/meals-obiady/lasagne/Four-cheese.png', dostepne: false },
    ],
  },
  {
    slug: 'miso-details',
    tytul: 'Miso-Soup',
    kategoria: false,
    dzieci: [
      { nazwa: 'With-tofu-and...', slug: 'with-tofu-and-wakame-details', obraz: 'assets/images/meals-sniadania/miso/With-tofu-and....png', dostepne: false },
      { nazwa: 'With-mushroom', slug: 'with-mushroom-details', obraz: 'assets/images/meals-sniadania/miso/With-mushroom.png', dostepne: false },
      { nazwa: 'With-vegetables', slug: 'with-vegetables-details', obraz: 'assets/images/meals-sniadania/miso/With-vegetables.png', dostepne: false },
      { nazwa: 'With-clams', slug: 'with-clams-details', obraz: 'assets/images/meals-sniadania/miso/With-clams.png', dostepne: false },
      { nazwa: 'Spicy', slug: 'spicy-details', obraz: 'assets/images/meals-sniadania/miso/Spicy.png', dostepne: false },
    ],
  },
  {
    slug: 'muesli-details',
    tytul: 'Muesli',
    kategoria: false,
    dzieci: [
      { nazwa: 'Classic', slug: 'classic-details', obraz: 'assets/images/meals-sniadania/muesli/Classic.png', dostepne: false },
      { nazwa: 'Bircher', slug: 'bircher-details', obraz: 'assets/images/meals-sniadania/muesli/Bircher.png', dostepne: false },
      { nazwa: 'Nutty', slug: 'nutty-details', obraz: 'assets/images/meals-sniadania/muesli/Nutty.png', dostepne: false },
      { nazwa: 'Berry', slug: 'berry-details', obraz: 'assets/images/meals-sniadania/muesli/Berry.png', dostepne: false },
      { nazwa: 'Chocolate', slug: 'chocolate-details', obraz: 'assets/images/meals-sniadania/muesli/Chocolate.png', dostepne: false },
    ],
  },
  {
    slug: 'mushroom-soup-details',
    tytul: 'Mushroom-soup',
    kategoria: false,
    dzieci: [
      { nazwa: 'Cream-of', slug: 'cream-of-mushroom-soup-details', obraz: 'assets/images/meals-obiady/mushroom-soup/Cream-of.png', dostepne: false },
      { nazwa: 'Wild', slug: 'wild-mushroom-soup-details', obraz: 'assets/images/meals-obiady/mushroom-soup/Wild.png', dostepne: false },
      { nazwa: 'Barley', slug: 'barley-mushroom-soup-details', obraz: 'assets/images/meals-obiady/mushroom-soup/Barley.png', dostepne: false },
      { nazwa: 'Miso', slug: 'miso-mushroom-soup-details', obraz: 'assets/images/meals-obiady/mushroom-soup/Miso.png', dostepne: false },
      { nazwa: 'Creamy-with...', slug: 'creamy-with-potato-mushroom-soup-details', obraz: 'assets/images/meals-obiady/mushroom-soup/Creamy-with....png', dostepne: false },
    ],
  },
  {
    slug: 'oatmeal-details',
    tytul: 'Oatmeal',
    kategoria: false,
    dzieci: [
      { nazwa: 'Classic', slug: 'classic-details', obraz: 'assets/images/meals-sniadania/oatmeal/Classic.png', dostepne: false },
      { nazwa: 'Apple-cinnamon', slug: 'apple-cinnamon-details', obraz: 'assets/images/meals-sniadania/oatmeal/Apple-cinnamon.png', dostepne: false },
      { nazwa: 'Banana-nut', slug: 'banana-nut-details', obraz: 'assets/images/meals-sniadania/oatmeal/Banana-nut.png', dostepne: false },
      { nazwa: 'Berry-blast', slug: 'berry-blast-details', obraz: 'assets/images/meals-sniadania/oatmeal/Berry-blast.png', dostepne: false },
      { nazwa: 'Pumpkin-spice', slug: 'pumpkin-spice-details', obraz: 'assets/images/meals-sniadania/oatmeal/Pumpkin-spice.png', dostepne: false },
    ],
  },
  {
    slug: 'obiad',
    tytul: 'Dinner',
    kategoria: true,
    dzieci: [
      { nazwa: 'Beetroot-soup', slug: 'beetroot-soup-details', obraz: 'assets/images/obiady/Beetroot-soup.png', dostepne: true, kuchnia: 'Regional' },
      { nazwa: 'Hunters-stew', slug: 'hunters-stew-details', obraz: 'assets/images/obiady/Hunters-stew.png', dostepne: true, kuchnia: 'Regional' },
      { nazwa: 'Cabbage-rolls', slug: 'cabbage-rolls-details', obraz: 'assets/images/obiady/Cabbage-rolls.png', dostepne: true, kuchnia: 'Regional' },
      { nazwa: 'Mushroom-soup', slug: 'mushroom-soup-details', obraz: 'assets/images/obiady/Mushroom-soup.png', dostepne: true, kuchnia: 'Regional' },
      { nazwa: 'Dumplings', slug: 'dumplings-details', obraz: 'assets/images/obiady/Dumplings.png', dostepne: true, kuchnia: 'Regional' },
      { nazwa: 'Silesian-noodles', slug: 'silesian-noodles-details', obraz: 'assets/images/obiady/Silesian-noodles.png', dostepne: true, kuchnia: 'Regional' },
      { nazwa: 'Pork-cutlet', slug: 'pork-cutlet-details', obraz: 'assets/images/obiady/Pork-cutlet.png', dostepne: true, kuchnia: 'Regional' },
      { nazwa: 'Sour-rye-soup', slug: 'sour-rye-soup-details', obraz: 'assets/images/obiady/Sour-rye-soup.png', dostepne: true, kuchnia: 'Regional' },
      { nazwa: 'Cheeseburger', slug: 'cheeseburger-details', obraz: 'assets/images/obiady/Cheeseburger.png', dostepne: true, kuchnia: 'American' },
      { nazwa: 'Pork-ribbs', slug: 'pork-ribbs-details', obraz: 'assets/images/obiady/Pork-ribbs.png', dostepne: true, kuchnia: 'American' },
      { nazwa: 'Ramen', slug: 'ramen-details', obraz: 'assets/images/obiady/Ramen.png', dostepne: true, kuchnia: 'Japanese' },
      { nazwa: 'Donburi', slug: 'donburi-details', obraz: 'assets/images/obiady/Donburi.png', dostepne: true, kuchnia: 'Japanese' },
      { nazwa: 'Pizza', slug: 'pizza-details', obraz: 'assets/images/obiady/Pizza.png', dostepne: true, kuchnia: 'Italian' },
      { nazwa: 'Risotto', slug: 'risotto-details', obraz: 'assets/images/obiady/Risotto.png', dostepne: true, kuchnia: 'Italian' },
      { nazwa: 'Spaghetti', slug: 'spaghetti-details', obraz: 'assets/images/obiady/Spaghetti.png', dostepne: true, kuchnia: 'Italian' },
      { nazwa: 'Greek-salad', slug: 'greek-salad-details', obraz: 'assets/images/obiady/Greek-salad.png', dostepne: true, kuchnia: 'Mediteranan' },
      { nazwa: 'Trout', slug: 'trout-details', obraz: 'assets/images/obiady/Trout.png', dostepne: true, kuchnia: 'Mediteranan' },
      { nazwa: 'Focaccia', slug: 'focaccia-details', obraz: 'assets/images/obiady/Focaccia.png', dostepne: true, kuchnia: 'Mediteranan' },
      { nazwa: 'Kung-pao', slug: 'kung-pao-details', obraz: 'assets/images/obiady/Kung-pao.png', dostepne: true, kuchnia: 'Asian' },
      { nazwa: 'Pad-thai', slug: 'pad-thai-details', obraz: 'assets/images/obiady/Pad-thai.png', dostepne: true, kuchnia: 'Asian' },
      { nazwa: 'Sushi', slug: 'sushi-details', obraz: 'assets/images/obiady/Sushi.png', dostepne: true, kuchnia: 'Asian' },
      { nazwa: 'Ratatouille', slug: 'ratatouille-details', obraz: 'assets/images/obiady/Ratatouille.png', dostepne: true, kuchnia: 'Continental' },
      { nazwa: 'Lasagne', slug: 'lasagne-details', obraz: 'assets/images/obiady/Lasagne.png', dostepne: true, kuchnia: 'Continental' },
      { nazwa: 'Paella', slug: 'paella-details', obraz: 'assets/images/obiady/Paella.png', dostepne: true, kuchnia: 'Continental' },
      { nazwa: 'Coq-au-vin', slug: 'coq-au-vin-details', obraz: 'assets/images/obiady/Coq-au-vin.png', dostepne: true, kuchnia: 'Continental' },
    ],
  },
  {
    slug: 'okonomiyaki-details',
    tytul: 'Okonomiyaki',
    kategoria: false,
    dzieci: [
      { nazwa: 'Classic', slug: 'classic-details', obraz: 'assets/images/meals-sniadania/okonomiyaki/Classic.png', dostepne: false },
      { nazwa: 'Hiroshima', slug: 'hiroshima-details', obraz: 'assets/images/meals-sniadania/okonomiyaki/Hiroshima.png', dostepne: false },
      { nazwa: 'Seafood', slug: 'seafood-details', obraz: 'assets/images/meals-sniadania/okonomiyaki/Seafood.png', dostepne: false },
      { nazwa: 'Vegetarian', slug: 'vegetarian-details', obraz: 'assets/images/meals-sniadania/okonomiyaki/Vegetarian.png', dostepne: false },
      { nazwa: 'Modern-fusion', slug: 'modern-fusion-details', obraz: 'assets/images/meals-sniadania/okonomiyaki/Modern-fusion.png', dostepne: false },
    ],
  },
  {
    slug: 'omelette-details',
    tytul: 'Omelette',
    kategoria: false,
    dzieci: [
      { nazwa: 'Frittata', slug: 'frittata-details', obraz: 'assets/images/meals-sniadania/omelette/Frittata.png', dostepne: false },
      { nazwa: 'Eggs-benedict', slug: 'eggs-benedict-details', obraz: 'assets/images/meals-sniadania/omelette/Eggs-benedict.png', dostepne: false },
      { nazwa: 'Spanish', slug: 'spanish-details', obraz: 'assets/images/meals-sniadania/omelette/Spanish.png', dostepne: false },
      { nazwa: 'Mushroom', slug: 'mushroom-details', obraz: 'assets/images/meals-sniadania/omelette/Mushroom.png', dostepne: false },
    ],
  },
  {
    slug: 'osso-buco-details',
    tytul: 'Osso-buco',
    kategoria: false,
    dzieci: [
      { nazwa: 'With-vegetables', slug: 'osso-buco-with-vegetables-details', obraz: 'assets/images/meals-kolacje/osso-buco/With-vegetables.png', dostepne: false },
      { nazwa: 'With-potatoes', slug: 'osso-buco-with-potatoes-details', obraz: 'assets/images/meals-kolacje/osso-buco/With-potatoes.png', dostepne: false },
      { nazwa: 'With-rice', slug: 'osso-buco-with-rice-details', obraz: 'assets/images/meals-kolacje/osso-buco/With-rice.png', dostepne: false },
      { nazwa: 'With-buckwheat', slug: 'osso-buco-with-buckwheat-details', obraz: 'assets/images/meals-kolacje/osso-buco/With-buckwheat.png', dostepne: false },
      { nazwa: 'With-mashed...', slug: 'osso-buco-with-mashed-potatoes-details', obraz: 'assets/images/meals-kolacje/osso-buco/With-mashed....png', dostepne: false },
    ],
  },
  {
    slug: 'pad-thai-details',
    tytul: 'Pad-thai',
    kategoria: false,
    dzieci: [
      { nazwa: 'Classic', slug: 'classic-pad-thai-details', obraz: 'assets/images/meals-obiady/pad-thai/Classic.png', dostepne: false },
      { nazwa: 'Vegetarian', slug: 'vegetarian-pad-thai-details', obraz: 'assets/images/meals-obiady/pad-thai/Vegetarian.png', dostepne: false },
      { nazwa: 'Seafood', slug: 'seafood-pad-thai-details', obraz: 'assets/images/meals-obiady/pad-thai/Seafood.png', dostepne: false },
      { nazwa: 'Chicken', slug: 'chicken-pad-thai-details', obraz: 'assets/images/meals-obiady/pad-thai/Chicken.png', dostepne: false },
      { nazwa: 'Tofu', slug: 'tofu-pad-thai-details', obraz: 'assets/images/meals-obiady/pad-thai/Tofu.png', dostepne: false },
    ],
  },
  {
    slug: 'paella-details',
    tytul: 'Paella',
    kategoria: false,
    dzieci: [
      { nazwa: 'Valencian', slug: 'valencian-paella-details', obraz: 'assets/images/meals-obiady/paella/Valencian.png', dostepne: false },
      { nazwa: 'Seafood', slug: 'seafood-paella-details', obraz: 'assets/images/meals-obiady/paella/Seafood.png', dostepne: false },
      { nazwa: 'Mixed', slug: 'mixed-paella-details', obraz: 'assets/images/meals-obiady/paella/Mixed.png', dostepne: false },
      { nazwa: 'Vegetarian', slug: 'vegetarian-paella-details', obraz: 'assets/images/meals-obiady/paella/Vegetarian.png', dostepne: false },
      { nazwa: 'Black', slug: 'black-paella-details', obraz: 'assets/images/meals-obiady/paella/Black.png', dostepne: false },
    ],
  },
  {
    slug: 'pancakes-details',
    tytul: 'Pancakes',
    kategoria: false,
    dzieci: [
      { nazwa: 'Classic', slug: 'classic-details', obraz: 'assets/images/meals-sniadania/pancakes/Classic.png', dostepne: false },
      { nazwa: 'Blueberry', slug: 'blueberry-details', obraz: 'assets/images/meals-sniadania/pancakes/Blueberry.png', dostepne: false },
      { nazwa: 'Banana', slug: 'banana-details', obraz: 'assets/images/meals-sniadania/pancakes/Banana.png', dostepne: false },
      { nazwa: 'Chocolate-chip', slug: 'chocolate-chip-details', obraz: 'assets/images/meals-sniadania/pancakes/Chocolate-chip.png', dostepne: false },
      { nazwa: 'Buttermilk', slug: 'buttermilk-details', obraz: 'assets/images/meals-sniadania/pancakes/Buttermilk.png', dostepne: false },
    ],
  },
  {
    slug: 'panini-details',
    tytul: 'Panini',
    kategoria: false,
    dzieci: [
      { nazwa: 'Caprese', slug: 'caprese-details', obraz: 'assets/images/meals-sniadania/panini/Caprese.png', dostepne: true },
      { nazwa: 'Turkey', slug: 'turkey-details', obraz: 'assets/images/meals-sniadania/panini/Turkey.png', dostepne: false },
      { nazwa: 'Chicken-pesto', slug: 'chicken-pesto-details', obraz: 'assets/images/meals-sniadania/panini/Chicken-pesto.png', dostepne: false },
      { nazwa: 'Veggie', slug: 'veggie-details', obraz: 'assets/images/meals-sniadania/panini/Veggie.png', dostepne: false },
      { nazwa: 'Italian', slug: 'italian-details', obraz: 'assets/images/meals-sniadania/panini/Italian.png', dostepne: false },
    ],
  },
  {
    slug: 'pasta-details',
    tytul: 'Pasta',
    kategoria: false,
    dzieci: [
      { nazwa: 'Fusilli-with...', slug: 'fusilli-with-pesto-details', obraz: 'assets/images/meals-kolacje/pasta/Fusilli-with....png', dostepne: false },
      { nazwa: 'Spaghetti...', slug: 'spaghetti-bolognese-details', obraz: 'assets/images/meals-kolacje/pasta/Spaghetti....png', dostepne: false },
      { nazwa: 'Penne...', slug: 'penne-arabbiata-details', obraz: 'assets/images/meals-kolacje/pasta/Penne....png', dostepne: false },
      { nazwa: 'Tagliatelle...', slug: 'tagliatelle-carbonara-details', obraz: 'assets/images/meals-kolacje/pasta/Tagliatelle....png', dostepne: false },
      { nazwa: 'Seafood...', slug: 'seafood-linguine-details', obraz: 'assets/images/meals-kolacje/pasta/Seafood....png', dostepne: false },
    ],
  },
  {
    slug: 'pho-details',
    tytul: 'Pho',
    kategoria: false,
    dzieci: [
      { nazwa: 'Beef', slug: 'beef-pho-details', obraz: 'assets/images/meals-kolacje/pho/Beef.png', dostepne: false },
      { nazwa: 'Chicken', slug: 'chicken-pho-details', obraz: 'assets/images/meals-kolacje/pho/Chicken.png', dostepne: false },
      { nazwa: 'Vegetarian', slug: 'vegetarian-pho-details', obraz: 'assets/images/meals-kolacje/pho/Vegetarian.png', dostepne: false },
      { nazwa: 'Seafood', slug: 'seafood-pho-details', obraz: 'assets/images/meals-kolacje/pho/Seafood.png', dostepne: false },
      { nazwa: 'Spicy-beef', slug: 'spicy-beef-pho-details', obraz: 'assets/images/meals-kolacje/pho/Spicy-beef.png', dostepne: false },
    ],
  },
  {
    slug: 'pizza-details',
    tytul: 'Pizza',
    kategoria: false,
    dzieci: [
      { nazwa: 'Margherita', slug: 'pizza-margherita-details', obraz: 'assets/images/meals-obiady/pizza/Margherita.png', dostepne: false },
      { nazwa: 'BBQ-chicken', slug: 'bbq-chicken-pizza-details', obraz: 'assets/images/meals-obiady/pizza/BBQ-chicken.png', dostepne: false },
      { nazwa: 'Hawaiian', slug: 'hawaiian-pizza-details', obraz: 'assets/images/meals-obiady/pizza/Hawaiian.png', dostepne: false },
      { nazwa: 'Margherita...', slug: 'pizza-margherita-con-bufala-details', obraz: 'assets/images/meals-obiady/pizza/Margherita....png', dostepne: false },
      { nazwa: 'Neapolitan', slug: 'neapolitan-pizza-details', obraz: 'assets/images/meals-obiady/pizza/Neapolitan.png', dostepne: false },
      { nazwa: 'Pepperoni', slug: 'pizza-pepperoni-details', obraz: 'assets/images/meals-obiady/pizza/Pepperoni.png', dostepne: false },
      { nazwa: 'Quattro-stagioni', slug: 'quattro-satgioni-pizza-details', obraz: 'assets/images/meals-obiady/pizza/Quattro-stagioni.png', dostepne: false },
      { nazwa: 'Supreme', slug: 'supreme-pizza-details', obraz: 'assets/images/meals-obiady/pizza/Supreme.png', dostepne: false },
      { nazwa: 'White-pizza', slug: 'white-pizza-details', obraz: 'assets/images/meals-obiady/pizza/White-pizza.png', dostepne: false },
      { nazwa: 'Chicago-deep...', slug: 'chicago-deep-dish-details', obraz: 'assets/images/meals-obiady/pizza/Chicago-deep....png', dostepne: false },
    ],
  },
  {
    slug: 'pork-cutlet-details',
    tytul: 'Pork-cutlet',
    kategoria: false,
    dzieci: [
      { nazwa: 'Tonkatsu', slug: 'tonkatsu-details', obraz: 'assets/images/meals-obiady/pork-cutlet/Tonkatsu.png', dostepne: true },
      { nazwa: 'Schnitzel', slug: 'schnitzel-details', obraz: 'assets/images/meals-obiady/pork-cutlet/Schnitzel.png', dostepne: false },
      { nazwa: 'Milanesa', slug: 'milanesa-details', obraz: 'assets/images/meals-obiady/pork-cutlet/Milanesa.png', dostepne: false },
      { nazwa: 'Pork-katsu...', slug: 'pork-katsu-curry-details', obraz: 'assets/images/meals-obiady/pork-cutlet/Pork-katsu....png', dostepne: false },
      { nazwa: 'Cordon-bleu', slug: 'cordon-bleu-details', obraz: 'assets/images/meals-obiady/pork-cutlet/Cordon-bleu.png', dostepne: false },
      { nazwa: 'Schabowy', slug: 'schabowy-details', obraz: 'assets/images/meals-obiady/pork-cutlet/Schabowy.png', dostepne: false },
    ],
  },
  {
    slug: 'pork-ribbs-details',
    tytul: 'Pork-ribbs',
    kategoria: false,
    dzieci: [
      { nazwa: 'Baby-back', slug: 'baby-back-ribs-details', obraz: 'assets/images/meals-obiady/pork-ribbs/Baby-back.png', dostepne: false },
      { nazwa: 'Country-style', slug: 'country-style-ribs-details', obraz: 'assets/images/meals-obiady/pork-ribbs/Country-style.png', dostepne: false },
      { nazwa: 'Spareribs', slug: 'spareribs-ribs-details', obraz: 'assets/images/meals-obiady/pork-ribbs/Spareribs.png', dostepne: false },
      { nazwa: 'St.-louis-style', slug: 'st.-louis-style-ribs-details', obraz: 'assets/images/meals-obiady/pork-ribbs/St.-louis-style.png', dostepne: false },
      { nazwa: 'Tips', slug: 'pork-ribs-tips-details', obraz: 'assets/images/meals-obiady/pork-ribbs/Tips.png', dostepne: false },
    ],
  },
  {
    slug: 'potato-cakes-details',
    tytul: 'Potato-cakes',
    kategoria: false,
    dzieci: [
      { nazwa: 'Traditional', slug: 'traditional-potato-cakes-details', obraz: 'assets/images/meals-kolacje/potato-cakes/Traditional.png', dostepne: false },
      { nazwa: 'Cheese', slug: 'cheese-potato-cakes-details', obraz: 'assets/images/meals-kolacje/potato-cakes/Cheese.png', dostepne: false },
      { nazwa: 'Bacon', slug: 'bacon-potato-cakes-details', obraz: 'assets/images/meals-kolacje/potato-cakes/Bacon.png', dostepne: false },
      { nazwa: 'Sweet', slug: 'sweet-potato-cakes-details', obraz: 'assets/images/meals-kolacje/potato-cakes/Sweet.png', dostepne: false },
      { nazwa: 'Herbed', slug: 'herbed-potato-cakes-details', obraz: 'assets/images/meals-kolacje/potato-cakes/Herbed.png', dostepne: false },
    ],
  },
  {
    slug: 'quiche-details',
    tytul: 'Quiche',
    kategoria: false,
    dzieci: [
      { nazwa: 'Spinach-and...', slug: 'spinach-and-feta-details', obraz: 'assets/images/meals-sniadania/quiche/Spinach-and....png', dostepne: false },
      { nazwa: 'Bacon-and...', slug: 'bacon-and-cheddar-details', obraz: 'assets/images/meals-sniadania/quiche/Bacon-and....png', dostepne: false },
      { nazwa: 'Mushroom-and...', slug: 'mushroom-and-swiss-details', obraz: 'assets/images/meals-sniadania/quiche/Mushroom-and....png', dostepne: false },
      { nazwa: 'Broccoli-and...', slug: 'broccoli-and-cheddar-details', obraz: 'assets/images/meals-sniadania/quiche/Broccoli-and....png', dostepne: false },
      { nazwa: 'Tomato-and...', slug: 'tomato-and-basil-details', obraz: 'assets/images/meals-sniadania/quiche/Tomato-and....png', dostepne: false },
    ],
  },
  {
    slug: 'ramen-details',
    tytul: 'Ramen',
    kategoria: false,
    dzieci: [
      { nazwa: 'Shoyu', slug: 'shoyu-ramen-details', obraz: 'assets/images/meals-obiady/ramen/Shoyu.png', dostepne: false },
      { nazwa: 'Tonkotsu', slug: 'tonkotsu-ramen-details', obraz: 'assets/images/meals-obiady/ramen/Tonkotsu.png', dostepne: false },
      { nazwa: 'Miso', slug: 'miso-ramen-details', obraz: 'assets/images/meals-obiady/ramen/Miso.png', dostepne: false },
      { nazwa: 'Shio', slug: 'shio-ramen-details', obraz: 'assets/images/meals-obiady/ramen/Shio.png', dostepne: false },
      { nazwa: 'Tantanmen', slug: 'tantanmen-ramen-details', obraz: 'assets/images/meals-obiady/ramen/Tantanmen.png', dostepne: false },
    ],
  },
  {
    slug: 'ratatouille-details',
    tytul: 'Ratatouille',
    kategoria: false,
    dzieci: [
      { nazwa: 'Traditional', slug: 'traditional-ratatouille-details', obraz: 'assets/images/meals-obiady/ratatouille/Traditional.png', dostepne: false },
      { nazwa: 'Layered', slug: 'layered-ratatouille-details', obraz: 'assets/images/meals-obiady/ratatouille/Layered.png', dostepne: false },
      { nazwa: 'Niçoise', slug: 'niçoise-ratatouille-details', obraz: 'assets/images/meals-obiady/ratatouille/Niçoise.png', dostepne: false },
      { nazwa: 'Tian', slug: 'tian-ratatouille-details', obraz: 'assets/images/meals-obiady/ratatouille/Tian.png', dostepne: false },
      { nazwa: 'Roulade', slug: 'ratatouille-roulade-details', obraz: 'assets/images/meals-obiady/ratatouille/Roulade.png', dostepne: false },
    ],
  },
  {
    slug: 'ravioli-details',
    tytul: 'Ravioli',
    kategoria: false,
    dzieci: [
      { nazwa: 'Cheese', slug: 'cheese-ravioli-details', obraz: 'assets/images/meals-kolacje/ravioli/Cheese.png', dostepne: false },
      { nazwa: 'Spinach-and...', slug: 'spinach-and-ricotta-ravioli-details', obraz: 'assets/images/meals-kolacje/ravioli/Spinach-and....png', dostepne: false },
      { nazwa: 'Mushroom', slug: 'mushroom-ravioli-details', obraz: 'assets/images/meals-kolacje/ravioli/Mushroom.png', dostepne: false },
      { nazwa: 'Lobster', slug: 'lobster-ravioli-details', obraz: 'assets/images/meals-kolacje/ravioli/Lobster.png', dostepne: false },
      { nazwa: 'Butternut...', slug: 'butternut-squash-ravioli-details', obraz: 'assets/images/meals-kolacje/ravioli/Butternut....png', dostepne: false },
    ],
  },
  {
    slug: 'rice-with-egg-details',
    tytul: 'Rice-with-egg',
    kategoria: false,
    dzieci: [
      { nazwa: 'Tamago-gohan', slug: 'tamago-gohan-details', obraz: 'assets/images/meals-sniadania/rise-with-egg/Tamago-gohan.png', dostepne: false },
      { nazwa: 'Oyakodon', slug: 'oyakodon-details', obraz: 'assets/images/meals-sniadania/rise-with-egg/Oyakodon.png', dostepne: false },
      { nazwa: 'Omurice', slug: 'omurice-details', obraz: 'assets/images/meals-sniadania/rise-with-egg/Omurice.png', dostepne: false },
      { nazwa: 'Fried-rice', slug: 'fried-rice-details', obraz: 'assets/images/meals-sniadania/rise-with-egg/Fried-rice.png', dostepne: false },
    ],
  },
  {
    slug: 'risotto-details',
    tytul: 'Risotto',
    kategoria: false,
    dzieci: [
      { nazwa: 'Alla-milanese', slug: 'rissoto-alla-milanese-details', obraz: 'assets/images/meals-obiady/risotto/Alla-milanese.png', dostepne: false },
      { nazwa: 'Ai-funghi', slug: 'rissoto-ai-funghi-details', obraz: 'assets/images/meals-obiady/risotto/Ai-funghi.png', dostepne: false },
      { nazwa: 'Al-frutti-di...', slug: 'rissoto-al-frutti-di-mare-details', obraz: 'assets/images/meals-obiady/risotto/Al-frutti-di....png', dostepne: false },
      { nazwa: 'Ai-frutti-di...', slug: 'rissoto-ai-frutti-di-bosco-details', obraz: 'assets/images/meals-obiady/risotto/Ai-frutti-di....png', dostepne: false },
    ],
  },
  {
    slug: 'sandwiches-details',
    tytul: 'Breakfast',
    kategoria: false,
    dzieci: [
      { nazwa: 'Club', slug: 'club-details', obraz: 'assets/images/meals-sniadania/sandwiches/Club.png', dostepne: false },
      { nazwa: 'BLT', slug: 'blt-details', obraz: 'assets/images/meals-sniadania/sandwiches/BLT.png', dostepne: false },
      { nazwa: 'Grilled-cheese', slug: 'grilled-cheese-details', obraz: 'assets/images/meals-sniadania/sandwiches/Grilled-cheese.png', dostepne: false },
      { nazwa: 'Reuben', slug: 'reuben-details', obraz: 'assets/images/meals-sniadania/sandwiches/Reuben.png', dostepne: false },
      { nazwa: 'Philly-cheese...', slug: 'philly-chesesteak-details', obraz: 'assets/images/meals-sniadania/sandwiches/Philly-cheese....png', dostepne: false },
    ],
  },
  {
    slug: 'sashimi-details',
    tytul: 'Sashimi',
    kategoria: false,
    dzieci: [
      { nazwa: 'Tuna', slug: 'tuna-sashimi-details', obraz: 'assets/images/meals-kolacje/sashimi/Tuna.png', dostepne: false },
      { nazwa: 'Salmon', slug: 'salmon-sashimi-details', obraz: 'assets/images/meals-kolacje/sashimi/Salmon.png', dostepne: false },
      { nazwa: 'Mackerel', slug: 'mackerel-sashimi-details', obraz: 'assets/images/meals-kolacje/sashimi/Mackerel.png', dostepne: false },
      { nazwa: 'Shrimp', slug: 'shrimp-sashimi-details', obraz: 'assets/images/meals-kolacje/sashimi/Shrimp.png', dostepne: false },
      { nazwa: 'Duck', slug: 'duck-sashimi-details', obraz: 'assets/images/meals-kolacje/sashimi/Duck.png', dostepne: false },
    ],
  },
  {
    slug: 'scrambled-eggs-details',
    tytul: 'Scrambled Eggs',
    kategoria: false,
    dzieci: [
      { nazwa: 'Classic', slug: 'classic-details', obraz: 'assets/images/meals-sniadania/scrambled-eggs/Classic.png', dostepne: false },
      { nazwa: 'Creamy', slug: 'creamy-details', obraz: 'assets/images/meals-sniadania/scrambled-eggs/Creamy.png', dostepne: false },
      { nazwa: 'Cheesy', slug: 'cheesy-details', obraz: 'assets/images/meals-sniadania/scrambled-eggs/Cheesy.png', dostepne: false },
      { nazwa: 'Herbed', slug: 'herbed-details', obraz: 'assets/images/meals-sniadania/scrambled-eggs/Herbed.png', dostepne: false },
      { nazwa: 'Smoked-salmon', slug: 'smoked-salmon-details', obraz: 'assets/images/meals-sniadania/scrambled-eggs/Smoked-salmon.png', dostepne: false },
    ],
  },
  {
    slug: 'shakshouka-details',
    tytul: 'Shakshouka',
    kategoria: false,
    dzieci: [
      { nazwa: 'Spinach-and-feta', slug: 'spinach-and-feta-details', obraz: 'assets/images/meals-sniadania/shakshouka/Spinach-and-feta.png', dostepne: false },
      { nazwa: 'Zucchini-and...', slug: 'zucchini-and-eggplant-details', obraz: 'assets/images/meals-sniadania/shakshouka/Zucchini-and....png', dostepne: false },
      { nazwa: 'Chorizo', slug: 'chorizo-details', obraz: 'assets/images/meals-sniadania/shakshouka/Chorizo.png', dostepne: false },
      { nazwa: 'Bell-pepper-and...', slug: 'bell-pepper-and-chickpea-details', obraz: 'assets/images/meals-sniadania/shakshouka/Bell-pepper-and....png', dostepne: false },
      { nazwa: 'Mushroom-and...', slug: 'mushroom-and-olive-details', obraz: 'assets/images/meals-sniadania/shakshouka/Mushroom-and....png', dostepne: false },
    ],
  },
  {
    slug: 'shrimps-details',
    tytul: 'Shrimps',
    kategoria: false,
    dzieci: [
      { nazwa: 'Scampi', slug: 'scampi-details', obraz: 'assets/images/meals-sniadania/shrimps/Scampi.png', dostepne: false },
      { nazwa: 'Coconut', slug: 'coconut-details', obraz: 'assets/images/meals-sniadania/shrimps/Coconut.png', dostepne: false },
      { nazwa: 'Pad-thai', slug: 'pad-thai-details', obraz: 'assets/images/meals-sniadania/shrimps/Pad-thai.png', dostepne: true },
      { nazwa: 'Coctail', slug: 'coctail-details', obraz: 'assets/images/meals-sniadania/shrimps/Coctail.png', dostepne: false },
      { nazwa: 'Garlic-butter', slug: 'garlic-butter-details', obraz: 'assets/images/meals-sniadania/shrimps/Garlic-butter.png', dostepne: false },
    ],
  },
  {
    slug: 'silesian-noodles-details',
    tytul: 'Silesian-noodles',
    kategoria: false,
    dzieci: [
      { nazwa: 'Traditional', slug: 'traditional-silesian-noodles-details', obraz: 'assets/images/meals-obiady/silesian-noodles/Traditional.png', dostepne: false },
      { nazwa: 'Drop-noodles', slug: 'drop-noodles-details', obraz: 'assets/images/meals-obiady/silesian-noodles/Drop-noodles.png', dostepne: false },
      { nazwa: 'Lazy...', slug: 'lazy-dumplings-details', obraz: 'assets/images/meals-obiady/silesian-noodles/Lazy....png', dostepne: false },
      { nazwa: 'Steamed...', slug: 'steamed-dumplings-details', obraz: 'assets/images/meals-obiady/silesian-noodles/Steamed....png', dostepne: false },
      { nazwa: 'Filled...', slug: 'filled-dumplings-details', obraz: 'assets/images/meals-obiady/silesian-noodles/Filled....png', dostepne: false },
    ],
  },
  {
    slug: 'sniadanie',
    tytul: 'Breakfast',
    kategoria: true,
    dzieci: [
      { nazwa: 'Shakshouka', slug: 'shakshouka-details', obraz: 'assets/images/sniadania/Shakshouka.png', dostepne: true, kuchnia: 'Asian' },
      { nazwa: 'Omelette', slug: 'omelette-details', obraz: 'assets/images/sniadania/Omelette.png', dostepne: true, kuchnia: 'American' },
      { nazwa: 'Eggs', slug: 'eggs-details', obraz: 'assets/images/sniadania/Eggs.png', dostepne: true, kuchnia: 'Regional' },
      { nazwa: 'Crepes', slug: 'crepes-details', obraz: 'assets/images/sniadania/Crepes.png', dostepne: true, kuchnia: 'Regional' },
      { nazwa: 'Pancakes', slug: 'pancakes-details', obraz: 'assets/images/sniadania/Pancakes.png', dostepne: true, kuchnia: 'American' },
      { nazwa: 'Panini', slug: 'panini-details', obraz: 'assets/images/sniadania/Panini.png', dostepne: true, kuchnia: 'Italian' },
      { nazwa: 'Sandwiches', slug: 'sandwiches-details', obraz: 'assets/images/sniadania/Sandwiches.png', dostepne: true, kuchnia: 'Regional' },
      { nazwa: 'Scrambled-eggs', slug: 'scrambled-eggs-details', obraz: 'assets/images/sniadania/Scrambled-eggs.png', dostepne: true, kuchnia: 'Regional' },
      { nazwa: 'Rice-with-egg', slug: 'rice-with-egg-details', obraz: 'assets/images/sniadania/Rice-with-egg.png', dostepne: true, kuchnia: 'Japanese' },
      { nazwa: 'Toasts', slug: 'toasts-details', obraz: 'assets/images/sniadania/Toasts.png', dostepne: true, kuchnia: 'American' },
      { nazwa: 'Miso', slug: 'miso-details', obraz: 'assets/images/sniadania/Miso.png', dostepne: true, kuchnia: 'Japanese' },
      { nazwa: 'Okonomiyaki', slug: 'okonomiyaki-details', obraz: 'assets/images/sniadania/Okonomiyaki.png', dostepne: true, kuchnia: 'Japanese' },
      { nazwa: 'Croissant', slug: 'croissant-details', obraz: 'assets/images/sniadania/Croissant.png', dostepne: true, kuchnia: 'Italian' },
      { nazwa: 'Bread-with-oil', slug: 'bread-with-oil-details', obraz: 'assets/images/sniadania/Bread-with-oil.png', dostepne: true, kuchnia: 'Mediteranan' },
      { nazwa: 'Yoghurt', slug: 'yoghurt-details', obraz: 'assets/images/sniadania/Yoghurt.png', dostepne: true, kuchnia: 'Mediteranan' },
      { nazwa: 'Dim-sum', slug: 'dim-sum-details', obraz: 'assets/images/sniadania/Dim-sum.png', dostepne: true, kuchnia: 'Asian' },
      { nazwa: 'Wonton', slug: 'wonton-details', obraz: 'assets/images/sniadania/Wonton.png', dostepne: true, kuchnia: 'Asian' },
      { nazwa: 'Boba-tea', slug: 'boba-tea-details', obraz: 'assets/images/sniadania/Boba-tea.png', dostepne: true, kuchnia: 'Asian' },
      { nazwa: 'Shrimps', slug: 'shrimps-details', obraz: 'assets/images/sniadania/Shrimps.png', dostepne: true, kuchnia: 'Asian' },
      { nazwa: 'Bruschetta', slug: 'bruschetta-details', obraz: 'assets/images/sniadania/Bruschetta.png', dostepne: true, kuchnia: 'Italian' },
      { nazwa: 'Quiche', slug: 'quiche-details', obraz: 'assets/images/sniadania/Quiche.png', dostepne: true, kuchnia: 'Continental' },
      { nazwa: 'Muesli', slug: 'muesli-details', obraz: 'assets/images/sniadania/Muesli.png', dostepne: true, kuchnia: 'Continental' },
      { nazwa: 'Oatmeal', slug: 'oatmeal-details', obraz: 'assets/images/sniadania/Oatmeal.png', dostepne: true, kuchnia: 'Continental' },
    ],
  },
  {
    slug: 'sour-rye-soup-details',
    tytul: 'Sour-rye-soup',
    kategoria: false,
    dzieci: [
      { nazwa: 'Classic', slug: 'classic-sour-rye-soup-details', obraz: 'assets/images/meals-obiady/sour-rye-soup/Classic.png', dostepne: false },
      { nazwa: 'With-bacon...', slug: 'sour-rye-soup-with-bacon-and-eggs-details', obraz: 'assets/images/meals-obiady/sour-rye-soup/With-bacon....png', dostepne: false },
      { nazwa: 'With-mushroom', slug: 'sour-rye-soup-with-mushroom-details', obraz: 'assets/images/meals-obiady/sour-rye-soup/With-mushroom.png', dostepne: false },
      { nazwa: 'With-white...', slug: 'sour-rye-soup-with-white-sausage-details', obraz: 'assets/images/meals-obiady/sour-rye-soup/With-white....png', dostepne: false },
      { nazwa: 'Vegetarian', slug: 'vegetarian-sour-rye-soup-details', obraz: 'assets/images/meals-obiady/sour-rye-soup/Vegetarian.png', dostepne: false },
    ],
  },
  {
    slug: 'spaghetti-details',
    tytul: 'Spaghetti',
    kategoria: false,
    dzieci: [
      { nazwa: 'Carbonara', slug: 'spaghetti-carbonara-details', obraz: 'assets/images/meals-obiady/spaghetti/Carbonara.png', dostepne: false },
      { nazwa: 'Bolognese', slug: 'spaghetti-bolognese-details', obraz: 'assets/images/meals-obiady/spaghetti/Bolognese.png', dostepne: false },
      { nazwa: 'Aglio-e-olio', slug: 'spaghetti-aglio-e-olio-details', obraz: 'assets/images/meals-obiady/spaghetti/Aglio-e-olio.png', dostepne: false },
      { nazwa: 'Alle-vongole', slug: 'spaghetti-alle-vongole-details', obraz: 'assets/images/meals-obiady/spaghetti/Alle-vongole.png', dostepne: false },
      { nazwa: 'Alla-puttanesca', slug: 'spaghetti-alla-puttanesca-details', obraz: 'assets/images/meals-obiady/spaghetti/Alla-puttanesca.png', dostepne: false },
    ],
  },
  {
    slug: 'sushi-details',
    tytul: 'Sushi',
    kategoria: false,
    dzieci: [
      { nazwa: 'Nigiri', slug: 'nigiri-sushi-details', obraz: 'assets/images/meals-obiady/sushi/Nigiri.png', dostepne: false },
      { nazwa: 'Maki', slug: 'maki-sushi-details', obraz: 'assets/images/meals-obiady/sushi/Maki.png', dostepne: false },
      { nazwa: 'Temaki', slug: 'temaki-sushi-details', obraz: 'assets/images/meals-obiady/sushi/Temaki.png', dostepne: false },
      { nazwa: 'Chirashi', slug: 'chirashi-sushi-details', obraz: 'assets/images/meals-obiady/sushi/Chirashi.png', dostepne: false },
    ],
  },
  {
    slug: 'sweet-crepes-details',
    tytul: 'Sweet-crepes',
    kategoria: false,
    dzieci: [
      { nazwa: 'Nutella-and...', slug: 'nutella-and-banana-crepes-details', obraz: 'assets/images/meals-kolacje/sweet-crepes/Nutella-and....png', dostepne: false },
      { nazwa: 'Strawberry', slug: 'strawberry-crepes-details', obraz: 'assets/images/meals-kolacje/sweet-crepes/Strawberry.png', dostepne: false },
      { nazwa: 'Lemon-and...', slug: 'lemon-and-sugar-crepes-details', obraz: 'assets/images/meals-kolacje/sweet-crepes/Lemon-and....png', dostepne: false },
      { nazwa: 'Blueberry-and...', slug: 'blueberry-and-ricotta-crepes-details', obraz: 'assets/images/meals-kolacje/sweet-crepes/Blueberry-and....png', dostepne: false },
      { nazwa: 'Apple-cinamon', slug: 'apple-cinamon-sweet-crepes-details', obraz: 'assets/images/meals-kolacje/sweet-crepes/Apple-cinamon.png', dostepne: false },
    ],
  },
  {
    slug: 'tagliatelle-details',
    tytul: 'Tagliatelle',
    kategoria: false,
    dzieci: [
      { nazwa: 'Mushroom', slug: 'mushroom-tagliatelle-details', obraz: 'assets/images/meals-kolacje/tagliatelle/Mushroom.png', dostepne: false },
      { nazwa: 'Spinach', slug: 'spinach-tagliatelle-details', obraz: 'assets/images/meals-kolacje/tagliatelle/Spinach.png', dostepne: false },
      { nazwa: 'Shrimp', slug: 'shrimp-tagliatelle-details', obraz: 'assets/images/meals-kolacje/tagliatelle/Shrimp.png', dostepne: false },
      { nazwa: 'Chicken', slug: 'chicken-tagliatelle-details', obraz: 'assets/images/meals-kolacje/tagliatelle/Chicken.png', dostepne: false },
      { nazwa: 'Tomato-sauce', slug: 'tomato-sauce-tagliatelle-details', obraz: 'assets/images/meals-kolacje/tagliatelle/Tomato-sauce.png', dostepne: false },
    ],
  },
  {
    slug: 'tandoori-details',
    tytul: 'Tandoori',
    kategoria: false,
    dzieci: [
      { nazwa: 'Chicken', slug: 'chicken-tandoori-details', obraz: 'assets/images/meals-kolacje/tandoori/Chicken.png', dostepne: false },
      { nazwa: 'Lamb', slug: 'lamb-tandoori-details', obraz: 'assets/images/meals-kolacje/tandoori/Lamb.png', dostepne: false },
      { nazwa: 'Fish', slug: 'fish-tandoori-details', obraz: 'assets/images/meals-kolacje/tandoori/Fish.png', dostepne: false },
      { nazwa: 'Paneer', slug: 'paneer-tandoori-details', obraz: 'assets/images/meals-kolacje/tandoori/Paneer.png', dostepne: false },
      { nazwa: 'Mixed-grill', slug: 'mixed-grill-tandoori-details', obraz: 'assets/images/meals-kolacje/tandoori/Mixed-grill.png', dostepne: false },
    ],
  },
  {
    slug: 'toasts-details',
    tytul: 'Toasts',
    kategoria: false,
    dzieci: [
      { nazwa: 'Avocado', slug: 'avocado-details', obraz: 'assets/images/meals-sniadania/toasts/Avocado.png', dostepne: false },
      { nazwa: 'Egg-in-a-hole', slug: 'egg-in-a-hole-details', obraz: 'assets/images/meals-sniadania/toasts/Egg-in-a-hole.png', dostepne: false },
      { nazwa: 'Cheese-and...', slug: 'cheese-and-tomato-details', obraz: 'assets/images/meals-sniadania/toasts/Cheese-and....png', dostepne: false },
      { nazwa: 'French', slug: 'french-details', obraz: 'assets/images/meals-sniadania/toasts/French.png', dostepne: false },
      { nazwa: 'Ham-and-cheese', slug: 'ham-and-cheese-details', obraz: 'assets/images/meals-sniadania/toasts/Ham-and-cheese.png', dostepne: false },
    ],
  },
  {
    slug: 'tonkatsu-details',
    tytul: 'Tonkatsu',
    kategoria: false,
    dzieci: [
      { nazwa: 'Katsu-don', slug: 'katsu-don-details', obraz: 'assets/images/meals-kolacje/tonkatsu/Katsu-don.png', dostepne: false },
      { nazwa: 'Chicken', slug: 'chicken-tonkatsu-details', obraz: 'assets/images/meals-kolacje/tonkatsu/Chicken.png', dostepne: false },
      { nazwa: 'Pork', slug: 'pork-tonkatsu-details', obraz: 'assets/images/meals-kolacje/tonkatsu/Pork.png', dostepne: false },
      { nazwa: 'Shrimp', slug: 'shrimp-tonkatsu-details', obraz: 'assets/images/meals-kolacje/tonkatsu/Shrimp.png', dostepne: false },
      { nazwa: 'Vegetarian', slug: 'vegetarian-tonkatsu-details', obraz: 'assets/images/meals-kolacje/tonkatsu/Vegetarian.png', dostepne: false },
    ],
  },
  {
    slug: 'trout-details',
    tytul: 'Trout',
    kategoria: false,
    dzieci: [
      { nazwa: 'Rainbow', slug: 'rainbow-trout-details', obraz: 'assets/images/meals-obiady/trout/Rainbow.png', dostepne: false },
      { nazwa: 'Brown', slug: 'brown-trout-details', obraz: 'assets/images/meals-obiady/trout/Brown.png', dostepne: false },
      { nazwa: 'Brook', slug: 'brook-trout-details', obraz: 'assets/images/meals-obiady/trout/Brook.png', dostepne: false },
      { nazwa: 'Lake', slug: 'lake-trout-details', obraz: 'assets/images/meals-obiady/trout/Lake.png', dostepne: false },
      { nazwa: 'Cutthroat', slug: 'cutthroat-trout-details', obraz: 'assets/images/meals-obiady/trout/Cutthroat.png', dostepne: false },
    ],
  },
  {
    slug: 'udon-details',
    tytul: 'Udon',
    kategoria: false,
    dzieci: [
      { nazwa: 'Tofu', slug: 'tofu-udon-details', obraz: 'assets/images/meals-kolacje/udon/Tofu.png', dostepne: false },
      { nazwa: 'Beef', slug: 'beef-udon-details', obraz: 'assets/images/meals-kolacje/udon/Beef.png', dostepne: false },
      { nazwa: 'Chicken', slug: 'chicken-udon-details', obraz: 'assets/images/meals-kolacje/udon/Chicken.png', dostepne: false },
      { nazwa: 'Shrimp', slug: 'shrimp-udon-details', obraz: 'assets/images/meals-kolacje/udon/Shrimp.png', dostepne: false },
      { nazwa: 'Vegetable', slug: 'vegetable-udon-details', obraz: 'assets/images/meals-kolacje/udon/Vegetable.png', dostepne: false },
    ],
  },
  {
    slug: 'vegetable-salad-details',
    tytul: 'Vegetable-salad',
    kategoria: false,
    dzieci: [
      { nazwa: 'Caesar', slug: 'caesar-salad-details', obraz: 'assets/images/meals-kolacje/vegetable-salad/Caesar.png', dostepne: false },
      { nazwa: 'Caprese', slug: 'caprese-salad-details', obraz: 'assets/images/meals-kolacje/vegetable-salad/Caprese.png', dostepne: false },
      { nazwa: 'Cobb', slug: 'cobb-salad-details', obraz: 'assets/images/meals-kolacje/vegetable-salad/Cobb.png', dostepne: false },
      { nazwa: 'Greek', slug: 'greek-salad-details', obraz: 'assets/images/meals-kolacje/vegetable-salad/Greek.png', dostepne: true },
      { nazwa: 'Waldorf', slug: 'waldorf-salad-details', obraz: 'assets/images/meals-kolacje/vegetable-salad/Waldorf.png', dostepne: false },
    ],
  },
  {
    slug: 'wonton-details',
    tytul: 'Wonton-soup',
    kategoria: false,
    dzieci: [
      { nazwa: 'Hong-kong', slug: 'hong-kong-details', obraz: 'assets/images/meals-sniadania/wonton/Hong-kong.png', dostepne: false },
      { nazwa: 'Sichuan', slug: 'sichuan-details', obraz: 'assets/images/meals-sniadania/wonton/Sichuan.png', dostepne: false },
      { nazwa: 'Fried', slug: 'fried-details', obraz: 'assets/images/meals-sniadania/wonton/Fried.png', dostepne: false },
      { nazwa: 'Thai-style', slug: 'thai-style-details', obraz: 'assets/images/meals-sniadania/wonton/Thai-style.png', dostepne: false },
    ],
  },
  {
    slug: 'yakisoba-details',
    tytul: 'Yakisoba',
    kategoria: false,
    dzieci: [
      { nazwa: 'Chicken', slug: 'chicken-yakisoba-details', obraz: 'assets/images/meals-kolacje/yakisoba/Chicken.png', dostepne: false },
      { nazwa: 'Beef', slug: 'beef-yakisoba-details', obraz: 'assets/images/meals-kolacje/yakisoba/Beef.png', dostepne: false },
      { nazwa: 'Vegetarian', slug: 'vegetarian-yakisoba-details', obraz: 'assets/images/meals-kolacje/yakisoba/Vegetarian.png', dostepne: false },
      { nazwa: 'Shrimp', slug: 'shrimp-yakisoba-details', obraz: 'assets/images/meals-kolacje/yakisoba/Shrimp.png', dostepne: false },
      { nazwa: 'Pork', slug: 'pork-yakisoba-details', obraz: 'assets/images/meals-kolacje/yakisoba/Pork.png', dostepne: false },
    ],
  },
  {
    slug: 'yoghurt-details',
    tytul: 'Yogurt',
    kategoria: false,
    dzieci: [
      { nazwa: 'Greek', slug: 'greek-details', obraz: 'assets/images/meals-sniadania/yogurt/Greek.png', dostepne: false },
      { nazwa: 'Priobiotic', slug: 'priobiotic-details', obraz: 'assets/images/meals-sniadania/yogurt/Priobiotic.png', dostepne: false },
      { nazwa: 'Plant-based', slug: 'plant-based-details', obraz: 'assets/images/meals-sniadania/yogurt/Plant-based.png', dostepne: false },
      { nazwa: 'Low-fat', slug: 'low-fat-details', obraz: 'assets/images/meals-sniadania/yogurt/Low-fat.png', dostepne: false },
      { nazwa: 'Fruit-flavored', slug: 'fruit-flavored-details', obraz: 'assets/images/meals-sniadania/yogurt/Fruit-flavored.png', dostepne: false },
    ],
  },
];
